### ISSUE TITLE
Not opening the project.  Inside Iran

### ISSUE THREAD

**Issue by Hamed744** [gradio-app/gradio#10183]
### Describe the bug

Hello, I hope you're doing well. Sometimes, the AI models and spaces on Hugging Face work in Iran, and sometimes they don't. Generally, they are not blocked or filtered, but at times they fail to open, and I need to use a VPN. Please address this issue so that we can access these models and spaces easily and without the need for a VPN. I live in Iran and use these services for various tasks. Thank you

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
![Screenshot_۲۰۲۴-۱۲-۱۱-۲۲-۰۶-۰۸-۲۸۵_com miui gallery](https://github.com/user-attachments/assets/487bb8cc-6264-4ffd-96da-c741d41e29e8)

import gradio as gr

```

### System Info

```shell
Test
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Sorry @Hamed744 but the intermittent access you're experiencing could be due to network restrictions imposed by Iranian internet providers, who may occasionally block or limit access to certain international domains like Hugging Face. We cannot directly control these network-level restrictions within the `gradio` library
