### ISSUE TITLE
Multi-Label Classification support for gradio.Label

### ISSUE THREAD

**Issue by sijunhe** [gradio-app/gradio#1051]
**Is your feature request related to a problem? Please describe.**
Currently the `gradio.outputs.Label` supports the multi-class classification setting, where only 1 class is predicted. In terms of visualization, the predicted class is highlighted in the bar chart and also becomes the `Label` of the component. In the multi-label setting, multiple labels could be predicted and the two above-mentioned visualization scenario doesn't really work.

**Describe the solution you'd like**
We could either add a new class like `gradio.outputs.MultiLabel` that supports multilabel setup, or add an multilabel argument in the  `gradio.outputs.Label` that toggles the behavior. 
Instead of highlighting a single class in the bar chart, we could highlight N classes that passes through some threshold.
I am not sure what is the desired behavior for the `Label` of the component where there are multiple predicted class.

**Comment by abidlabs** [comment]
Nice suggestion. We are working on redesigning our Label component, so it would be good to keep the multilabel use case in mind. cc @gary149 @pngwn

**Comment by abidlabs** [comment]
Hi! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help if you'd like to put together a custom component for this issue

**Comment by abidlabs** [comment]
Will leave this for anyone to develop as a custom component!
