### ISSUE TITLE
[Blocks] Single Column Interface (UnifiedInterface)

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1067]
Forked from #838 

We want to have a new Interface type, Single Column Interface (UnifiedInterface). Which will support 
- Inputless
- Outputless
- No Input No Output
- Combined input/output interfaces(using a component both as an input and output)

Name has some concerns from @abidlabs to not cover all the use cases, feel free to suggest one.

**Comment by FarukOzderim** [comment]
IMO it is cleaner for different layouts to have different Interface types. That way our interface design would be cleaner and we would have an interface type for different layouts.

**Comment by pngwn** [comment]
I think we would be better off using the existing `Interface` class for this.

**Inputless and Outputless Gradio Apps**

I think the simplest possible API for this is:

```py
gr.Interface(fn=fn, outputs=[...])
```

and 

```py
gr.Interface(fn=fn, inputs=[...])
```

This feels very natural to me, almost intuitive. Mainly because it doesn't what you think it would do. "A gradio intereface but with no outputs" or "A gradio intereface but with no inputs". We also havent reserved this API in anyway, our only alternatives when someone passes these arguments to `Interface` are to give a broken layout (two column layout but with nothing in one column, current behaviour) or to throw an error. 

The API is somehwat implicit but very intuitive: it doesn't require users to check the docs for a new class to solve their problem. This kind of API is 'discoverable' just by playing with the args, which imo is a great marker of good API design.

Not a hill I'll die on, but my gut says this is a better design than a new class.

**Unified Interfaces**

I'm generally of the opinion that a kwarg (`unified=True` or `type='unified'` for better future compatibility) is the best option here because it is a variant of `Interface`. However, @abidlabs raised a good point that certain kwargs don't make much sense (or would have no function) when used in the context opf a unified interface.

I Lean towards a kwarg but neutral when considering the point that @abidlabs raised about redundant kwargs.

I know @aliabid94 had some opinions on these kinds of abstractions, so would good to gather those thoughts here.

**Comment by aliabid94** [comment]
I agree with @pngwn , I don't think we need a whole class for a simple usecase. We don't even need another kwarg, why isn't this enough?
```
field = gr.Textbox()
gr.Interface(fn, inputs=field, outputs=field)
```
It's only two lines of code, no need to create another class to manage this case.

**Comment by abidlabs** [comment]
Interesting idea. It could allow us to potentially create "partially" unified interfaces as well perhaps. Good to think about the cases that @FarukOzderim brings up though. Also what would happen in this case:

* `gr.Interface(fn, inputs=[a,c], outputs=[b, a])`

**Comment by pngwn** [comment]
I would keep the rule simple. 

If inputs are the same (equal or the contents of the list are the same length + equal) then unified. Otherwise a normal interface.

**Comment by FarukOzderim** [comment]
> I would keep the rule simple.
> 
> If inputs are the same (equal or the contents of the list are the same length + equal) then unified. Otherwise a normal interface.

I don't see how this solves this case.
>gr.Interface(fn, inputs=[a,c], outputs=[a,b])

IMO from user perspective having `UnifiedInterface` would be better because of
- `Interface` showing different layouts
- having ambiguity with what will happen in the given 4 cases 

In the `UnifiedInterface` there would be a single column where each component is both input and output. If the function returns None or smt decide like `DONT_CHANGE` the component would not update its inner data.

**Comment by pngwn** [comment]
> I don't see how this solves this case.

It does. It would not show a unified interface because it doesn't satisfy this rule "**contents of the list are the same length + equal**"

**Comment by abidlabs** [comment]
I'm leaning towards not having a separate `UnifiedInterface` as well to keep the number of classes small. This is a neat solution that works well: 

> field = gr.Textbox()
> gr.Interface(fn, inputs=field, outputs=field)

To keep things unambiguous, the conditions for a unified interface are:

> inputs and outputs must either both be a single item or both a list
> if inputs + outputs are both a single item they must be referentially equal
> if inputs + outputs are both a list then the each item in the input list must be referentially equal to the equivalent item in the output list.

I'll add that a single-column interface should also be created if:
* `inputs` is `None`, or
* `outputs` is `None`

But in these 2 cases, the behavior is a little different of course. In the case when `inputs` is None, clicking on the Submit button simply runs the function without any input and outputs it in the output component. In the case when `outputs` is None, clicking on the Submit button shows the status indicator, but it does not show any output.

We should think about what buttons make sense to show by default in each of these cases:
* For unified interfaces, we should show the Submit button, Clear button, and Flag buttons all in one row underneath the unified interface
* For output-only Interfaces, we should show the Submit button (maybe call it Generate instead of submit?) and the Flag button
* For input-only Interfaces, we should show the Submit button and Clear button

**Comment by pngwn** [comment]
@abidlabs This all sounds sensible to me.

**Comment by FarukOzderim** [comment]
@abidlabs what is the layout that will appear with this interface?


>gr.Interface(fn, inputs=[a,c], outputs=[a,b])

**Comment by abidlabs** [comment]
> if inputs + outputs are both a list then the each item in the input list must be referentially equal to the equivalent item in the output list.

So in this case, since `b != c`, we would have a non-unified interface, that would look like:

|  a  |  a  |
| c   |  b  |

**Comment by FarukOzderim** [comment]
But `a` is a single component, why are we rendering it in both input and outputs? And their contents will be the same. Isn't this absurd?

**Comment by abidlabs** [comment]
Hmm, I see what you are saying. But this would get messy if we tried to unify the layouts for partially matching lists. Imagine if the `inputs` was `[a, b]` and the `outputs` was `[c, a]`.

For simplicity, how about this: if `inputs` and `outputs` are lists, and they share some elements but not all, we can just throw an exception where we explain to the users that either they must share all of the elements, in which case a unified interface is produced, or they should not share any components, in which case a standard interface is produced.

**Comment by FarukOzderim** [comment]
> Hmm, I see what you are saying. But this would get messy if we tried to unify the layouts for partially matching lists. Imagine if the `inputs` was `[a, b]` and the `outputs` was `[c, a]`.
> 
> For simplicity, how about this: if `inputs` and `outputs` are lists, and they share some elements but not all, we can just throw an exception where we explain to the users that either they must share all of the elements, in which case a unified interface is produced, or they should not share any components, in which case a standard interface is produced.

That's what I am trying to show since the beginning. This approach does not allow using a component both as an input and output at the same time.
However this does:
> IMO from user perspective having UnifiedInterface would be better because of

    Interface showing different layouts
    having ambiguity with Interface about what will happen in the given 4 cases

In the UnifiedInterface there would be a single column where each component is both input and output. If the function returns None or smt decide like DONT_CHANGE the component would not update its inner data.

**Comment by abidlabs** [comment]
I strongly feel that setting `inputs` to `None` or `outputs` to `None` in the `Interface` should produce single-column interfaces, because that is what users would expect. In _no case_ can I imagine a user wanting a two-column interface in which the inputs are missing or outputs are missing. 

For the specific case of unified inputs, I don't feel as strongly. I can see the pros/cons of having a separate `UnifiedInterface` class versus implicitly determining that from the component lists so either way is fine by me!

**Comment by aliabid94** [comment]
I also agree that we shouldn't be expanding to another class when we can handle this intuitively through arguments.

**Comment by FarukOzderim** [comment]
OK then, @aliabid94  would you like to take this on, I think it would be faster with you since you designed Interface with Blocks.

Btw regarding the issue below, if we don't want to give errors, we could just unify input and output sets. First respecting the input order then the output order. Also giving an explanation warning to the user while doing this, where we explain the situation and s/he should use the same lists if there is an intersection.

example: 
[a,b] : [c,a] becomes [a,b,c]
[a,b,e] [e:c:a] becomes [a,b,e,c]

>Hmm, I see what you are saying. But this would get messy if we tried to unify the layouts for partially matching lists. Imagine if the inputs was [a, b] and the outputs was [c, a].
For simplicity, how about this: if inputs and outputs are lists, and they share some elements but not all, we can just throw an exception where we explain to the users that either they must share all of the elements, in which case a unified interface is produced, or they should not share any components, in which case a standard interface is produced.

**Comment by abidlabs** [comment]
> OK then, @aliabid94 would you like to take this on, I think it would be faster with you since you designed Interface with Blocks.

I can take this on, as I'm working on rewriting parts of Interface
