### ISSUE TITLE
Demos and Getting Started out of sync with release gradio (2.9.4)

### ISSUE THREAD

**Issue by hjl** [gradio-app/gradio#1129]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In various demo samples, there are declarations that used to be `input.Image` or `outputs.Label` etc, now they are just `Image` and `Label`, which doesn't work with the current release version of gradio (2.9.4, via `pip install`).

These appear to be for interface changes that are planned for a future release? The changes in the demos show up in #892. 

### Reproduction

Reverting to a form like this:
`image = gr.inputs.Image(shape=(224, 224))` makes the demos runnable with gradio 2.9.4, vs
`image = gr.Image(shape=(224, 224))` fails with current released version.

### System Info

```shell
gradio 2.9.4, ubuntu 18.04 or macos 12.2, python 3.8
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Thank you @hjl, you are 100% right. We should have waited until the 3.0 release before updating the demos. Since we are planning on releasing 3.0 shortly, I'm inclined towards leaving the demos for now, and pointing users to an older commit to run the demos.

In particular, these demos should work correctly with `gradio==2.9.4`: https://github.com/gradio-app/gradio/tree/31f9bc112d263eb3bc2b6fc816c0f004ed5f5e13/demo

**Comment by abidlabs** [comment]
Thanks @hjl. I'll also say that if anyone wants to use the demos that are currently on the `main` branch or from the Getting Started page on the website, you can try the latest pre-release of Gradio: `pip install gradio==2.9b23`. 

You'll find that the getting started page and demos should work fine with this version of Gradio.

**Comment by abidlabs** [comment]
Should be fixed now with the release of `gradio==3.0.2`. Thanks @hjl for creating the issue!
