### ISSUE TITLE
Need help in manipulating code to produce audio output in gradio

### ISSUE THREAD

**Issue by jaslineljy** [gradio-app/gradio#127]
Hi,

Firstly, i would like to say that gradio interface looks amazing, especially with the idea of dragging in the audio files and produce the output. I would really like to implement this onto a model that i am experimenting on, [Demucs](https://github.com/facebookresearch/demucs) (a waveform model that separates input waveform into 4 sources.) so that I am able to show others the big picture of the project in my upcoming assignment. 

However, I am a beginner to machine learning and coding and would really need your assistance. I have tried importing gradio and entered what i have seen in your document to the file:
inputs = gr.inputs.Audio(source="upload", type="numpy", label=None)
outputs = gr.outputs.Audio(type="auto", label=None)
iface = gr.Interface(fn=main,inputs= inputs , outputs=outputs, server_port=7860, server_name="127.0.0.1").launch()

While i managed to open in localhost and able to input the audio file. I am unable to output the results. I got an error `TypeError: main() takes 0 positional arguments but 1 was given.`  I figured out that has got to be passing a/some argument(s) in my main function and return something at the end of the function. After a few days, i manage to finally output something out put it is only 1 stem (vocals)
![image](https://user-images.githubusercontent.com/44189034/109751645-e56bb580-7c19-11eb-9abe-732210da0130.png)

How should i further manipulate the code such that i can produce all 4 output stems (drums, bass, vocals and others) together with the labels?  Would really appreciate if you could **explicitly** tell me the exact code that i should enter for such output.Thank you so much for your time and patience. 
I have attached the necessary file for your reference on what i have done so far
[separate.txt](https://github.com/gradio-app/gradio/files/6073539/separate.txt)

**Comment by aliabid94** [comment]
Hi jaslineljy, glad to hear you're exploring ML with Gradio! The way Gradio works is by wrapping a function that takes inputs and returns outputs, by creating components for each of the function inputs and outputs. In your example, you wrap the function main, which takes no inputs - rather, you are using an argument parser to pass inputs to the entire program, not the function main. You will need to rewrite the code so that these inputs are passed to the main function, at the very least the "tracks" input. Assuming there are 4 audio file outputs, your code will look something like this:
`
inputs = gr.inputs.Audio(source="upload", type="numpy", type="file")

def main(audio_file):
  tracks = audio_file.name
  ... use tracks as 
  return track_1, track_2, track_3, track_4

gr.Interface(main, inputs, ["audio", "audio", "audio", "audio"]).launch();
`

I think it would be helpful for you to go through the [Getting Started](https://gradio.app/getting_started) page to understand how to work with components first!

**Comment by jaslineljy** [comment]
Hi @aliabid94 thank you so much for your help! I manage to make it work after assigning each individual files to track_1,track_2, track_3, track_4. :)

Can i ask if Gradio supports adding extra labels or change labels to the output. Because i see the samples given on Gradio website it seems like it is always default output title. some examples of the output labels i meant can be seen below
![sample](https://user-images.githubusercontent.com/44189034/109755979-f7515680-7c21-11eb-8d8b-446852b8f0fe.png)

**Comment by aliabid94** [comment]
Great! You can add label=“” to the output components to give them custom
labels

**Comment by jaslineljy** [comment]
I am not sure if i am doing it right... i am having errors... is there any examples? 
![image](https://user-images.githubusercontent.com/44189034/109762357-67180f00-7c2b-11eb-9edb-cd9943fc4ddb.png)

**Comment by abidlabs** [comment]
Actually, it would look like this:
```
output1 = gr.outputs.Audio(label="Drums")
output2 = gr.outputs.Audio(label="Bass")
...
gr.Interface(main, inputs, [output1, output2, output3, output4]).launch()
```

**Comment by jaslineljy** [comment]
Thank you so much! Manage to work :)

**Comment by aliabid94** [comment]
Glad we could help @jaslineljy! If you get a chance, try uploading your model as a repo to the Hub [(instructions here)](https://gradio.app/introducing-hosted)
