### ISSUE TITLE
Image mode not supporting alpha channel

### ISSUE THREAD

**Issue by mortium91** [gradio-app/gradio#134]
We noticed for image inputs only rgb and black/white is supported and the alpha channel gets removed. You guys plan to support transparency anytime soon? We use .png's with transparency a lot!

Besides that, Gradio is awesome btw!

**Comment by aliabid94** [comment]
You can actually pass image_mode="RGBA". Thanks for pointing that this is missing from the documentation! We use Pillow for image processing, so any image_mode supported by PIL is supported by gradio

**Comment by Skiddoh** [comment]
Hi, sorry to bother you, but this took me forever to figure out, because inputting a image with alpha channel results in a dummy picture being loaded.
I searched the docs and havent found your hint regarding RGBA as image_mode. It only says ""RGB" if color, or "L" if black and white." at https://gradio.app/docs/#image
