### ISSUE TITLE
String shortcuts in Docs

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1367]
- [X] I have searched to see if a similar issue already exists.

- [ ] We only define shortcuts under specific components. But I think we should also provide them in a stand-alone section.
![image](https://user-images.githubusercontent.com/44067394/170056798-a086602c-6e62-40a7-882a-0d342881e04b.png)
- [ ] Share an example [demo ](https://github.com/gradio-app/gradio/blob/main/demo/blocks_component_shortcut/run.py)to show different ways of using shortcuts.
- [x] Let users know that they can add custom components or templates and contribute to the library

**Comment by FarukOzderim** [comment]
WDYT @aliabd @abidlabs?

**Comment by freddyaboulton** [comment]
@FarukOzderim I like how the string shortcuts are listed per component. What's the benefit of listing them all in one section?

The Docs page will grow shortly with the addition of Events + more components so I think we don't have to put the same information twice.

I like the demo you shared, maybe we can add to the playground later (#1860) but otherwise I think we should close?

**Comment by FarukOzderim** [comment]
I think that's a better classification. 
**Flow:**
User wants to use shortcuts since namings are shorter, however whenever the user wants to learn the shortcut name s/he needs to find the related component, and fetch the shortcut name from there. However if there is a table then the user can easily find the names s/he is searching for.

**Comment by abidlabs** [comment]
@aliabd do you have thoughts on this? I don't have a strong opinion on this. Would it be all right if I removed myself from this -- if you'd like to implement it, go ahead @aliabd

**Comment by aliabd** [comment]
We discussed this and decided that we will no longer document string shortcuts as it makes for a confusing API. We'll still support them but will instead document the template classes. They work the same way but instead of `"shortcut"` it's `gr.Shortcut()` (so `"text"` is`gr.Text()`)

We won't include a standalone section but will replace the string shortcuts section in each component with a template classes section (and explain briefly how it works)

**Comment by FarukOzderim** [comment]
Yeah I totally agree with this, actually wanted to do this a few months ago, but there was a wish for backwards compatibility and ease of usage.

So did you create another issue for `gr.Shortcut` docs?
