### ISSUE TITLE
Interface.launch(share=False) silently creates a public link

### ISSUE THREAD

**Issue by EdAbati** [gradio-app/gradio#1371]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

A public link is always automatically created when _launching_ a Gradio `Interface` inside a Google Colab notebook . This happens also when setting `share=False`.
I may be wrong here, but I couldn't find any part in the docs or in the logs or print statements, that flags this behaviour. The only place I saw it mentioned is: https://github.com/gradio-app/gradio/blob/e4b5d4c1b798f90467fae25507040e49f5e804bd/gradio/blocks.py#L506

I found another side effect, when executing the following in Colab:
``` python
demo = gr.Interface(fn=predict, inputs="text", outputs="text")
demo.launch(share=False)
```

Here `demo.share_url` gets populated (e..g.`'https://12345.gradio.app'`) while `demo.share` is NOT changed but it is still set to `False`.

**Describe the solution you'd like** 

- add a note in the [docs of Interface.launch](https://gradio.app/docs/#launch-header) about this behaviour
- (more permissive behaviour) add an extra print statement to tell the user that the shareable link is always created (for example after `'Colab notebook detected. To show errors in colab notebook, set debug=True in launch()'`)
- (stricter behaviour) raise an Exception if a user set `share=False` in a Colab notebook
- set `self.share` accordingly when it is changed automatically 

If you agree with the request and the approach, I can make a PR for this.
Thank you :)

**Comment by abidlabs** [comment]
Hi @EdAbati this is a really good point. Thanks for creating the issue and proposing various solutions. I agree with all of these steps, and would be in favor of raising an `Exception` if a user set `share=False` in a Colab notebook. 

We should change `share` so that it is `None` by default, which defaults to `True` in colab notebooks and `False` elsewhere. If a user decides to set `share=False` explicitly in a colab, then they should get the Exception.

If you could kindly create the PR, I would be happy to review and merge.

**Comment by EdAbati** [comment]
Hey @abidlabs , sorry no, not yet. These days I played a bit with Gradio for the 'Blocks Party'!
I can have a look at this tomorrow or the day after if it is ok :)

**Comment by abidlabs** [comment]
Yes of course, glad you joined the Blocks Party!
