### ISSUE TITLE
Allow `Gallery` to be used as in input component and upload multiple images

### ISSUE THREAD

**Issue by MohamedAliRashad** [gradio-app/gradio#1379]
- [x] I have searched to see if a similar issue already exists.

I found a similar question [here](https://github.com/gradio-app/gradio/issues/713) but when i tried it. i only was able to upload one image.
What i am looking for is for the `gr.Image` class to have a flag called `multiple_images`. when it's `true` it allows user to upload more than one image and preview it before submission. (it delivers the images as a list of paths to my function).

**Comment by aliabid94** [comment]
For now, using gr.File with file_count="multiple" would be the way to go, @dawoodkhan82 that works right? Will look into batch inputs for Image soon.

**Comment by pngwn** [comment]
Gallery feels like the right way to do this. The only problem is that we currently always match inputs + outputs. What I mean by that is the inputs that a component accepts (when it is being populated as an output) and the values that a component provides (when it is used as an input) are always the same. It would be easy enough to change the interface for the Gallery to accept `{ images: List[string], selected: int }` but ideally when used as an input the gallery wouldn't send the index of the currently selected image but the image itself.

We could inroduce optional `input_value`(the value passed in either as the default value or the result of a predict function) and `output_value`(the value passed to a predict function) to work around issues like this, rather than simply using `value` for all cases. This wouldn't have any bearing on existing components, we could check for `input_value` or `output_value` first and fall back to `value` if they did not exist. We would need to consider how this would interact with other features, such as `js` functions.

**Comment by abidlabs** [comment]
As discussed, moving to 3.x milestone @dawoodkhan82

**Comment by abidlabs** [comment]
Renaming to reflect the new issue. In particular, it would be nice if the Gallery component could allow you to upload a bunch of images, and you could pass in the images, along with some of them selected into your function.

**Comment by abidlabs** [comment]
A good example of where this component would be useful is here: https://huggingface.co/spaces/NimaBoscarino/playlist-generator, where a person could simply click on one of the song pictures to get the lyrics

**Comment by diegoakel** [comment]
This would be super useful!

**Comment by colemanhindes** [comment]
If you use the File option, then on mobile it doesn't take the user to their photos, it takes them to their files, which are often empty

**Comment by abidlabs** [comment]
This is now possible via the `.select()` method and using the `File` component as mentioned earlier. You can now upload a bunch of images, and then as select them to preview them individually. Here's a code snippet to show how that would work:

```py
import gradio as gr

def preview(files, sd: gr.SelectData):
    return files[sd.index].name

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            f = gr.File(file_types=["image"], file_count="multiple")
            i = gr.Image()
            btn = gr.Button()
        with gr.Column():
            o = gr.Image()
    
    f.select(preview, f, i)
    btn.click(lambda x:x, i, o)
    
demo.launch()
```

**Comment by Subhajyotidas** [comment]
Hi, @abidlabs
I have been trying to upload mulitple images and save in a folder in google colab.
I found many ways to upload the files, but did not find any clue to save them in a folder in google colab or google drive.
Any help would be appreciated.

Thanks in advance

**Comment by MohamedAliRashad** [comment]
@pngwn If `Gallery()` will be allowed to upload images. Please, return the current chosen image with the input.

**Comment by MohamedAliRashad** [comment]
@freddyaboulton Is there a way to know the currect image chosen in gallery ?

**Comment by freddyaboulton** [comment]
Yes, use the `select` event of the gallery

**Comment by branaway** [comment]
> Yes, use the `select` event of the gallery

Can you show a sample code snippet yo get the current selected image? thanks

**Comment by branaway** [comment]
> > Yes, use the `select` event of the gallery
> 
> Can you show a sample code snippet yo get the current selected image? thanks

I thought it would be as easy as gallery.getSelectedImage()...

**Comment by freddyaboulton** [comment]
Please see this demo: https://github.com/gradio-app/gradio/blob/main/demo/gallery_component_events/run.py
