### ISSUE TITLE
Support for sliding image comparison

### ISSUE THREAD

**Issue by fcakyon** [gradio-app/gradio#1382]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently, it is possible to compare two vision model output in two separate output visuals as in this demo: https://huggingface.co/spaces/fcakyon/sahi-yolov5
However, it is not easy to spot the differences between two different visuals.

**Describe the solution you'd like**  
It would be easier to visualize/compare two vision model output in a single image with a slider component as https://juxtapose.knightlab.com/
Would it be possible to add such support to Gradio?

**Additional context**  
Here is a minimal demo for the sliding image comparison component in streamlit: https://huggingface.co/spaces/fcakyon/streamlit-image-comparison

**Comment by FarukOzderim** [comment]
Thanks for the suggestion @fcakyon, it looks like it would be nice to support it in Gradio, WDYT @aliabid94, @abidlabs?
Could we have a component that could render multiple images side by side and let users scroll them together?

![image](https://user-images.githubusercontent.com/44067394/170353776-2714672f-a828-4d32-8dec-2f56ea2d143e.png)

**Comment by abidlabs** [comment]
+1, this would be very nice for colorization demos as well

**Comment by aliabid94** [comment]
Interesting. I think it makes sense, we should discuss the best way to implement this.

**Comment by abidlabs** [comment]
Sorry not at the moment. But we're working on a way to let users build custom components, inspired by this feature request. Stay tuned :)

**Comment by abidlabs** [comment]
Hi! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help if you'd like to put together a custom component for this issue

**Comment by abidlabs** [comment]
And now @pngwn has published an Image Slider custom component. Enjoy everyone!

https://huggingface.co/spaces/pngwn/gradio_imageslider

**Comment by wbhu** [comment]
Hi, 

is there a similar tool for video sliders?
