### ISSUE TITLE
Website: demos scrollbars

### ISSUE THREAD

**Issue by gary149** [gradio-app/gradio#1402]
Will it be possible to not have a fixed height for the demos on the website? I think there should never be a scrollbar for the demos: they should take their full height as we do for Spaces (Maybe using an iframe resizer?). I find it makes the UX deceptive, particularly on mobile (very hard to use imo). 

<img width="866" alt="image" src="https://user-images.githubusercontent.com/3841370/170677901-3adc1c48-1212-4818-8742-1a3852f54bd7.png">

Also, having the demos aligned with code blocks will make it look better but it's minor compared to the prior.

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/3841370/170678439-e7e823f3-eae2-41fd-88bd-4bb377f0b550.png">

**Comment by aliabd** [comment]
Since we render the html from python i'm not sure if there's an iframe resizer that can fix the height issues. Without setting the height there is too much white space underneath the interfaces. 

In any case once https://github.com/gradio-app/gradio/pull/1444 is merged which should be done very soon we'll embed all the demos on the website directly which will make it a lot easier to fix these issues. Agree with you that its very hard to use right now

**Comment by gary149** [comment]
Fixed now 👍
