### ISSUE TITLE
Built with gradio footer is not very visible

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1502]
- [X] I have searched to see if a similar issue already exists.

A similar issue is #785, we might also continue from that issue.

Currently `built with gradio` footer is not visible to a new user, and people use Gradio demos without knowing about Gradio IMO.

1. I also think we could have built with Gradio over the Author footer. It gets lost at below(not sure if it currently doable with markdown component being footer)., see image:
![image](https://user-images.githubusercontent.com/44067394/172770654-41d0eb6f-1a9a-4f3e-9d26-81e2dc8b43a9.png)

2. We should also add a gradio icon there so Gradio will enter people's mind more? "built with gradio" looks very alone and is not catchy or attractive.
Smt like this:
![image](https://user-images.githubusercontent.com/44067394/172770685-851af633-d68f-4506-ab92-54aa5d8e0f5f.png)

3. Make the text bolder and easier to catch
![image](https://user-images.githubusercontent.com/44067394/172770945-987248a0-a3c0-4b49-adcd-dbdd168671fe.png)

cc: @gary149 @abidlabs @aliabid94

**Comment by abidlabs** [comment]
With the Stable Diffusion launch, one thing we've noticed is that the cropped pictures don't include the Gradio logo or any Gradio branding. Could we somehow include it in the screenshotted-region? 

Slack discussion: https://huggingface.slack.com/archives/C03T5KLGW92/p1661359744531859

cc @AK391

**Comment by abidlabs** [comment]
This looks very nice @aliabd and very clean!

Some suggestions:
* Adding emojis to each section ("Text", "Images", "Tabular") (side note: love the emoji for "Recipes" itself)
* Consider naming "Text" to "Text & Natural Language Processing", "Images" to "Images & Computer Vision", and "Tabular" to "Tabular Data and Plots"
* Can we add an "Audio & Speech" section and a "Fun" section underneath as well? Inspired by the categories here: https://github.com/gradio-app/awesome-demos
* "Sentiment Analysis" is really "Sentiment Analysis from Speech". It would be good to put a pure text sentiment analysis demo here instead, and then move the sentiment analysis from speech to the Audio section
* Remove "Calculator (live)" as it's too similar to Calculator

I think we should thiknk through whether these specific demos are the "best ones" to use for people wanting "recipes" or "templates", and maybe rearranging the order of the some of the demos. So for example, "GPT-J" should appear before "GPT" because it's a simpler demo and should probably be called "GPT-J from Hugging Face Hug", and "GPT" should be renamed "GPT (Single Textbox)" to make it clear what the value of that demo is. 

Overall, looks great!

**Comment by abidlabs** [comment]
Looks much better now!

Previously:

<img width="115" alt="image" src="https://user-images.githubusercontent.com/1778297/220943759-5fe489fe-90f5-4a40-b043-cd10b72cfb78.png">


Now:

<img width="221" alt="image" src="https://user-images.githubusercontent.com/1778297/220943837-d1e2b115-6f4d-455d-8873-ef4792365610.png">


So I think we can go ahead and close this.
