### ISSUE TITLE
Colorpicker component

### ISSUE THREAD

**Issue by LuigiCerone** [gradio-app/gradio#1622]
- [X] I have searched to see if a similar issue already exists.

# Problem  
I need a colorpicker component in order to input a color in a Gradio application and I couldn't find an existing component in the docs.

# Solution 
Create a new component that allows users to input a color by selection from a colorpicker.

# Additional context
I am available to try to implement this feature with @mfumanelli.

Also discussed [here on Discord](https://discord.com/channels/879548962464493619/988832204182401104).

**Comment by pngwn** [comment]
Hey there, thanks for creating this issue. And thanks for being willing to take this task on.

We don't have any great documentation right now on how to implement new components but the (very) rough process look like this:

- create a new class in [`components.py`](https://github.com/gradio-app/gradio/blob/main/gradio/components.py). You could use a simple example like the [`Textbox`](https://github.com/gradio-app/gradio/blob/main/gradio/components.py#L279) as a good from which to implement, it should be pretty similar to that. I'm not sure how many of the methods are actually required to get a working component. Perhaps @aliabid94 or @abidlabs could add some context on the python side. 
- Import the class in the necessary places (I think this is just [here](https://github.com/gradio-app/gradio/blob/main/gradio/__init__.py) @aliabid94 @abidlabs can confirm)
- Now we should be able to use the component to create a demo. Either use the component in an existing demo or create a new one in `/demo`. Run the demo with `python run.py` from the specific demo folder. This will run the app but the UI will fail because the component has not yet been implemented on the frontend. this is fine.
- [Follow the instructions to get set up with the frontend tooling](https://github.com/gradio-app/gradio/blob/main/ui/README.md). You won't need to run any demos because you have already done that but get `pnpm dev` working. This is similar to just clicking the link generated by running the demo but with developer mode niceness. Now we can develop the actual component on the frontend.
- Figure out where it should live. All new components should be in a package inside of `ui` somewhere. Sometimes we would create a new package but in this case I think we can create another component inside of `ui/forms`. Create a new file in the `src` folder with an appropriate name (must start with an uppercase letter). Add some dummy text/ html just so the component renders something.
- Export the file as a 'named export' in the `index.ts` file by doing `export {default as Colorpicker } from './Filename.svelte`.
- Now we need to create a 'new component' in the actual app (in `ui/app`). Take a look in the `src/components` folder to see an example of how components are structured. Copy/ paste a folder and rename it to get going. Again use something simple like another form input as a base.
- Now we need to go into the `components/directory.ts` and add it to the component map. Just copy/paste a line in there changing the text as appropriate. The key name needs to be the lowercase version of the actual component name in the python library. So if you called the component `ColorPicker` in python then the key of the map should be `colorpicker`
- At this point if everything has been renamed + exported correctly then the preview application (which should have been updating automatically in the background and is running on `localhost:3000`) should show whatever dummy text you placed in the Svelte component.
- Everything is hooked up correctly at this point and you are free to develop the component and iterate on the implementation.

I'm sure I've missed some things, made some errors, or skipped over details but this is a rough breakdown. If you have any issues or questions then feel free to open a draft PR, ask in this issue, or ping me on discord with any questions (discord DMs are also fine).

I hope this breakdown is helpful.

**Comment by FarukOzderim** [comment]
> Hey there, thanks for creating this issue. And thanks for being willing to take this task on.
> 
> We don't have any great documentation right now on how to implement new components but the (very) rough process look like this:
> 
>     * create a new class in [`components.py`](https://github.com/gradio-app/gradio/blob/main/gradio/components.py). You could use a simple example like the [`Textbox`](https://github.com/gradio-app/gradio/blob/main/gradio/components.py#L279) as a good from which to implement, it should be pretty similar to that. I'm not sure how many of the methods are actually required to get a working component. Perhaps @aliabid94 or @abidlabs could add some context on the python side.
> 
>     * Import the class in the necessary places (I think this is just [here](https://github.com/gradio-app/gradio/blob/main/gradio/__init__.py) @aliabid94 @abidlabs can confirm)
> 
>     * Now we should be able to use the component to create a demo. Either use the component in an existing demo or create a new one in `/demo`. Run the demo with `python run.py` from the specific demo folder. This will run the app but the UI will fail because the component has not yet been implemented on the frontend. this is fine.
> 
>     * [Follow the instructions to get set up with the frontend tooling](https://github.com/gradio-app/gradio/blob/main/ui/README.md). You won't need to run any demos because you have already done that but get `pnpm dev` working. This is similar to just clicking the link generated by running the demo but with developer mode niceness. Now we can develop the actual component on the frontend.
> 
>     * Figure out where it should live. All new components should be in a package inside of `ui` somewhere. Sometimes we would create a new package but in this case I think we can create another component inside of `ui/forms`. Create a new file in the `src` folder with an appropriate name (must start with an uppercase letter). Add some dummy text/ html just so the component renders something.
> 
>     * Export the file as a 'named export' in the `index.ts` file by doing `export {default as Colorpicker } from './Filename.svelte`.
> 
>     * Now we need to create a 'new component' in the actual app (in `ui/app`). Take a look in the `src/components` folder to see an example of how components are structured. Copy/ paste a folder and rename it to get going. Again use something simple like another form input as a base.
> 
>     * Now we need to go into the `components/directory.ts` and add it to the component map. Just copy/paste a line in there changing the text as appropriate. The key name needs to be the lowercase version of the actual component name in the python library. So if you called the component `ColorPicker` in python then the key of the map should be `colorpicker`
> 
>     * At this point if everything has been renamed + exported correctly then the preview application (which should have been updating automatically in the background and is running on `localhost:3000`) should show whatever dummy text you placed in the Svelte component.
> 
>     * Everything is hooked up correctly at this point and you are free to develop the component and iterate on the implementation.
> 
> 
> I'm sure I've missed some things, made some errors, or skipped over details but this is a rough breakdown. If you have any issues or questions then feel free to open a draft PR, ask in this issue, or ping me on discord with any questions (discord DMs are also fine).
> 
> I hope this breakdown is helpful.

This looks like a good tutorial for creating custom components. We should create a Guide around this.

**Comment by LuigiCerone** [comment]
Hi, thank you for all this useful information. If we have any problems we will contact you.

Regarding issue #1628, we will try to keep track of all the steps so that we can contribute to the writing of the guide :) .
