### ISSUE TITLE
Avoid unnecessary serialization/deserialization to file when querying huggingface api

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1679]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio developer, I think we should avoid serializing/deserializing Images and Audio to temporary files when querying the hugging face inference api. Consider the following example:

```python
import gradio as gr

interface = gr.Interface.load("models/google/vit-base-patch16-224")
interface.launch()
```

This is the life cycle of the image when querying the predict api:

1. Image comes in base64 format
2. The `preprocess` method on `Image` on interfaces created from the model hub will write this to a temporary file
3. The temporary file will be [converted back to base64](https://github.com/gradio-app/gradio/blob/main/gradio/interface.py#L709) format by the `Image` `deserialize` method since `api_mode` is set to true.
4. The `preprocess` helper for image pipelines will convert the base64 data to binary

We should cut out step 2. I don’t think we need to write to disk just to read it immediately afterwards back to its original format. I think the same applies to Audio-input models on the hub.

This could make the serving responses from the hub faster. 

**Describe the solution you'd like**  
We should avoid writing to file in this case. One possible solution is to add a `base64` `type` to `Image` and `Audio`. That way we can make `deserialize` on `Image` and `Audio` a no-op like we do for `Textbox`? 

**Additional context**

**Comment by abidlabs** [comment]
Yes, great catch! +1 to the suggestion for adding a `"base64"` `type` to the the `Image` and `Audio` (and perhaps `Video` and `File`) components. 

To confirm, I think you are referring to `serialize()` not `deserialize()`, since in Step 3, it is the `serialize()` method that currently [converts the image back to base64](https://github.com/gradio-app/gradio/blob/00a1894bf509f3d91808b1f9d1a1ae48a5267fcc/gradio/components.py#L1478).

We should keep in mind that some users may use the `interface` as a function. So if `called_directly` is `True`, then serialization should still convert the file to base64 format:

```py
import gradio as gr

interface = gr.Interface.load("models/google/vit-base-patch16-224")
interface("filepath.jpg")
```
