### ISSUE TITLE
Add ability to set background color and text color in `gr.Textbox`

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1698]
Motivated by this issue: https://github.com/gradio-app/7guis-gradio/pull/2, we'd like to have support for custom background colors and text colors in the Textbox component. If we can update this parameter via Python, this would allow for some nice custom validation as well.

**Comment by pngwn** [comment]
I think what would be preferable is a series of 'variants' for the textbox (which come with  a set of background + text colors) and then when we do theming, allow these variants to be 'themed' along with everything else. This way we can provide the ability to create 'stand out' boxes (for things like asides, warnings, errors, etc) but still ensure that they work with our existing design.

Where possible, I'd like us to control things like colors, spacing, etc via theming so that users don't need to put on a designer hat in order to create the UIs the want (other than for layouts) but can drop down and make those modification where necessary with themes.

**Comment by freddyaboulton** [comment]
Closing in favor of #1844 !
