### ISSUE TITLE
Test in colab-like environment in CI

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1713]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio developer, I would like to know if a feature or change I am planning to merge (or have merged) will work in google colab. A lot of our users use gradio on colab so it's important to know if we merged something that breaks functionality on that platform.

**Describe the solution you'd like**  
I think we should try to replicate the colab environment as closely as possible on the CI. Some things that are unique to colab:

- Use ptyhon 3.7.13
- Certain functionality is enabled by default on colab, like `share=True`

Does colab have an api? I wonder if we can programmatically install gradio and run a couple of demos directly on colab?

**Additional context**

**Comment by abidlabs** [comment]
I think we can close this issue for several interrelated reasons:
* Colab doesn't have an API nor does Google release a docker image that can be used to replicate the environment in a ci testing environment
* We no longer set `share=True` in a colab notebook by default
* We have a circle ci environment that runs tests on Python 3.7 (actually, Colab now runs python 3.8, but I think it's good if we keep our ci environment 3.7 so that we continue to test and support anyone running Python>=3.7)

**Comment by abidlabs** [comment]
Closing for reasons above^
