### ISSUE TITLE
Text examples look weird when it is the only component in dark mode

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1725]
### Describe the bug

When examples are given for only a single text component, the examples are formatted in a way that's hard to read. They are also not formatted in a single-column table like I would expect.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

def combine(a):
    return a + " Steve"

demo = gr.Interface(combine, inputs=["textbox"], outputs=["textbox"],
                    examples=[["Hello"], ["Hi"]], cache_examples=True)

if __name__ == "__main__":
    demo.launch()
```

### Screenshot

![image](https://user-images.githubusercontent.com/41651716/177679910-985c6fb5-7d64-4d01-8d40-1872f952bcbb.png)

This is not the case when there is more than one component as as example

```python
import gradio as gr

def combine(a, b):
    return (a + " Steve") * int(b)

demo = gr.Interface(combine, inputs=["textbox", "number"], outputs=["textbox"],
                    examples=[["Hello", 3], ["Hi", 5]], cache_examples=True)

if __name__ == "__main__":
    demo.launch()
```

![image](https://user-images.githubusercontent.com/41651716/177680125-07752489-7d43-47cf-a637-db231ce97703.png)

### Logs

```shell
-
```

### System Info

```shell
3.0.24, OSX
```

### Severity

annoying

**Comment by abidlabs** [comment]
This is actually intentional -- when you have a single input component and a lot of examples (particularly images), they look nicer and take up less space when they are shown in the condensed layout above (as opposed to having a table of rows). That being said, it looks like there is something wrong with how the examples are appearing in dark mode (the white background and white font should not be there).

Here's how they look in light mode:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1778297/178080318-5eea7200-0095-41fd-8237-7c31952b0843.png">

**Comment by asheerrizvi** [comment]
Can I take this up?

**Comment by asheerrizvi** [comment]
@freddyaboulton I don't seem to have the permission to do that. Can you help me with this?

**Comment by freddyaboulton** [comment]
@asheerrizvi done!

**Comment by asheerrizvi** [comment]
@freddyaboulton thanks :D

**Comment by asheerrizvi** [comment]
@freddyaboulton have opened a PR for this:

https://github.com/gradio-app/gradio/pull/1780

lmk if you guys need any change.

🎆
