### ISSUE TITLE
Extended support for type annotations

### ISSUE THREAD

**Issue by tiangolo** [gradio-app/gradio#1728]
- [x] I have searched to see if a similar issue already exists.
    * I haven't, but I just had a call with @abidlabs and he asked me to share my ideas here. :sweat_smile: 

**Is your feature request related to a problem? Please describe.**  

Nope, just an upgrade in developer experience.

Right now declaring inputs and making sure the number and types of parameters are correct has to be done in two different places, the `Interface` and the function. This means that refactors can introduce bugs and have to be checked by hand, e.g. removing a parameter, adding a parameter, changing a type, etc. The same for outputs. And there's no internal way to get autocompletion and inline errors for the code and parameters.

**Describe the solution you'd like**  

You could support an interface like this, based on standard type annotations:

```Python
import gradio as gr
import numpy as np
from typing_extensions import Annotated


def greet(
    name: Annotated[str, gr.Textbox()],
    img: Annotated[np.ndarray, gr.Image()],
) -> Annotated[str, gr.Markdown()]:
    return f"Hello, **{name}**! You have an image of {img.shape[0]} by {img.shape[1]}"


demo = gr.Interface(fn=greet)

demo.launch()
```

This would have autocompletion and inline errors for the function. And also contains the information of the parameter types, that can be extracted in the creation of the `Interface`.

And for types that don't require arguments and modifications, Gradio could export a shortcut, I'm showing it inline here:

```Python
import gradio as gr
import numpy as np
from typing_extensions import Annotated

# This would be imported from Gradio
TextboxType = Annotated[str, gr.Textbox()]
ImageType = Annotated[np.ndarray, gr.Image()]
MarkdownType = Annotated[str, gr.Markdown()]


def greet(
    name: TextboxType,
    img: ImageType,
) -> MarkdownType:
    return f"Hello, **{name}**! You have an image of {img.shape[0]} by {img.shape[1]}"


demo = gr.Interface(fn=greet)

demo.launch()
```

In both cases, editors and tools (e.g. mypy) will provide autocompletion and inline errors for the parameters in the function.

**Additional context**  

You can check how to extract these things in Pydantic's source code. Here's an example in the docs extracting `Annotated`: https://pydantic-docs.helpmanual.io/usage/types/#nested-discriminated-unions

You could also check out https://github.com/annotated-types/annotated-types

**Comment by abidlabs** [comment]
A very nice QoL enhancement! Thanks for creating the issue @tiangolo

**Comment by FarukOzderim** [comment]
Thanks for the suggestion @tiangolo, it is awesome. Let us know if you would like to take this on and have any questions, it would be awesome to see you in Gradio's Contributors😄

**Comment by abidlabs** [comment]
Thanks all for participating in this issue. We discussed this but felt the annotated type syntax was a bit too clunky to use for a developer-facing API. We're not going to implement this approach, but instead just released a decorator-based syntax for events that kind of gets at the same idea (bringing event listeners and functions closer together so that its easier to map parameters & input components). 

See: https://github.com/gradio-app/gradio/pull/5395

**Comment by deckar01** [comment]
I think there is still an opportunity to offer a very simple annotation syntax to users who are not running type checkers.

```py
@greet_btn.click(api_name="greet")
def greet(name: name_txt) -> output_txt:
    return f"Hello {name}!"
```

I originally implemented this as [an `@on` decorator](https://github.com/deckar01/oracle/blob/e3cf31d/oracle/gradio/event.py#L7-L18), but it would also work nicely in the new event decorators. The the kwarg inputs/outputs override the annotations to ensure the current syntax functions correctly regardless of how the listeners are (or aren't) annotated.

It is technically possible to instrument component instances so that type checkers resolve them to the correct primitive type ([like I did in marsha](https://gitlab.com/deckar01/marsha/-/blob/master/marsha/format_registry.py?ref_type=heads#L18-22) or with `Annotated`) while maintaining my proposed syntax, but I personally would not want to maintain that in a codebase this large.

**Comment by abidlabs** [comment]
Hi @deckar01 we considered this syntax but didn't use it because we didn't want to break type checking

> It is technically possible to instrument component instances so that type checkers resolve them to the correct primitive type ([like I did in marsha](https://gitlab.com/deckar01/marsha/-/blob/master/marsha/format_registry.py?ref_type=heads#L18-22) or with Annotated) while maintaining my proposed syntax

Can you elaborate a little more? I can see how you could use component *classes* for typing, but how would component *instances* work?

**Comment by deckar01** [comment]
Actually, it looks like type checkers might be a little more strict than when I was writing that code in 2018. Custom types do have to be declared statically. Sorry for the confusion.
