### ISSUE TITLE
Issue with a Gradio button if the returned parameter from the function is too large

### ISSUE THREAD

**Issue by bcm-at-zama** [gradio-app/gradio#1877]
### Describe the bug

This is from https://discuss.huggingface.co/t/having-a-gradio-button-call-a-function-which-returns-large-elements/20731/4 that I raised to the community.

Basically, I want to call a button which calls a function `func` which returns a large value. But, at a moment, when this value is too large, to blocks everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

HOW TO REPRODUCE:
```python
import gradio as gr


def func(how_many):
    x = (
        "We believe people shouldn't care about privacy. Not because it doesn't matter, but because it shouldn't be an issue! From data breaches and surveillance of cloud applications, to blockchain smart contracts where everything is public, doing things privately online is becoming increasingly complicated. The only way to solve this is to make everything encrypted end-to-end, regardless of where the application is running. And the only way this can happen is if homomorphic encryption becomes mainstream."
        * int(how_many)
    )
    return 42, x


demo = gr.Blocks()

with demo:
    gr.Markdown("Hey.")
    n = gr.Number(label="Answer to the universal question:", value=0, interactive=False)
    x = gr.Textbox(label="Random text", max_lines=2, interactive=False)
    how_many = gr.Number(label="Small: no bug, Large (eg, 20000): well", value=2)
    btn = gr.Button(value="Please press")
    btn.click(func, inputs=[how_many], outputs=[n, x])

if __name__ == "__main__":
    demo.launch()
```

Then:
- python3 app.py
- press the button with a small value (eg, the default 2), it works
- press it with something large like 20000, it looks to block and I even see a 0.1/0.0

Remark that, what it changes under the hood, is that what is returned by `func` is larger and larger.

EXPECTED BEHAVIOUR:
for any value `how_many`, it should work. With the `max_lines` of `x`, I would expect the text of the text box to be truncated

WHAT I HAVE:
for large value, the app blocks, and looks dead. 

### Screenshot

<img width="1177" alt="Capture d’écran 2022-07-22 à 19 57 36" src="https://user-images.githubusercontent.com/64148533/180729340-0b97e9b4-3844-473d-8cad-2c710e1a8cfc.png">

### Logs

```shell
I have no error or crash
```

### System Info

```shell
macOS:
ProductName:	macOS
ProductVersion:	11.6.7
BuildVersion:	20G630

gradio.__version__
'3.1.0'
```

### Severity

annoying

**Comment by bcm-at-zama** [comment]
Workaround: in the meantime, I save and load the big data in a file, instead of trying to exchange it with UI elements from Gradio

**Comment by pngwn** [comment]
Interesting. Thanks for filing this issue, we'll take a look into shortly.

**Comment by pngwn** [comment]
@freddyaboulton @abidlabs Could you take a look at this one. The only thing I can see for sure is that with _certain_ values the request errors with a 'unexpected end of JSON'. My guess is that the response is taking up to much memory but it is hard to debug on the frontend because everything just locks up.

I will say that it only locks up some of the time. If I use `20000` then the UI locks up, but if i use `2000000` the UI errors due to the previously mentioned JSON error. What kind of memory constraints will we hit on the server, would a generated response this large hit those limits?

**Comment by freddyaboulton** [comment]
@pngwn If you hit the api manually, you can get a successful response with 20,000.

```bash
curl  -X POST http://127.0.0.1:7861/api/predict -H 'Content-Type: application/json' -d '{"data": [200000], "fn_index": 0}' > resp.txt
```

![image](https://user-images.githubusercontent.com/41651716/186019431-a695b95f-9af6-4df6-aa43-17f54b61946e.png)

I don't think we're hitting a memory limit on the backend server since it's able to successfully complete the response. We may be hitting a memory limit elsewhere on the front-end code?

I think we should close the issue though. @bcm-at-zama was able to find a workaround and using files for transferring large data is the right approach anyways.

**Comment by abidlabs** [comment]
Sounds reasonable to close this issue as well given that @bcm-at-zama has found a reasonable solution! Thanks @freddyaboulton and @pngwn for looking into this.
