### ISSUE TITLE
Grouping Tabs and Tabview freezes the UI in latest relaease 3.1.1

### ISSUE THREAD

**Issue by millermuttu** [gradio-app/gradio#1911]
### Describe the bug

Grouping Tabs and Tabview components within Row() or Column() freezes the web app and makes it non-responsive. 

Had to fall back to previous releases like 3.1.0 or 3.0 to use the Tab feature.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
app = gr.Blocks()

with app:
  gr.Markdown("**This is demo app:**")
  with gr.Box(), gr.Tabs():
    file = gr.File()
    with gr.Row():
      with gr.TabItem(label="plots"):
        gr.Plot()
        gr.Plot()
    with gr.Column():
      with gr.TabItem(label="plots"):
        gr.Plot()
        gr.Plot()

app.launch()
```
    

### Logs

```shell
No logs
```

### System Info

```shell
Gradio version - 3.1.1
System - Windows 64 bit
Python - 3.8
```

### Severity

annoying

**Comment by pngwn** [comment]
I can't repsoduce this with the provided demo. It could be that it was fixed recently.

@millermuttu could you retest this and ensure the problem is still present. If so could you provide additional reproduction steps. The layout looks a bit weird but the tabs remain responsive.

@abidlabs @aliabid94 @freddyaboulton @dawoodkhan82 Can you reproduce?

**Comment by freddyaboulton** [comment]
I can reproduce on 3.1.1 but not on 3.1.3 ! 

![tab_switch](https://user-images.githubusercontent.com/41651716/183126903-98138870-367f-4000-b728-61691c37c937.gif)
