### ISSUE TITLE
can't switch tabs except once 

### ISSUE THREAD

**Issue by santarabantoosoo** [gradio-app/gradio#1928]
### Describe the bug

in a multi-tab application, I can go from first tab to second tab, submit inputs in the second tab. If I tried to get back to the first tab, the app becomes non-functional. I must refresh the app so that it works

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/Santarabantoosoo/Sentiments_topic_modeling_ITALIAN 

### Screenshot

https://user-images.githubusercontent.com/31887357/182272392-f5c169b2-f58b-4b1e-9553-bfae4431f62e.mp4

### Logs

```shell
None
```

### System Info

```shell
3.1.1
```

### Severity

serious, but I can work around it

**Comment by dawoodkhan82** [comment]
Thanks @santarabantoosoo for reporting. We'll take a look into it.

**Comment by abidlabs** [comment]
Hi @santarabantoosoo, this should be fixed with the latest version of gradio (3.1.4). Please upgrade to the latest version of gradio (you can do this in Spaces by specifying the `sdk_version` in the README file) and it should be fixed.

I made a clone of your Space, but using Gradio 3.1.4, to confirm: https://huggingface.co/spaces/abidlabs/Sentiments_topic_modeling_ITALIAN
