### ISSUE TITLE
Gradio demos do not work properly on landing page 

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1958]
### Describe the bug

I'm seeing issues with the Gradio demos on the website (might be related to the recent PR: #1899):

* There is no "processing" message to indicate that the demo is running when you click submit (or draw on the sketchpad)
* The sketchpad does not work after you switch back to it after viewing another demo
* The echocardiogram one works, but I think it would be better if caching was disabled
* The speech verification one does not work at all

@aliabd we should revert the changes in this PR, or find a way to fix soon since this is not a good first impression for gradio users that all of our demos are broken on the landing page!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just visit www.gradio.app

### Logs

```shell
I'm seeing some stuff in the console that might be applicable. For example:

index.9d04c032.js:970 
        
       Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at saveLine (https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:970:15)
    at https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:790:4
    at Array.forEach (<anonymous>)
    at draw_lines (https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:776:9)
    at load_save_data (https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:760:4)
    at handle_canvas_resize (https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:844:3)
    at ResizeObserver.<anonymous> (https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:701:5)
```

### System Info

```shell
Using Microsoft Edge browser on Windows
```

### Severity

serious, but I can work around it

**Comment by aliabd** [comment]
Thanks for listing these @abidlabs 
* The no processing/loading message is an issue with all of the embedded demos. I opened #1960  to track it
* I opened #1961 for the sketchpad issue and will look into it.
* I removed caching in the [echocardiogram space](https://huggingface.co/spaces/gradio/Echocardiogram-Segmentation) 
* Speech verification demo issues not related to embedding, I couldn't figure out what was going on and opened #1962, I tried downgrading the gradio version to 2.9.0 and it still didn't work. Don't think we should downgrade further so I opened #1963 to remove the demo for now.


I don't think we should revert #1899 because there were usability issues with the iframes too, especially with sizing and the pictionary demo

**Comment by abidlabs** [comment]
Thanks @aliabd for creating the individual issues! 

We can close this issue once #1963 is in.

**Comment by freddyaboulton** [comment]
Since #1963 got merged we can close @abidlabs @aliabd ?

**Comment by abidlabs** [comment]
Yes thank you! Let's close this issue, but also do a pypi release soon so that we can get the audio space working again

**Comment by abidlabs** [comment]
Lol just saw your comment here: https://github.com/gradio-app/gradio/issues/1962#issuecomment-1211242715

Thank you!
