### ISSUE TITLE
Add a `Calendar` component 

### ISSUE THREAD

**Issue by tt0203** [gradio-app/gradio#2029]
I don't understand why these component functions haven't been available until now?
such as side navigation components,calendar component,download button and etc.
why gr.Textbox no password text mode?

**Comment by abidlabs** [comment]
These are great suggestions @tt0203! The reason is that for the most part, Gradio has been used to build machine learning demos, where these components are less common.

But these are great suggestions, especially as Gradio expands to more use cases. cc @freddyaboulton I think some of these are very relevant for the data science / dashboard use cases.

**Comment by mustafalhamadsa** [comment]
I would like to give implementing the Calendar component a shot, I personally found a use for it in filling information for my predictive model where I could use a single component more robust to the task instead of multiple.
![image](https://user-images.githubusercontent.com/100326225/190706672-eec8c87b-4413-4baa-b601-565aba34b63b.png)

**Comment by abidlabs** [comment]
Sounds good to me! I think a component that allows easy selection of dates would be quite helpful for data science applications. You'll find this Guide helpful in putting the new component: https://gradio.app/creating_a_new_component/

@pngwn @freddyaboulton @aliabid94 any additional thoughts?

**Comment by abidlabs** [comment]
Hi @mustafalhamadsa would you still be interested in implementing a `DatePicker` component?

**Comment by pngwn** [comment]
Sorry I meant to follow up on this and forgot. Will add some notes soon.

**Comment by mustafalhamadsa** [comment]
> Hi @mustafalhamadsa would you still be interested in implementing a `DatePicker` component?

Hello, I am sorry I just got back.  Heavy heartedly here to tell you that it seems like it would be better to assign this mission to another team.

Thank you very much for your patience, and once again I am sorry.

**Comment by abidlabs** [comment]
As of #2653, we now support email and password textbox types, so renaming this issue

**Comment by abidlabs** [comment]
Hi! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help if you'd like to put together a custom component for this issue

**Comment by abidlabs** [comment]
We now have a custom Gradio component that does exactly this. You can install it here: https://pypi.org/project/gradio-grcalendar/

**Comment by albertvillanova** [comment]
Awesome!

**Comment by abidlabs** [comment]
Ah I believe @freddyaboulton is fixing that custom component -- stay tuned

**Comment by futurestandard** [comment]
me too. I get infinite loading.
And How about gradio-datepicker by same auther?
https://github.com/freddyaboulton/gradio-datepicker
https://pypi.org/project/gradio-datepicker/
I try this v0.0.2 via pip, It works. I want to omit time value but I could not see the v0.0.2 code(0.0.1). I try gradio cc build, but It cannot use it.

**Comment by freddyaboulton** [comment]
Hello! Sorry for the delay. I have updated the calendar component. Here is the Pypi [page](https://pypi.org/project/gradio-calendar/0.0.1/) and you can see an interactive demo here: https://huggingface.co/spaces/freddyaboulton/gradio_calendar

It uses the native html date picker component so the display of the calendar will vary a bit between browsers. Feel free to submit PRs to the space for improvements!

**Comment by abidlabs** [comment]
🔥
