### ISSUE TITLE
Change handler for gradio.Gallery

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2123]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

I used a change handler on the `Image` component to render a "clear" button when the image is loaded. Since the image can be loaded 3-4 different ways through the app, it was convenient to use the `change` handler on the image component, since it would trigger regardless of how the image was loaded.

When I switched to a `Gallery`, however, this broke.

**Describe the solution you'd like**  
A `change` handler that has the same semantics as its equivalent on the `Image` component.

**Additional context**

**Comment by abidlabs** [comment]
Interesting, we hadn't added `.change()` events to output components. It seems reasonable to have some sort of event that fires when a component loads its value, but I think it should have a different name, since `.change()` should be reserved for when a _user_ modifies the input value of a component. (I know `.change()` isn't currently limited to that).

@pngwn what do you think about a `.load()` event trigger to any component that fires when a component loads its output? (It would mirror the `Blocks.load()` event trigger

**Comment by ankrgyl** [comment]
In case it's helpful, here is the code btw: https://huggingface.co/spaces/impira/docquery/blob/main/app.py. This issue in some ways is related to #2107. You can see how there are multiple event handlers which set or unset the state of `image`, `document`, `question`, `output`, `example_image` (`image` is the gallery, and `document` is the variable). Ideally, I could simply update `document` from most of these change handlers, which would trigger updates to things like `image` and `output`, and `image` would trigger changes to `example_image`, etc.
