### ISSUE TITLE
"Cannot read properties of null (reading 'id')" Error while updating a button's visibility

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2194]
### Describe the bug

I upgraded to 3.2 and noticed that updating a button's visibility status no longer seems to work. It crashes with a console error:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
    at Array.K (index.4ddf74a5.js:3853:3701)
    at Object.p (index.037cda16.js:142:72)
    at update_slot_base (index.4ddf74a5.js:126:14)
    at Object.p (index.037cda16.js:40:6)
    at update (index.4ddf74a5.js:615:36)
    at flush (index.4ddf74a5.js:582:13)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

with gr.Blocks() as demo:
    img_clear_button = gr.Button("Clear", visible=False)
    foo = gr.Button()
    foo.click(lambda: gr.update(visible=True), inputs=[], outputs=[img_clear_button])

if __name__ == "__main__":
    demo.launch()
```

If you click the "Run" button you will see the error

### Logs

```shell
N/A
```

### System Info

```shell
In [2]: gradio.__version__
Out[2]: '3.2'
```

### Severity

blocking upgrade to latest gradio version

**Comment by freddyaboulton** [comment]
Hi @ankrgyl ! There is a problem with `gr.update` in 3.2. The fix is in `gradio-3.2.1b2` which is a pre-release. There is also another workaround in #2154 (return a dict `{"visible": True, "__type__": "update"}`) if you prefer to not upgrade.

Here is a gif of your demo working on 3.2.1b2:

![btn_visible_fix](https://user-images.githubusercontent.com/41651716/188894384-d244466d-439c-41c9-b458-04c61c642599.gif)
