### ISSUE TITLE
Scale argument does not work if columns are nested

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2223]
### Describe the bug

If you have nested rows, and you try to set the scale for columns within the nested row, the scale appears to be ignored.

In the screenshot attached, I'd expect the Run button to be 5 times smaller than the textbox.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr
import pandas as pd
import time

with gr.Blocks() as demo:
    with gr.Row():
        gr.Markdown("Left")

        with gr.Row():
            with gr.Column(scale=5):
                a = gr.Textbox()
            with gr.Column(scale=1):
                b = gr.Button()

if __name__ == "__main__":
    demo.launch(enable_queue=True)
```

### Screenshot

![Screen Shot 2022-09-09 at 2 21 29 PM](https://user-images.githubusercontent.com/565363/189447585-9fc55e77-ce33-4dcb-8ba8-6abea80ca7e1.png)

### Logs

```shell
N/A
```

### System Info

```shell
gradio==3.2.1b2
```

### Severity

blocking upgrade to latest gradio version

**Comment by aliabid94** [comment]
oh yikes. will take a look!

**Comment by aliabid94** [comment]
Okay so here's what's happening. Columns have a `min_width` argument that specifies the number of pixels the column must take up. `min_width` is taken into account first before `scale` is considered. By default, `min_width` is 320 pixels.

What you want to do is set the min_width to zero (or whatever you think is appropriate), e.g.
```python
with gr.Blocks() as demo:
    with gr.Row():
        gr.Markdown("Left")

        with gr.Row():
            with gr.Column(scale=5, min_width=0):
                a = gr.Textbox()
            with gr.Column(scale=1, min_width=0):
                b = gr.Button()
```
![Screen Shot 2022-09-13 at 2 34 56 AM](https://user-images.githubusercontent.com/7870876/189867011-b823b3a7-e9fb-4d1b-a2f0-e4b81639b7ae.png)

Let me know if you have any other questions, otherwise feel free to close!

**Comment by aliabid94** [comment]
Because in the nested case, there isn't enough space in the second column to respect the min_width since the screen has been cut in half already for the second column. In the non-nested case, there's a whole screen to work with, so we can respect both min_width and scale.

The purpose of min_width was so things render well on mobile screens, and if there isn't enough space we don't just keep splitting up the horizontal real estate. Let me know how things could be more clear in the docs, or feel free to open a PR against the documentation! (either in `gradio/guides/3)building_with_blocks/2)controlling_layout.md` to edit the  layout guide or in `gradio/gradio/layouts.py` to edit the documentation)

**Comment by ankrgyl** [comment]
Here you go! https://github.com/gradio-app/gradio/pull/2259

I didn't update the guide because it's so short, that it seems out of place to add an extra implementation detail in there. But happy to add more/less per your feedback.
