### ISSUE TITLE
Ability to change brush size

### ISSUE THREAD

**Issue by Theagainmen** [gradio-app/gradio#2228]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When masking/painting an image it is currently not possible to change the brush size. It would be very convenient if this was possible. (The image below shows the default brush size, which is the thing that should be adjustable).
![image](https://user-images.githubusercontent.com/24569139/189521089-21f2475a-d862-47cd-8c81-96258a13be3a.png)

**Describe the solution you'd like**  
Make it possible to adjust the brush size.

**Additional context**  
If the feature request is not clear, please let me know.

**Comment by abidlabs** [comment]
Hi @Theagainmen, thank you for creating this issue. Agreed that this is a current limitation. We are working on a new sketching UI that should be released soon and will solve this problem. See #1721 for the larger issue. Since that issue also includes variation in brush size, I'll go ahead and close this issue

**Comment by Theagainmen** [comment]
Sounds great, thanks for the note!
