### ISSUE TITLE
REQ outplainting with options

### ISSUE THREAD

**Issue by TwistedFromArma** [gradio-app/gradio#2229]
- [ Y] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Often the head or feet or both are cut off. someitmes its the sides cut off by the AI. Its frustrating.

**Describe the solution you'd like**  
An option for outpainitng would let you automatically expand the canvas by 100 or so pixels in any chosen direction. Plus option to auto mask these new areas as where to regenerate the visual.
Plus the options to run the SD AI using the same seed/algorithm/CFG and even description again to fill in the new blank areas. 

**Additional context**  
[Add any other context or screenshots about the feature request here.]
It's been done very well here but that required multiple and involved steps. the author says it was exhausting as theres no itnerface to do this in. 
(https://www.reddit.com/gallery/xb4jr5)

**Comment by abidlabs** [comment]
Hi! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help if you'd like to put together a custom component for this issue

**Comment by abidlabs** [comment]
I'll go ahead and close this issue since we are not planning to include this in the core Gradio library. But happy to help if you are interested in making this a custom Gradio component (feel free to ask questions in this issue).
