### ISSUE TITLE
Gradio Interface is not loading

### ISSUE THREAD

**Issue by nimanpra** [gradio-app/gradio#225]
Hi,

I'm trying to host a gpt2 ML model which I published using huggingface. But the interface is not loading after Hosting. I get this standard gradio interface instead of what I made. Any tips?

![image](https://user-images.githubusercontent.com/13941762/122519634-4b951080-d030-11eb-8ef3-cdee385f58ac.png)

**Comment by aliabid94** [comment]
Taking a look

**Comment by aliabid94** [comment]
Sorry, was an issue on our part, fixed now! 

![image](https://user-images.githubusercontent.com/7870876/122604533-f1de1780-d02a-11eb-8a6e-a6c089c5e829.png)
https://gradio.app/g/nimanpra/GPT2_Genre_Wise_Content_Generator
I did notice your model is extremely slow (perhaps because we don't provide gpu support yet) but you may be able to optimize your function call better - it seems like you load the model in every function call, perhaps you can take this outside the function so it doesn't get run every prediction? 
Feel free to reopen if you have any other issues.

**Comment by Nickil21** [comment]
@aliabid94 Any idea when the GPU inference support would be made available? I am trying to do an ONNX inference session using the CUDAExecutionProvider. Right now, the latency is too much without the GPU when I try to host the demo application. Is there any workaround for the time being?

**Comment by Nickil21** [comment]
Yes, you can see the Gradio demo app [here](https://huggingface.co/spaces/nickil/weakly-supervised-parsing).

**Comment by abidlabs** [comment]
Thanks for asking about upgrading your Space to GPU! I checked with the team, and currently we don't have a self-serve process for this but we can enable your Space(s) manually, but there is a certain monthly charge for that. If you are interested, shoot me an email at abu@hf.co and I'm happy to share more info
