### ISSUE TITLE
Video Gallery Outputs

### ISSUE THREAD

**Issue by fffiloni** [gradio-app/gradio#2298]
[*] I have searched to see if a similar issue already exists.
YES

**Is your feature request related to a problem? Please describe.**  
NO

**Describe the solution you'd like**  
I'd like to be able to display a list of videos outputs as a Gallery, that would work as the images gallery works, but for videos.

**Additional context**  
Context: I made a PySceneDetect demo that can divide a video sequence into every shots it can detect.
Link: [Scene Edit Detection on HuggingFace](https://huggingface.co/spaces/nanomenta/scene-edit-detection)
I use the `gr.List` instead, and display an image Gallery for every first frame of each shot.

**Comment by abidlabs** [comment]
Hey @fffiloni! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help if you'd like to put together a custom component for this issue

**Comment by dawoodkhan82** [comment]
@fffiloni I published a `video_gallery` component using our new custom component workflow. Feel free to try it out (https://pypi.org/project/gradio-videogallery/)

**Comment by dawoodkhan82** [comment]
@abidlabs After seeing how much thumbs up the original issue has, maybe we should add this functionality to core.

**Comment by abidlabs** [comment]
Instead of adding a new component, could we modify `Gallery` to accept images or videos or a combination?

**Comment by dawoodkhan82** [comment]
@abidlabs yeah for sure, wasn't clear but that's what I meant.

**Comment by abidlabs** [comment]
Let's do it

**Comment by fffiloni** [comment]
yay 🎉

**Comment by fffiloni** [comment]
I dropped a simple space to demonstrate the video gallery component, but as you can experiment [here](https://huggingface.co/spaces/fffiloni/gradio-video-gallery), it seems there is a conflict with the File component i use to drop some videos.

**Comment by fffiloni** [comment]
* there's no logs

**Comment by 240db** [comment]
> Let's do it

is the gr.Gallery() already supporting videos?

**Comment by Lyken17** [comment]
> is the gr.Gallery() already supporting videos?

Seems not supported yet

**Comment by rxy1212** [comment]
@abidlabs we do need a video gallery component. And the custom component is too complicated for users.

**Comment by dawoodkhan82** [comment]
@rxy1212 I'll work on this soon.
