### ISSUE TITLE
Microphone cannot be stopped after starting without permissions

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#2325]
### Describe the bug

([internal discussion](https://huggingface.slack.com/archives/C02QZLG8GMN/p1663834347523179))

Using the microphone component in any Gradio app (such as https://huggingface.co/spaces/ysharma/Talk_to_Multilingual_AI_WhisperBloomCoqui), in Chrome, **without** microphone permissions, allows me to click "Record from microphone". Afterward, I cannot click "Stop recording".

The UX should not have allowed me to click "Record", as I didn't give permission. Being stuck in recording was very confusing

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Any gradio app, e.g. https://huggingface.co/spaces/ysharma/Talk_to_Multilingual_AI_WhisperBloomCoqui

### Logs

```shell
-
```

### System Info

```shell
Any version, Chrome
```

### Severity

annoying

**Comment by Nachimak28** [comment]
Have been facing this issue since yesterday so can confirm.
Even after providing the correct permissions in site settings of chrome, the issue persists.
My gradio version is 3.3.1.

This is what the console displays after pressing the record and stop buttons.
![image](https://user-images.githubusercontent.com/23210132/191964337-e4687b93-77fc-4411-81fa-54dfef810746.png)
