### ISSUE TITLE
Show Model Console output/log on gradio output

### ISSUE THREAD

**Issue by djaym7** [gradio-app/gradio#2360]
When one submits, show live log of console outputs on gradio output box.

**Comment by abidlabs** [comment]
Hi @djaym7 thanks for opening the issue. I think you might be referring a feature that is available when you set `show_error=True` in `Interface.launch()` or `Blocks.launch()`.  But as it stands the issue is not clear. 

If you'd like, please reopen the issue and provide more details, including a full code example we can use to reproduce the issue you are experiencing.

**Comment by djaym7** [comment]
If I understand it correctly, it will only show errors, I want to show all the console output errors and not errors.
