### ISSUE TITLE
Split Docs into multiple pages so they can be indexed by google

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#2415]
A common workflow for users is to search the query on google, but then the results only lead to the docs page where they have to search the query again. It might be better to split the docs into multiple pages (which is not uncommon practice, for example: [tailwind](https://tailwindcss.com/docs), [huggingface](https://huggingface.co/docs/tokenizers)) so google can index them.

**Comment by pngwn** [comment]
We need a full search solution before we can do this really because it breaks ctrl + f. I’m also not 100% certain it is necessary, I think most people will go to the Gradio site to search for Gradio solutions. 

I think a full site search that searches docs and guides would be more valuable but is a prerequisite for this anyway really.
