### ISSUE TITLE
Identify the source of the change event (automatic, or manual upload) for video/audio components

### ISSUE THREAD

**Issue by altryne** [gradio-app/gradio#2419]
- [x ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Would like to be able to diffrentiate between a user initiated manual upload to a Video and an automatic value update from somewhere else 

**Describe the solution you'd like**  
Add a .upload event, that causes the .change event to have metadata for the upload. 

**Additional context**  
This is helpful as right now, I have to use 2 separate elements for uploading and for showing a result, I would like that to be 1 element

**Comment by abidlabs** [comment]
Thanks for creating the issue @altryne. Just to confirm, when you say 

> automatic value update from somewhere else

you mean if the `Video` component is being set as the output of some function, correct?

**Comment by pngwn** [comment]
Yeah. The change is fired when the user uploads some media but also when the component data is set via a predict function. There is currently no way to differentiate. 

I actually think having a general change event is quite nice because many people don’t care how the data is set, they just want to know when it is but it would be good to have some way to differentiate.

**Comment by altryne** [comment]
> I actually think having a general change event is quite nice

Completely agree, I think change should work all the time. 

But maybe an .upload event could be fired before so that I could save a reference somehow? Not sure if I overstep with implementation suggestions.
