### ISSUE TITLE
Browse option to take a location as input?

### ISSUE THREAD

**Issue by ML-BOSS** [gradio-app/gradio#249]
Is there any browse option in gradio to take a location as input

**Comment by abidlabs** [comment]
Sorry I don't know what you mean here? Are you saying that you want to include the location of files in a filesystem?

**Comment by ML-BOSS** [comment]
> 
> 
> Sorry I don't know what you mean here? Are you saying that you want to include the location of files in a filesystem?

Thanks for your reply. My question is simple, it may clear you:

https://www.google.com/search?q=textbox+with+browse+button+in+html&client=firefox-b-d&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiwtZCa4YfyAhX0yYsBHcrgBCwQ_AUoAnoECAEQBA&biw=1283&bih=662&dpr=1.25#imgrc=oM3_iYiXsIdmVM

However, in my case no need to upload, just want to take the folder location using browsing instead writing the location in the textbox.

**Comment by aliabid94** [comment]
This is not possible unfortunately - Google Chrome blocks the browser from accessing any directory data of the host machine. When you upload a file or directory, it only shows the uploaded file names but blocks directory information. Since the majority of users use Google Chrome, it doesn't make sense for us to support this.
