### ISSUE TITLE
Improve whitespace of plotly plots

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2500]
### Describe the bug

When using Plotly plots, the box has a lot of whitespace around it which looks awkward.

[Space](https://huggingface.co/spaces/freddyaboulton/repository-statistics)
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/41651716/196788589-9bc7c3f4-9a01-409f-9b79-6bd2dca4bfb0.png">

[Space](https://huggingface.co/spaces/dawood/NYC-Airbnb-Map)
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/41651716/196789559-6109335c-9046-4187-8723-c6623179f6fc.png">

Would be nice if the plots took up the entire space of the box.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use a plotly plot in a demo.

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

annoying

**Comment by pngwn** [comment]
If it is possible to fix this, it will have to be done within plotly itself. Maybe we can give it some config to render differently. It can't be fixed with CSS at least, and definitely not on the gradio side:
<img width="1319" alt="Screenshot 2022-10-24 at 15 48 40" src="https://user-images.githubusercontent.com/12937446/197556042-0722e3a9-537f-4c7d-9348-2983c7e7e8fe.png">
