### ISSUE TITLE
Output images are converted to square images and aspect ratio is distorted

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2504]
### Describe the bug

It seems that in some Spaces, the output images are forced to be squares and this distorts the width/height ratio of the image

E.g. https://twitter.com/osanseviero/status/1582823250832211968

<img width="298" alt="image" src="https://user-images.githubusercontent.com/1778297/196807635-bcb3f6e2-fb9d-4f09-a0af-58748583d77e.png">

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Space: https://huggingface.co/spaces/runwayml/stable-diffusion-inpainting

### Logs

```shell
N/A
```

### System Info

```shell
3.6
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Wonder if it's cause of the `style` on the output Image: https://huggingface.co/spaces/runwayml/stable-diffusion-inpainting/blob/main/app.py#L75

**Comment by osanseviero** [comment]
In this same space having some weird issue with the image being cut by half 

![Screenshot from 2022-10-19 23-33-43](https://user-images.githubusercontent.com/7246357/196809036-dbf90c3d-1982-45d2-b482-b06fc6ac0efb.png)

**Comment by pngwn** [comment]
The bug that @abidlabs is reporting here doesn't look like a bug at all. This isn't a styling issue, the actual image is distorted.

The author of this app has not constrained the image input to a square (https://huggingface.co/spaces/runwayml/stable-diffusion-inpainting/blob/main/app.py#L66) and then resizes to a square without cropping at all, which is expected to squash the image (https://huggingface.co/spaces/runwayml/stable-diffusion-inpainting/blob/main/app.py#L38-L39).

So I think this is expected behaviour. Now, if they _did_ constrain the image to a square, the user wouldn't actually know about it until the image is generated and parts of the mask could be cropped out, so we should definitely improve the UX of the behaviour of the square kwarg for `Image`. There is already an issue for this [here (relevant comment linked)](https://github.com/gradio-app/gradio/issues/2054#issuecomment-1270135880): 

The thing that @osanseviero mentioned is a different bug relating to the way canvas sizes are calculated based upon the source image, as far as I am aware.

**Comment by pngwn** [comment]
I've confirmed this issue is an issue with user code. There are already issues for the other problems noted.
