### ISSUE TITLE
How to control click and submit action buttons

### ISSUE THREAD

**Issue by IsraelAbebe** [gradio-app/gradio#2511]
I have huggingfce space as shown below and I want someone to drow what is shown in the label and return result in the output.

it works for one pass and to redo the process I wanted to click clear button so it would clear the sketchpad and reload the label to show other stuff based on the function I have?

how can I control the action of clear button/

```
  | sketchpad = gr.Sketchpad()
  | sketchpad.shape = (128,128)
  |  
  |  
  | interface = gr.Interface(
  | save,
  | inputs=[gr.Label(value=getrandomstring(),shape = (64,64)),sketchpad],
  | outputs='label',
  | )
  |  
  | interface.launch()
```

![image](https://user-images.githubusercontent.com/15804692/197189710-fed56dd3-15aa-4dc3-b647-3ab84db9b6e9.png)

**Comment by abidlabs** [comment]
Hi @IsraelAbebe to have more fine-grained control over the action of buttons, you should use the lower-level `Blocks` API, as described here: https://gradio.app/blocks_and_event_listeners/

Since this is neither a bug report or a feature request, I'll go ahead and close this issue. For open-ended questions like this, please use our [Forums ](https://discuss.huggingface.co/c/gradio/26) or [Discord](https://t.co/JKepTfXraQ).
