### ISSUE TITLE
Can i change the layout when i click a button?

### ISSUE THREAD

**Issue by MHX1203** [gradio-app/gradio#2539]
for example, I whould like to add a row or change some other layout of the frame when i click a button. how can i do this operation.

thanks.

**Comment by abidlabs** [comment]
Hi @MHX1203 for general to have more control over the layout by clicking on a button, you should use the lower-level Blocks API, as described here: https://gradio.app/blocks_and_event_listeners/

Since this is neither a bug report or a feature request, I'll go ahead and close this issue. For open-ended questions like this, please use our [Forums ](https://discuss.huggingface.co/c/gradio/26)or [Discord](https://t.co/JKepTfXraQ).
