### ISSUE TITLE
Events that are triggered when another event is complete - needed for several bugs

### ISSUE THREAD

**Issue by vzakharov** [gradio-app/gradio#2560]
The `_js` parameter is very useful if you want to do something before running the python code (i.e. making the API call), but sometimes you want to do the opposite.

For example, I’m using [WaveSurfer](http://wavesurfer-js.org/) to display/play audio in my app, and I need to run `wavesurfer.load('/file=preview.wav ')` once the audio is generated.

So far, I’m still struggling to find an optimal solution for this, choosing between:
- Creating an (artificial) checkbox that would fire once the audio is loaded and whose firing will on turn run the script (via `_js`)
- Creating a script HTML as the output of the audio loading function that would do the same

Both approaches look very makeshift, while having a `_js_after_python` would make this really easy and elegant.

Hope this helps!

**Comment by abidlabs** [comment]
@aliabid94 @pngwn as we think about making `js` an officially supported parameter, perhaps we should have both a `js_before` and a `js_after`?

Another idea that might be more useful actually would be to have a `event.then()` function which allows you to trigger events when other events complete. I've needed this use case often and usually have had to come up with a hack

**Comment by abidlabs** [comment]
Actually another more general idea would be to have a `event.then()` function which allows you to trigger events when other events complete. I've needed this use case often and usually have had to come up with a hack

**Comment by pngwn** [comment]
@abidlabs Do you have an example usecase for `event.then()`, I'd like to understand more.

**Comment by abidlabs** [comment]
Sure, @vzakharov's original post is one example, where you could define a regular backend function and then use `.then()` to define a js function that runs after the backend function is complete. [Here's a similar example](https://github.com/gradio-app/gradio/blob/main/demo/sound_alert/run.py), where a sound rings after a prediction is complete. 

There are lots of use cases where people want to do something _after_ a prediction is finished running. I remember seeing a user ask about having a prediction which produces an image and saves it to disk, and then running a 2nd function with that image afterwards. Can't find the issue right now, but it was similar to this one: https://github.com/gradio-app/gradio/discussions/2491

**Comment by vzakharov** [comment]
Oh, `then` would be even better!

Note that this would likely also mean allowing events to only have local
(js) processing without making an API call. (Currently I have to do weird
hacks like intentionally raising a JavaScript error to avoid making a call.)

**Comment by abidlabs** [comment]
@vzakharov can't you just set `fn=None` in your event trigger to avoid making an API call?

**Comment by vzakharov** [comment]
Oh, right, I must have been thinking about another use case, where you have
to either make or not make an API call depending on js results (say, a
confirmation dialog “Are you sure you want to delete …?”).

**Comment by pngwn** [comment]
@abidlabs 

for https://github.com/gradio-app/gradio/discussions/2491 can't you just:
- create a button, add an event listener, add the image component as an input and the gallery as an output. Possible in combination with `gr.Variable` to keep a reference to all images (if you want to append, we would need some state.)

> There are lots of use cases where people want to do something after a prediction is finished running.

I really think it is easier to keep track of state, rather than keeping track of an imperatively described control flow, most UI frameworks (across languages) have moved in this direction for this reason. Couldn't you just respond to the change of the `value` of some component, doing things imperatively means you need to handle all kinds of edge cases, because we'd need a way to prevent the subsequent action from running under certain circumstances. Events are easier to follow when they are discrete and do not need to consider anything outside of themselves, needing to cancel a later event under certain circumstances breaks this simplicity a little. What if we are chaining `.then` multiple times and only want to cancel one of the `.then` calls?

Couldn't you do something like this at the minute:

- add `change` event listener to an output component (which will run when he component value changes)
- prediction runs changing the value of a component(s), this triggers the `change` listener(s) and happens after the prediction.

**Comment by abidlabs** [comment]
> Couldn't you do something like this at the minute:

> add change event listener to an output component (which will run when he component value changes)
prediction runs changing the value of a component(s), this triggers the change listener(s) and happens after the prediction.

Yes that's the approach that I've ended up using (and suggesting to people), but it has one major and one minor drawback:

* The `.change()` event can be triggered by something other than the prediction completing. For example, the output component could be changed manually through user input instead of the prediction completing. Because we have no way of telling the source of the change, both would trigger the subsequent event. 
* If the function completes running and the output value is the same as the current value in the component (i.e. it doesn't "change"), then the `.change()` event is not triggered, and the subsequent function is not run, even though we would like it to
 
Now that I think about it, I'm pretty sure this was the motivation for users requesting the ability to distinguish between a change triggered by user input versus that triggered by a function completing. We could add a specific version of `.change()` that is only triggered when a function updates a component's value, but then that seems equivalent (and a less clear version) of `event.then()`.

> What if we are chaining .then multiple times and only want to cancel one of the .then calls?

Suppose you have the following chain of events: A -> B -> C

* Canceling C has no problem 
* Canceling A or B should mean that that the subsequent events are never triggered. In fact, the subsequent events should never get added to the queue in the first place. Events that are defined via `.then()` should get added to the queue when their parent events finish completing. It seems pretty doable to me?

**Comment by pngwn** [comment]
> Canceling A or B should mean that that the subsequent events are never triggered.

I just feel like it could be slightly messy. What happens if you have 'events' A, B, C, D, E.

You want to run A -> B -> C, if any previous events 'fails' or is cancelled then you want to cancel subsequent events but you always want to run D and E when everything else is done regardless of the success of prior events.

A -> B -> C -> D
A -> B -> C -> E

But how do we ensure everything that will run _has_ run and then trigger E or D? The only APIs i can think of require lots of repetition.

I'm not sure event chaining is the right solution for this usecase but will have a think about it, not sure what an alternative might look like atm.

**Comment by abidlabs** [comment]
Another example that @osanseviero and I just ran into was with this Space: https://huggingface.co/spaces/osanseviero/esmfold

Here's the flow:
1. A user selected a protein name in a dropdown (call it `dropdown`)
2. Based on the protein name selected, a field (call it `field`) is populated with the protein sequence
3. As soon as the field is populated, we'd like to then run another function to show the protein shape in an output (call it `output`) based on the protein sequence (it's an external API that we're calling)

The ideal way to do this would be to do:

```py
ev = dropdown.change(get_sequence, dropdown, field)
ev.then(get_shape, field, output)
```

But there's no good way to get this behavior right now. If you do something like:

```py
dropdown.change(get_sequence, dropdown, field)
dropdown.change(get_shape, field, output)
```

then it uses the _old_ value of the protein sequence

And if you do:

```py
dropdown.change(get_sequence, dropdown, field)
field.change(get_shape, field, output)
```

Then any change to the `field` textbox (like a single character being typed) causes the `get_shape()` function to get called

**Comment by abidlabs** [comment]
Note: this issue is blocking #2965 as we need to trigger an event (flagging) after another event (prediction) is complete.

**Comment by abidlabs** [comment]
To add a few concrete use cases where this has popped up recently:

* We recently wanted to add [visual feedback](https://github.com/gradio-app/gradio/pull/3289) when the Flag button is clicked. It would have been trivial to add this with `.then()`, right now we a very hacky way that also requires people to press the clear button to restore the flag button state if the flagging errors out
* We wanted to [add "auto" flagging](https://github.com/gradio-app/gradio/pulls?q=is%3Apr+is%3Aclosed+auto), which flags every sample that a user runs through the model. It would have been trivial to add this with `.then()`. We ended up not really being able to achieve this. Only the input is flagged, the output is not.
* Chatbot use case ([already discussed in the original PR](https://github.com/gradio-app/gradio/pull/3414)). 

Btw in the first case, we *do* want the subsequent function to run even if the previous function errors out. From what I've seen, this is the more common use case. And this is the harder one to achieve if `.then()` doesn't exist in the library.
