### ISSUE TITLE
Using the Blocks API, setting the default value for the Radio group makes the entire group disabled.

### ISSUE THREAD

**Issue by taesiri** [gradio-app/gradio#2572]
### Describe the bug

Hello,

I am trying to set the default Radio value for a Gradio Blocks demo. Whenever I set the default value for a Radio group, the entire component is shown as disabled. This only happens when I use the Blocks API and not the regular Interface API.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
app = gr.Blocks()
with app:
    checkboxes = {}

    selected_model = gr.Radio(
        ["radio 1", "radio 2", "radio 3"], value="radio 1"
    )

app.launch(debug=True)
```

### Screenshot

![disabled](https://user-images.githubusercontent.com/588431/199027056-ce391fb4-0076-436b-8ebe-6a21361f7155.png)
![disabled2](https://user-images.githubusercontent.com/588431/199027065-3bea1303-1af6-4a42-878b-c4710ae3ec06.png)

### Logs

```shell
No logs, Check the screenshot
```

### System Info

```shell
Gradio 3.7
Tested on Both Chrome and Firefox
```

### Severity

annoying

**Comment by taesiri** [comment]
I just checked and same thing happens for `Checkboxgroup`.

## Code

```python
import gradio as gr

app = gr.Blocks()
with app:
    checkboxes = {}

    selected_model = gr.Checkboxgroup(
        ["chk_1", "chk_2", "chk_3"], value=["chk_1"]
    )

app.launch(debug=False)
```


## Screenshot

![disabled3](https://user-images.githubusercontent.com/588431/199028399-9d5f9300-7375-41d4-9f15-859ae1799f43.png)

**Comment by abidlabs** [comment]
Hi @taesiri, the reason this is happening is because these checkboxes / radio buttons are not used as the input for anything else, so Gradio assumes you are just using it to statically display some choices. If you use them as the input for some function, then they will automatically become interactive. 

Or you can manually set `interactive=True` when you create the `gr.Radio(..., interactive=True)` or  `gr.Checkboxgroup(..., interactive=True)`
