### ISSUE TITLE
Parts of evaluate demo spaces illegible in dark mode

### ISSUE THREAD

**Issue by lvwerra** [gradio-app/gradio#2662]
### Describe the bug

Code text is not legible in dark mode, because the chosen font color is too dark.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Example here in the [accuracy](https://huggingface.co/spaces/evaluate-metric/accuracy) demo space.

![](https://user-images.githubusercontent.com/22726840/201073243-112171db-d814-4c92-9906-1d08e0350132.png)

### Logs

```shell
See above.
```

### System Info

```shell
gradio==3.0.2
```

### Severity

annoying

**Comment by abidlabs** [comment]
@lvwerra sorry I was wrong in my previous message, turns out this issue has already been fixed in the latest version of `gradio`. Example of how code looks now in dark mode:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1778297/202500935-1fd74e9b-41c5-40f5-9528-a00e96a1d56d.png">

**Comment by abidlabs** [comment]
Will close as this is already fixed.

**Comment by lvwerra** [comment]
Thanks!
