### ISSUE TITLE
Support for Hotkeys

### ISSUE THREAD

**Issue by wiseyoungbuck** [gradio-app/gradio#2670]
From what I can tell, hotkeys/shortcut keys are no supported by Gradio. 
I would like to be able to attach hotkeys to my Gradio apps/buttons to improve the UX.

**Comment by abidlabs** [comment]
Hi @wiseyoungbuck thanks for the suggestion, but this feels a little niche to me. Potentially we could let users define their own  javascript, as proposed in #2137

**Comment by abidlabs** [comment]
I'm going to close this issue, but if other users feel similarly, please chime in with use cases and we can potentially change our mind.

**Comment by thiswillbeyourgithub** [comment]
Hi!

> I'm going to close this issue, but if other users feel similarly, please chime in with use cases and we can potentially change our mind.

I'm a user with a use case.

I found that gradio was the easiest way for me to quickly get a project going where I'm using whisper and chatgpt a lot. I needed a flexible UI but very quickly.

My use case is that I often manually check the output of the LLM when some datapoints feel tricky (out of vocabulary words for example).

It would be very helpful if I could use hotkeys instead of manually clicking on the buttons each time.

I could settle for a version using _js but have yet to find a well explained implementation.

I have to say, I'm surprised you consider hotkeys a niche given that gradio is focused on human-ML  interaction, which can be repetitive given the amount of data.

Thanks and have a nice day!

**Comment by abidlabs** [comment]
Thanks @thiswillbeyourgithub for providing additional info.

> It would be very helpful if I could use hotkeys instead of manually clicking on the buttons each time.

This makes sense. However, it's worth keeping in mind that we do not have the notion of being focused in on your app meaning that any hotkeys would override browser defaults which we do not want to encourage. 

I think the best compromise would be to not have this as an official feature, but make it easier to add custom javascript if a user *really* wants to do this and knows what they are doing. We'll work on the js stuff soon
