### ISSUE TITLE
Display Audio files in a playable format in the Dataset component

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2678]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
It would be nice if the Dataset component was able to display audio files in a playable format like the dataset api on the hub:

![image](https://user-images.githubusercontent.com/41651716/202820975-3784b75c-141e-49ba-8dd4-70bdf17f04cf.png)

Would help with #2677 and I think it could help with the traditional ML demo use case as well. 

**Describe the solution you'd like**  
Make audio components playable in the Dataset class

**Additional context**

**Comment by abidlabs** [comment]
+1

**Comment by abidlabs** [comment]
I actually don't think we should do this. When selecting examples in a `gr.Dataset`, (unlike images) it is more meaningful to have the name of the audio file rather than a mysterious audio file that you have to listen to understand. For the dataset use case, we can suggest users to use `gr.DataFrame` instead, as described here: https://github.com/gradio-app/gradio/issues/8270
