### ISSUE TITLE
a W&B report block

### ISSUE THREAD

**Issue by scottire** [gradio-app/gradio#2757]
A little bit of syntactic sugar to embed W&B reports easily.
It would allow people to easily show off their experimental details / model training / interactive Tables within their Gradio apps.

a user calls `gr.wandb_report` (not very opinionated about the API) with a link to their W&B report and it would embed it within the Gradio app.

working example
```python
import gradio as gr

def wandb_report(url):
    iframe = f'<iframe src={url} style="border:none;height:1024px;width:100%">'
    return gr.HTML(iframe)

with gr.Blocks() as demo:
    report = wandb_report('https://wandb.ai/_scott/pytorch-sweeps-demo/reports/loss-22-10-07-16-00-17---VmlldzoyNzU2NzAx')

demo.launch(share=True)
```

**Comment by scottire** [comment]
I updated the above with a working example. Happy to open a PR if that would be helpful

**Comment by abidlabs** [comment]
Thanks @scottire, thanks for updating the code example. I'm not sure if we need a dedicated a method in the gradio codebase, since it's quite straightforward to implement as you've shown here. However, a good place for describing this method would be in the guide that we have for integrating with W&B: https://github.com/gradio-app/gradio/blob/main/guides/04_integrating_other_frameworks/Gradio_and_Wandb_Integration.md

Currently, the Guide focusing on integrating Gradio *into* a Weights & Biases report. But it would be great to add a section going the other way around, like what you have here. Would you be open to making a PR and adding that section?

**Comment by scottire** [comment]
Great, I'll add that change. 

> I'm not sure if we need a dedicated a method in the gradio codebase, since it's quite straightforward to implement as you've shown here
I think it would be a nice utility function, agreed it's pretty light but so are the `integrate` methods.
