### ISSUE TITLE
support Audio IO in Chatbot

### ISSUE THREAD

**Issue by sijunhe** [gradio-app/gradio#2768]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Given that Chatbot now supports images after v3.12.0, I think we should double down on the multi-modality and add Audio IO to the chatbot interface. It will be a great interface for Voice Assistant demos.

**Describe the solution you'd like**  
Gradio already all the building blocks for this feature and just need to put it together. I think something like the WeChat interface will be nice. Inside the chatbot interface, we replace each text with a bar, which is the Audio output and plays the audio when clicked. Then we can put the audio input button somewhere prominent for easy input. 
![image](https://user-images.githubusercontent.com/11987277/206097158-e86652ce-3923-4825-b8f8-2c092234f742.png)

**Comment by paulocoutinhox** [comment]
+1

**Comment by abidlabs** [comment]
cc @dawoodkhan82

**Comment by rishikeshF** [comment]
+1

**Comment by abidlabs** [comment]
Hi @rishikeshF you can already add audio files to your `gr.Chatbot` as long as you are using the latest version of gradio. Upgrade to the latest version (`pip install --upgrade gradio`) and then take a look at this section to add media files: https://gradio.app/creating-a-chatbot/#adding-markdown-images-audio-or-videos

**Comment by jpmcarrilho** [comment]
Hello, I'm building a full ai assistant bot on top of gradio (wwd, s2t, information retrial), I have to control many interfaces and components rendering or given outputs. There's no good reactive and fast response on any component, but the chatbot element, that's why I love it. It's very powerful and straightforward usage. But this issue is still not finished I think, we need the capability of recording audio the same way we write a text and press enter to interact now: record with audio, stop recording, press enter, deal with the possible post-process (wav2vec2, whisper), use LLMs and neural search. I think this is the correct implementation. And the field tendency is to add more and more multimodality, write, record, and send an image, as of today's 'XXX GPTs'. This implementation would certainly be a nice addition to the library.

**Comment by abidlabs** [comment]
Hi @jpmcarrilho just to confirm, you'd like to be able to record audio, do some preprocessing and display it in a Chatbot? This is already possible by using the `gr.Audio(source="microphone")` component

**Comment by jpmcarrilho** [comment]
Yes, sorry for the bad english, I want to be able to record the gr.Audio and click in 'stop recording', press enter and send it directly to the chat, or sendit after the click in stop. I saw the docs but they only cover files upload. Can you provide me a reference of the Audio component being sent to the chat bot as soon as i stop recording?

**Comment by abidlabs** [comment]
No worries @jpmcarrilho. Yes this is currently possible in Gradio, you could do something like this:

```py
import os

def get_chatbot_response(x):
    os.rename(x, x + '.wav')
    return [((x + '.wav',), "Your voice sounds nice!")]

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    mic = gr.Audio(source="microphone", type="filepath")
    mic.change(get_chatbot_response, mic, chatbot)
    
demo.launch()
```

(The `os.rename` part is because of a bug that we'll be fixing shortly). 

Whicih produces this:

![81623eca-dd8f-4d0c-9698-8f84a0224248](https://user-images.githubusercontent.com/1778297/230179069-ec1fea12-a160-4c44-9213-b0b3214fdd87.gif)

**Comment by jpmcarrilho** [comment]
Well, thank you that is exactly what I needed.

**Comment by rc-eddy** [comment]
@abidlabs is there an option to auto-play chatbot responses?

**Comment by dawoodkhan82** [comment]
@rc-eddy currently, there isn't. Although I'll look into adding that when I refactor the chatbot.

**Comment by dawoodkhan82** [comment]
@lehic  So auto-playing audio is not supported in most browsers. There are some workarounds you can try in this issue: https://github.com/gradio-app/gradio/issues/1349. But playing audio without user interaction is generally discouraged.
