### ISSUE TITLE
Subtitle support for gr.Video component

### ISSUE THREAD

**Issue by fcakyon** [gradio-app/gradio#2945]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I am currently using a Gradio-based web application for video+subtitle labeling but I have to use Video+Textbox components to show the video and subtitle separately and cannot synchronize the subtitle as the video flows. It would be much better if subtitles could be rendered inside gr.Video component.

**Describe the solution you'd like**  
Adding subtitle argument (file path or URL to an `.srt` formatted subtitle file) to gr.Video component and subtitle text will be shown over the video.

```python
import gradio as gr

video = gr.Video(value='video.mp4', subtitle='subtitle_file.srt')
```

```python
import gradio as gr

video_path_or_url = Textbox()
video_subtitle_path_or_url = Textbox()
video_with_subtitle = gr.Video()

def set_video(file_path, subtitle_path):
     return {
        video_with_subtitle: gr.update(value=file_path, subtitle=subtitle_path)
    }

demo = gr.Interface(
    fn=set_video,
    inputs=[video_path_or_url, video_subtitle_path_or_url],
    outputs=video_with_subtitle
)

demo.launch() 
```

**Additional context**  
Desired output would look like this:
<img width="500" alt="demo" src="https://user-images.githubusercontent.com/34196005/211105468-52fad6d3-48c6-45d3-9424-72a57f4a7f3a.png">

**Comment by abidlabs** [comment]
Great feature suggestion @fcakyon! 👍

**Comment by pngwn** [comment]
Related discussion: https://github.com/gradio-app/gradio/discussions/2968

**Comment by tomchang25** [comment]
Maybe you would like to check this [demo](https://github.com/tomchang25/gradio/blob/main/demo/video_with_caption/run.py)
```
import gradio as gr

css = (
    "footer {display: none !important;} .gradio-container {min-height: 0px !important;}"
)

with gr.Blocks(css=css) as demo:
    gr.Video(
        label="Video File Test",
        show_label=True,
        interactive=True,
        value="mp4/en.mp4",
        caption="tmp/en.vtt",
    )

demo.launch()

```
![image](https://user-images.githubusercontent.com/31534748/211816981-851cd802-8b11-4fbb-aedf-61be651e79ed.png)

But I just learned how to code svelte since last month, so there are lots of "dirty" code.
Any suggestion will be appreciate.

**Comment by fcakyon** [comment]
> Maybe you would like to check this [demo](https://github.com/tomchang25/gradio/blob/main/demo/video_with_caption/run.py)
> 
> ```
> import gradio as gr
> 
> css = (
>     "footer {display: none !important;} .gradio-container {min-height: 0px !important;}"
> )
> 
> with gr.Blocks(css=css) as demo:
>     gr.Video(
>         label="Video File Test",
>         show_label=True,
>         interactive=True,
>         value="mp4/en.mp4",
>         caption="tmp/en.vtt",
>     )
> 
> demo.launch()
> ```
> 
> ![image](https://user-images.githubusercontent.com/31534748/211816981-851cd802-8b11-4fbb-aedf-61be651e79ed.png)
> 
> But I just learned how to code svelte since last month, so there are lots of "dirty" code. Any suggestion will be appreciate.

Does your implementation support srt files?

**Comment by pngwn** [comment]
I think questions that @tomchang25 asked would be really good to answer and I'd be curious to get people's thoughts on this:

> 1. How should subtitles value like?
> Currently I just put it as value of a List (video path, caption path).
> Would it better if cation path become another class variable in video?
> 
> 2. How should subtitles input like?
> My custom component didn't allow user to upload custom subtitles, should I modify Svelte to add addition > slot to do this?
> Or just put other File components to do same thing?

**Comment by tomchang25** [comment]
@fcakyon I implemented this feature by using html5 track element and only VTT files are supported currently.Maybe add a little conversion function to convert it from srt to vtt?

**Comment by fcakyon** [comment]
In my use case I have to strictly use srt files.

**Comment by tomchang25** [comment]
Add some new feature and this is [demo](https://github.com/tomchang25/gradio/blob/main/demo/video_with_caption/run.py)
1. Support srt format by converting it to vtt format by [pysubs2](https://github.com/tkarabela/pysubs2)
2. Support caption update by other components, i.e. , File or Textbox.
3. Because gradio is only allow temp file created by TempFileManager, so I convert caption file to base64 to bypass this issue.

and here is my ideas about this new feature

## How should subtitles value like?

Currently I think using caption attribute instead add it to value has more advantage because most of video would not need subtitle/caption, and on top of that, we don't need to modify original value too much to implement this feature.

## How should subtitles input like?

Same reason as above. I think using another component is on the right path.

## Other format support

I have use pysubs2 to convert caption file to support srt format. The result looks good and it would be easy to extend the support format by changing file extension and put it to pysubs2.

## Multiple subtitles support

Not working right now because I want to make sure caption attribute didn't have other problem. But it should be easy to support it by change caption attribute from string to Dict.
