### ISSUE TITLE
Drag and drop multiple files to make the input

### ISSUE THREAD

**Issue by juhonkang** [gradio-app/gradio#3081]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by freddyaboulton** [comment]
Hi @juhonkang !

You are able to do this with `gr.File(file_count="multiple")`!

You can drag and drop multiple files at once.

**Comment by tovacinni** [comment]
Is it possible to consecutively upload? Right now once I drag and drop once, it doesn't let me drag and drop again (which is a tiny bit inconvenient if I'm uploading stuff from multiple different folders)

**Comment by rkromann** [comment]
I would also like to be able to do this. It is true that you can upload multiple files at once with gr.File(file_count="multiple"), but only if they are all placed in the same folder. I would like to be able to upload multiple files placed in multiple folders, so that you have to be able to navigate the file structure while selecting the files.

**Comment by piovis2023** [comment]
Was anyone able to find a solution to this?

I've not found an answer anywhere (discord, here, LLMs)
