### ISSUE TITLE
Image is resized when using tool 'sketch'

### ISSUE THREAD

**Issue by Darius-H** [gradio-app/gradio#3093]
### Describe the bug

I have an image with shape (height=80,width=848), and I want to use the 'sketch' tool to generate mask for it.
However, whether or not I use the gr.Image().style(height = 80, width = 848) or set shape parameters gr.Image(shape=(848,80)), the image is resized automatically which is not my desire.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

without .style
```
import gradio as gr
import os


def image_mod(input_image):
    init_image = input_image["image"]
    init_mask = input_image["mask"]
    return init_mask

with gr.Blocks() as demo:
    with gr.Column():
        i_image = gr.Image(tool='sketch',shape=(848,80))# .style(height = 80, width = 848)
        o_image = gr.Image(shape=(848,80))# .style(height = 80, width = 848)
        button = gr.Button()

    button.click(image_mod,inputs=i_image,outputs=o_image)


if __name__ == "__main__":
    demo.launch()
```

### Screenshot

without .style:
![image](https://user-images.githubusercontent.com/49788663/215643949-0aad477a-bf52-4684-90d2-6e88e2df714c.png)

with .style:
![image](https://user-images.githubusercontent.com/49788663/215644820-b647bbd8-0947-4498-a744-afe0f50b44ce.png)
![image](https://user-images.githubusercontent.com/49788663/215644897-8dac32f3-e564-41b9-ba00-f44fcc040c3f.png)
The image even cover the button and other components.

### Logs

```shell
$ python sketch.py 

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
gradio version: 3.11.0
system: windows 11
python version: 3.9.7
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @Darius-H ! 

To make sure I understand, you're saying the mask should also be resized to be the `shape` passed to `gr.Image`?

**Comment by Darius-H** [comment]
> Hi @Darius-H !
> 
> To make sure I understand, you're saying the mask should also be resized to be the `shape` passed to `gr.Image`?

I mean, you can see that in the first screenshot, the first Image component (which uses tool='sketch')is longer than the Run Button and exceeds the screen. But the second Image component which doesn't use tool='sketch' show the image correctly, and the image is resized to fit it. So when i set tool='sketch', the image passed to the Image component doesn't fit.

**Comment by abidlabs** [comment]
I tested this issue and it still seems to a problem even after PR #3277. The basic problem is that when an image is uploaded, the sketch tool is selected (or the color-sketch tool), _and_ a fixed shape is provided, then the image is resized in a weird way. Let me give an example:

```py
import gradio as gr

gr.Interface(
    lambda x:(x["image"], x["mask"]),
    inputs=gr.Image(tool="sketch", shape=(100, 100)),
    outputs=["image", "image"],
).launch()
```

produces this:

<img width="961" alt="image" src="https://user-images.githubusercontent.com/1778297/220992355-09820495-bb92-4ec5-afb3-890f148f8c88.png">

As you can see, the problem is only with the input image component. The data is being processed and displayed in the output just fine.

Note that this problem does *not* happen if a `shape` is not hardcoded:

```py
import gradio as gr

gr.Interface(
    lambda x:(x["image"], x["mask"]),
    inputs=gr.Image(tool="sketch"),
    outputs=["image", "image"],
).launch()
```

or if the source is a canvas:

```py
import gradio as gr

gr.Interface(
    lambda x:x,
    inputs=gr.Image(tool="sketch", source="canvas", shape=(100, 100)),
    outputs="image",
).launch()
```

It *does* happen if the the tool is `color-sketch` instead of `sketch`:

```py
import gradio as gr

gr.Interface(
    lambda x:x,
    inputs=gr.Image(tool="color-sketch", shape=(100, 100)),
    outputs="image",
).launch()
```

and it seems that in this case, the data that is sent through is also affected:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/1778297/220993663-b9002eef-a2e2-4cef-9a7f-638282246bb5.png">
