### ISSUE TITLE
Is it possible to support draw DAG

### ISSUE THREAD

**Issue by tp-nan** [gradio-app/gradio#3121]
- [x] I have searched to see if a similar issue already exists.
yes
 

**Describe the solution you'd like**  
I have a tasks pipeline and want to show it on Gradio. 
Is it possible to support Directed acyclic graph or flow chart? one example here: [netron](https://github.com/lutzroeder/netron)

**Comment by abidlabs** [comment]
Hey! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help. Hopefully this will help address this issue.

**Comment by tp-nan** [comment]
Glad to hear that!

**Comment by abidlabs** [comment]
Will close in favor of letting users create their own DAG custom components. 

One more cool example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.
