### ISSUE TITLE
Do not serialize images into base64 format before they are sent to the frontend

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3158]
For all of the file-based components, except for the `Image` component, we no longer serialize data into base64 format. Rather, we return the path to a copy of the file. This has the advantage of being much faster, particularly for large files. If possible, we should do the same for images as that would avoid issues like #2635.

However, it might be the case that our `Image` component requires the image format to be base64 format so that users can edit the image (this used to be the case with our previous complex image editor, @pngwn do you know if this is still the case?). In which case, we could potentially provide advanced users with a parameter that lets them choose whether the image is serialized to base64 or not.

If we do this, this should happen in 4.0 as it would change the REST API format of Spaces using the Image component.

**Comment by pngwn** [comment]
This wouldn't solve #2635 because those files are causing a problem before the backend event knows about them. For images, video, and audio we need some kind of valid URL. On the frontend we always convert to a base64, so we can use that as a source for the relevant media element (which we need for both previews and editing). To change this we need to immediately send the image to the backend to create a temp file + return the filepath when they are uploaded (not when the prediction is run).

@aliabid94 Is looking at #2635 atm so he can discuss what he is looking at currently to solve that issue but essentially the solution is to just send the blob rather than converting to a string (which is the slow part on the frontend), this is only currently viable for `File`s and nothing else, we need more significant changes for other media types.

**Comment by MilkClouds** [comment]
In my opinion, simply not using base64 would not resolve https://github.com/gradio-app/gradio/issues/2635, since it is not because of base64; it is because of image encoding logic of pillow. If gradio use pillow to save image to file and upload the url of the file, same issue would occur because there exists a "save image" logic.

**Comment by pngwn** [comment]
Fixed by #6169.
