### ISSUE TITLE
Canvas drawing is cut off when the shape is explicitly set to be a square

### ISSUE THREAD

**Issue by lllyasviel** [gradio-app/gradio#3166]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

Right now if we want to make a 512\*512 drawing canvas, the only method is (1) ask users to create a pure white 512\*512 image using third-party software like PhotoShop, then (2) ask users to import that blank image into gr.Image(source='upload', tool='sketch'), then (3) use the resulting mask as the user drawing for any applications. (Besides, the initial width of scribble can not be set by code.)

This is over-complicated. We should have an one-line function to make a simple drawing canvas.

**Describe the solution you'd like**  

We may consider something like

gr.Image(source='blank', tool='sketch', size=(512, 512))

**Comment by abidlabs** [comment]
Hi @lllyasviel this is already possible by doing:

```py
gr.Image(source="canvas", shape=(512, 512))
```

For example, you can test this with this Blocks demo:

```py
import gradio as gr

with gr.Blocks() as demo:
    i = gr.Image(source="canvas", shape=(512, 512))
    o = gr.Image()
    i.change(lambda x:x, i, o)

demo.launch()
```

**Comment by lllyasviel** [comment]
@abidlabs 
No. Right now gradio does not support a simple 512\*512 drawing canvas.

    pip install --upgrade gradio
 
then 

    
![image](https://user-images.githubusercontent.com/19834515/218083430-e759b194-ed1d-41e8-a5df-d79fc1b69e2b.png)

Then the result will be like

![image](https://user-images.githubusercontent.com/19834515/218083524-119b667b-1bf0-4383-afea-ffe64bcc2411.png)

As we can see, this has nothing to do with "shape=(512, 512)", the shape parameter does not control the resolution, it controls a "gradio-style dpi". You can even draw in this long rectangular:

![image](https://user-images.githubusercontent.com/19834515/218084162-ce754d49-4962-4631-8ff3-a58e0c4452f7.png)

When it is processed, the results provide strong evidence that "shape" is related to dpi and cropping, not shape of canvas

![image](https://user-images.githubusercontent.com/19834515/218084453-eeb0aed8-3d7c-48ff-af7d-2128ee1bdde5.png)

If this is an intentional design, it may be worthwhile to reopen this issue to target a more straightforward drawing board.

**Comment by abidlabs** [comment]
Hi @lllyasviel so to achieve what you want, I think we need to do control both the image resolution (with is controlled via the `shape` parameter above) and the display size of the Image component, which is controlled via the `.style()` method of the `Image` component. I agree that it's a bit confusing, but I think this should achieve what you want:

```py
import gradio as gr

with gr.Blocks() as demo:
    i = gr.Image(source="canvas", shape=(512, 512)).style(width=512, height=512)
    o = gr.Image().style(width=512, height=512)
    i.change(lambda x:x, i, o)

demo.launch()
```

However, when I tested this, I got the canvas being cut off at the halfway point, preventing me from drawing in the bottom half of the canvas, which is very strange. 

<img width="457" alt="image" src="https://user-images.githubusercontent.com/1778297/218155557-8f766207-6bd1-4848-9344-23380dd41a51.png">


I'm going to reopen this issue so that we can fix this. cc @pngwn
