### ISSUE TITLE
Bad performance caused by get_server_url_from_ws_url

### ISSUE THREAD

**Issue by lvelvee** [gradio-app/gradio#3237]
### Describe the bug

Getting `server_url` from `ws_url` is a bad idea as ws_url is a public URL. 
It makes more sense to derive the local URL from launch settings. 

For example, if the user connects to 1.1.1.1:80 (nginx) -> 1.1.1.2:80 (gradio), 

gradio will request `http:// 1.1.1.1:80/` --> 1.1.1.2:80,
but it can also request 127.0.0.1:80 directly,
 which is preferable in this case since it is a local URL rather than a public one.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

analyze the code

### Logs

```shell
..
```

### System Info

```shell
..
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Sorry can you elaborate a little more @lvelvee on what exactly the issue is and provide some code / nginx conf to reproduce? I don't quite understand

**Comment by abidlabs** [comment]
Gonna tag my colleague @freddyaboulton -- @freddyaboulton I think you're more familiar with this part of the codebase. Do you understand the issue and agree with this suggestion?

**Comment by freddyaboulton** [comment]
Yes I think I understand what @lvelvee is referring to!

We added that piece of logic because in the case when gradio is mounted as a subapplication, we don't know the path of the gradio app ahead of time. So we need to find a way to determine the path to the gradio app in that case.

I want to mention that the line In the case that gradio is not mounted as a subapplication, that piece of code `get_server_url_from_ws_url` does not run, as the server url for the queue is set during `launch`

https://github.com/gradio-app/gradio/blob/main/gradio/blocks.py#L1413

**Comment by freddyaboulton** [comment]
Ok, we can just use the `root_path` I think: https://fastapi.tiangolo.com/advanced/behind-a-proxy/#checking-the-current-root_path

**Comment by abidlabs** [comment]
This got fixed somewhere along the way, thanks @lvelvee for creating the issue!
