### ISSUE TITLE
Add chinese Readme and document

### ISSUE THREAD

**Issue by uanu2002** [gradio-app/gradio#3377]
- [ ✔️] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Gradio is a good tool, but it takes a lot of time for a lot of people around me to Gradio because they don't have any documentation for it in Chinese, which compromises the Gradio experience.

**Describe the solution you'd like**  
I want to add a Chinese Readme.md and add the usage document of Chinese later.

**Additional context**  
No more.

**Comment by wangtu2022** [comment]
That's a good suggestion. Hope to add Chinese version.

**Comment by abidlabs** [comment]
Hi @uanu2002 @wangtu2022 we'd love to support this, but we don't have the expertise on our team to translate the README into Chinese. Would either of you be interested in contributing the Chinese version as a PR?

We can certain link to it

**Comment by uanu2002** [comment]
> Hi @uanu2002 @wangtu2022 we'd love to support this, but we don't have the expertise on our team to translate the README into Chinese. Would either of you be interested in contributing the Chinese version as a PR?
> 
> We can certain link to it

Hello @abidlabs I am very glad to receive your approval, and I am happy to take on this task to contribute to the promotion of gradio.

**Comment by abidlabs** [comment]
Awesome, thanks @uanu2002! There are two files that would need to be translated:

* `readme_template.md`: https://github.com/gradio-app/gradio/blob/main/readme_template.md
* `quickstart`: https://github.com/gradio-app/gradio/blob/main/guides/01_getting-started/01_quickstart.md

If you can open a PR just with the translations of these files, we can work on organizing them so that they are linked to from the readme correctly. cc @aliabd
