### ISSUE TITLE
Add option to disable `Clear All` button in Dropdown or add a min_choices parameter

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3435]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
All dropdowns now come with an `x` button that allows the user to clear all selected choices.

As discussed in this [discord thread](https://discord.com/channels/879548962464493619/1083290221828907108/1083290221828907108), this button can cause problems if you have a `change` event on `Dropdown` and you don't expect the value of the drop down to be empty.

**Describe the solution you'd like**  
Three possible solutions I can think of:
1. Add `clear_all=bool` to `style` method to disable the clear_all button
2. Add `min_choices` parameter. `Change` event won't fire unless this is met. Kinda clunky now that I think about it lol.
3. Do nothing. It's up for the app author to guard against this case.

I'm between 1 and 3. Curious on everyone's thoughts.

**Additional context**

**Comment by abidlabs** [comment]
I think this is a broader limitation right now of Gradio components -- that we don't have any way to indicate *required* inputs (issue: #2718). I think we should design a general solution around validation / indicating that some inputs are required (and preventing predictions from going through if those fields are empty) rather than specifically handling this for Dropdown component.

**Comment by msampson3d** [comment]
Agree that an easy to use validation framework would be great, which allowed users to flag components as required and do a validation on a specific trigger (button click etc)

**Comment by msampson3d** [comment]
One additional improvement on Dropdown: if the dropdown isn't multiselect, the dropdown should close when you click an entry. Right now you have to click out of it.

**Comment by msampson3d** [comment]
I'm an advocate for option 1, personally

**Comment by g-wellsa** [comment]
for example  The dropdown how to set default option

**Comment by g-wellsa** [comment]
your project is so bad

**Comment by msampson3d** [comment]
> for example The dropdown how to set default option

Its right in the docs... https://gradio.app/docs/#dropdown  Set the 'value' attribute.

**Comment by abidlabs** [comment]
But until we have a proper validation framework for all components, I think (1) is a pretty reasonable addition to the API.

**Comment by pngwn** [comment]
The issue here is that the Dropdown doesn't match standard dropdown semantics, not arguing against the need for validation but I don't think that is the issue here. I don't think this needs an option either, just better defaults. The single dropdown shouldn't have a clear button and if there is no `None` option and a `value` (initial) is passed then it won't be possible to submit `None`.
