### ISSUE TITLE
customized error message not work

### ISSUE THREAD

**Issue by faye1225** [gradio-app/gradio#3478]
### Describe the bug

I think gradio should support custom error pop-ups
Just like this
```
import gradio as gr

def test():
    raise gr.exceptions.Error('some error')

with gr.Blocks() as demo:
    a = gr.Button()
    a.click(test)
demo.launch()

```
After clicking there should be a pop-up message on the page like this . but not.

![image](https://user-images.githubusercontent.com/56664035/225597126-ebc5c787-3520-43f3-aa89-600ec2739aab.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

def test():
    raise gr.exceptions.Error('some error')

with gr.Blocks() as demo:
    a = gr.Button()
    a.click(test)
demo.launch()

### Logs

```shell
raise gr.exceptions.Error('some error')
gradio.exceptions.Error: 'some error'
```

### System Info

```shell
gradio==3.16.2
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @faye1225 the reason you don't see a custom error message is because there needs to be an output component for the Error message to show up. For example, if you change the code to:

```py
import gradio as gr

def test():
    raise gr.exceptions.Error('some error')
    return "hi"

with gr.Blocks() as demo:
    a = gr.Button()
    b = gr.Textbox()
    a.click(test, None, b)
demo.launch()
```

Then, the error message appears as expected (at least on the latest version of Gradio, gradio==3.21.0). 

I do agree that we should support Errors even if no output component is specified but there is already an issue that covers this (#3347) so I'll go ahead and close this

**Comment by zhaobu** [comment]
> 

if a component set visible=False before, and I want to set visible=True in the click function,  then raise gr.Error not work
