### ISSUE TITLE
Document `cancels` parameter more clearly

### ISSUE THREAD

**Issue by SoulflareRC** [gradio-app/gradio#3518]
### Describe the bug

Basically i have a button that has a click event calling a function which has a loop that calls a command line tool. I was trying to add a button for canceling that event, but that button only cleared the progress bar shown on the interface, while the function was still running in the backend. 
![image](https://user-images.githubusercontent.com/107384280/226187361-7a43028b-6c66-427c-ac25-45e71097e454.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Let a button cancel another button's click event. 

### Screenshot

Before 
![image](https://user-images.githubusercontent.com/107384280/226187685-54528647-ba0f-4714-a641-92d8e3326368.png)
After (backend still running the function)
![image](https://user-images.githubusercontent.com/107384280/226187704-3ca03516-fa85-40aa-ad6f-811e2b2d1fce.png)

### Logs

```shell
None
```

### System Info

```shell
Gradio version: 3.20.1
OS: Windows 11
Browser: Chrome
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @SoulflareRC this is actually the expected behavior.  The `cancels` parameter actually can only cancel functions that have not yet run (or generators that are iterating), but functions that are currently running will be allowed to finish.

I agree that this should be documented better, so I'll change the issue to be around documenting this
