### ISSUE TITLE
I want server_url 0.0.0.0 and local_url 127.0.0.1 using Jupyter

### ISSUE THREAD

**Issue by o-alexandre-felipe** [gradio-app/gradio#3602]
- [x] I have searched to see if a similar issue already exists.

I am running gradio inside a docker container, using port redirection, and I want to inline in a notebook , that requires HTTPS when connecting to `localhost`. The alternative is to connect locally to 127.0.0.1. Currently my only alternative (without worrying about a certificate, e.g. if I share this) is to use pass `share=True`, a solution that I don't understand well, but I imagine it has to send the data to a remote server and download it again.

**Comment by o-alexandre-felipe** [comment]
No, because if I pass `server_name='127.0.0.1'` the server running inside docker won't bind to the host port. If I pass `server_name='localhost'` the browser requires `https`, If I pass `0.0.0.0` it will replace that by a `localhost`

**Comment by abidlabs** [comment]
Hmm would you please be able to provide a step-by-step explanation including your Python code and your docker commands so that we can try to reproduce this issue?

**Comment by abidlabs** [comment]
Closing for lack of followup

**Comment by colinlaney** [comment]
Let me explain what the problem was here.

If a Gradio app runs on Jupyter Lab inside a Docker container that is located on a remote host, then there are only two solutions to access the app from within the Jupyter notebook:

1. to break the network isolation of the Docker container with `docker run --network host ...`
2. to forward the port of the Gradio app with `ssh -NL 7860:localhost:7860 <remote>` from the remote host to the localhost through [SSH tunnel](https://github.com/gradio-app/gradio/issues/700#issuecomment-1445216680) when Docker exposes exactly the same port: `docker run -p 7860:7860 ...`

The 1st item is insecure, the 2nd item is some kind of overhead.

It would be great to render the Gradio app right in Jupyter Lab notebook that is running inside Docker container remotely like below, but without any port forwarding:

<img width="980" height="1129" alt="Image" src="https://github.com/user-attachments/assets/66025f19-5a70-4ac2-ae5f-3dc647f8a521" />

<img width="980" height="1129" alt="Image" src="https://github.com/user-attachments/assets/232c8d35-c2a7-40ff-a066-61dd0976dcd5" />

---
The trap is in the lack of Docker environment indication and in the substitution of `localhost` instead of `0.0.0.0` in 13edcfc4b429ac9ef74eb470448f56e5feeeaf68 or somewhere in the previous commits.
