### ISSUE TITLE
Ability to preload `gr.Dropdown` elements on page and never unload them

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3621]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Back when `gr.Dropdown` used a `<select>` it was possible to programmatically get the list of elements in the dropdown, etc. Now it seems like the new dropdown does not keep its elements on the page when closed, making it impossible to do this

Two cases I know of where the `<select>` behavior was used:
1. Clicking a button that copies one dropdown's value to another dropdown's, where both dropdowns had the same list of elements, but they lived in separate blocks contexts (so creating a simple event handler doesn't work)
2. Watching for changes to the dropdown's selected element exclusively in the frontend

**Describe the solution you'd like**  
An option to pass to `gr.Dropdown`, `keep_loaded` or similar that preloads the `ul`/`li` elements on the page and keeps them there when the dropdown is closed

**Additional context**

**Comment by space-nuko** [comment]
But I think keeping the list elements off the page helps with initial page load, since it's not sent over the network, best to let users decide what the best tradeoff is

**Comment by pngwn** [comment]
When you say programmatically, do you mean in javascript?

**Comment by pngwn** [comment]
The reason I ask is because when we make some architectural changes, there will be no guarantees that things are on the page at all, the only reason we generally do it now in some cases, is because we don't serialise internal component state. Additionally, this is an implementation detail and shouldn't be depended upon. Could we figure out some other way to do this?

**Comment by dawoodkhan82** [comment]
@space-nuko would using `gr.State()` to keep track of the dropdown elements work in your case?

**Comment by space-nuko** [comment]
It might but I'm not in control of the webui extension I want to select things from, I'd have to ask them to change it with every dropdown they add

Plus `gr.State` is backend only, where the frontend needs to know the element list

**Comment by abidlabs** [comment]
Agreed, it's too cumbersome to store the dropdown values in a `gr.State`. @dawoodkhan82 I think it's a better DX if we make the dropdown choices hidden or visible instead of loaded / unloaded. Same issue was also brought up by @CurtisDS here: https://github.com/gradio-app/gradio/discussions/3875

**Comment by CurtisDS** [comment]
I have implemented my own select drop downs on top of native select elements before when developing a front end UI. Basically what I did was use a hidden native select box that gets updated when the user interacts with the custom implementation. It's not shown to the user but is used to drive the custom implementation. When the user selects an item the select value is changed and an event is dispatched. When the select has a change event triggered (AKA someone programmatically changed the value) and the value is actually different (to avoid an infinite loop of ping ponging events) the value is mirrored back to the custom drop down.

I don't know if this is the best solution... I never did an analysis for efficiency of this approach.... but it functionally worked. Allowing the user to have a nice modern select drop down and still allow anyone to tap into the select control using JavaScript.

If you were to not do that and keep it as it is but change the list to be hidden instead of unloaded the only way I can see to implement the same functionality would be to run javascript on page load to scan the list and add click handlers to every item to tell if the user chose a new value. Then to programmatically change the value we would have to trigger a click event on the hidden list item which would in theory trigger gradio to update the internal value. It would be doable for our needs, but could become cumbersome in some more complex use cases, like if the drop down is a multi-select... you would basically have to also keep an internal list and your own state of each select. You would also have to have a constant timeout running every second to check if the value or list items were changed by another process.

**Comment by dawoodkhan82** [comment]
@space-nuko we won't have a fix for this issue right away. We plan to solve for this use case by eventually re-implementing the dropdown using `select`.  Also we will soon allow custom components, where the current dropdown component can be forked and customized.

**Comment by abidlabs** [comment]
I think we can close this issue as "wont-fix" given above^
