### ISSUE TITLE
Allow configuring development backend URL

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3656]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
So I just spent 4 hours trying to figure out how to get development hot reloading working, it turns out the demo I used didn't use the standard port of 7860 so the frontend Vite server couldn't load anything. The reason I don't use 7860 in my demo is because usually I have a webui instance open and it occupies port 7860

I could change the webui to use a port besides 7860, but I noticed the URL for dev mode is hardcoded, perhaps it could be made configurable instead

**Describe the solution you'd like**  
Ability to change backend URL/port for dev mode

**Additional context**
https://github.com/gradio-app/gradio/blob/ceb5853480ae23eef4f4ec1e5a481b00764fea2c/js/app/src/Index.svelte#L196-L199

**Comment by space-nuko** [comment]
What implications does it have outside of dev mode specifically? I thought it would be nice to have the port configurable if it's desired

**Comment by pngwn** [comment]
Why do you need to run multiple apps at once? You can only develop one at a time.

I'm strongly against configurable dev modes as a rule because everything becomes hard to reason about for _very_ little benefit and dev tooling can be complex enough as it is. So unless there is an overwhelming need for this I'd rather we didn't add it. I think there is a better solution to this.

I don't find the argument that some other piece of software is running at the same time compelling, just close it for a bit? If there is a valid usecase for running multiple gradio instances simultaneously that can't be solved by other means then I'd love to hear it.

**Comment by space-nuko** [comment]
It's merely a net positive convenience for me, with recent changes the webui can take several minutes to start up so it's just somewhat annoying to have to shut it down if I need to quickly test this one issue with Gradio

Plus, if I can reproduce a gradio issue in webui, it's nice to be able to have both apps open to compare the behavior in each

**Comment by abannura** [comment]
I'm currently with a Gradio server running inside a Docker container.

Docker containers don't work well with servers running on localhost inside of them, due to how port publishing is handled by Docker (TLDR: servers need to run on 0.0.0.0 in order to accept requesting coming from the host machine). In fact, @abidlabs mentioned this [here](https://github.com/gradio-app/gradio/issues/24#issuecomment-658129710).

Therefore, right now is not possible to run Gradio with hot reloading inside a Docker container. This seems to me a good-enough reason to allow configuration of the backend server address, when using hot reloading.

If you have another solution happy to hear it.

Note: I want to avoid using the option `--network="host"` (which forces that the container and the machine share the same network stack).

**Comment by operand** [comment]
I ran into this limitation with running dev mode within a container as well. I would also like to see this made configurable.

For now I came up with the following workaround. This works within a `python:3.9` Docker container.
```bash
apt-get update && apt-get install -y socat
socat TCP-LISTEN:7861,fork,reuseaddr TCP:127.0.0.1:7860 &
gradio demo.py
```
This will listen on another port (eg. `7861`) and forward to the hardcoded one.

**Comment by freddyaboulton** [comment]
This issue has gotten stale so will close. That being said, I wouldn't be opposed if someone wanted to open a PR to configure this via an environment variable. But we see this as a low priority improvement.
