### ISSUE TITLE
Front-end crashes if returning None from a callable in Gallery's init

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3737]
### Describe the bug

The front-end crashes when running the following code

```python
import gradio as gr

x = None
with gr.Blocks() as demo:
  with gr.Tab("tab1"):
    gr.Button("a button")
  with gr.Tab("tab2"):
    gr.Gallery(label="Output", value=lambda: x).style(preview=True)

demo.launch()
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Above^

### Screenshot

![image](https://user-images.githubusercontent.com/41651716/229411119-cf1839f9-6312-4203-b08a-31985726c89c.png)

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

annoying

**Comment by abidlabs** [comment]
Very strange bug. Was trying it out and it seems like `.style(preview=True)` is required for the error to happen. For example, this works fine:

```py
import gradio as gr

x = None
with gr.Blocks() as demo:
  with gr.Tab("tab1"):
    gr.Button("a button")
  with gr.Tab("tab2"):
    gr.Gallery(label="Output", value=lambda: None)

demo.launch()
```

I'm going to remove this from the 3.x milestone because while this is a bug that we should fix, it's relatively niche and we don't need to do it before 4.0 works.

**Comment by abidlabs** [comment]
Actually I'm pretty sure that this is the same issue as #3944. Let me close this altogether
