### ISSUE TITLE
Let Python client be able to duplicate a Space easily and make it private

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#3804]
Public Spaces will be rate limited, which means that if someone connects a Space using the Gradio client and starts making requests, they'll quickly hit the limit, something like this:

```py
from gradio_client import Client

client = Client("abidlabs/en2fr")
client.predict("hello")
> bonjour
client.predict("hello")
> bonjour
...
client.predict("hello")
> Error: 429 Rate limit. Please duplicate the Space and make it private to avoid being rate limited.
```

However, this requires users to manually duplicate the Space, which is quite cumbersome and harder to use than other APIs-as-a-service. What if we had a "private mode" for the Client. If you do:

```py
from gradio_client import Client

client = Client("abidlabs/en2fr", hf_token="...", private=True)
> Creating a private version of this Space for your own use 🤗 
> Created "aliabid94/en2fr", running on T4 GPU with a sleep timeout of 1 hour (after 1 hour of inactivity, the Space will go to sleep). 
> Ready to make predictions! 

client.predict("hello")
> bonjour
client.predict("hello")
> bonjour
client.predict("hello")
> bonjour

# no timeout!
```

cc @aliabid94 @freddyaboulton @osanseviero @julien-c @Wauplin

**Comment by freddyaboulton** [comment]
My thought is that running `Client("abidlabs/en2fr", hf_token="...", private=True)` should be idempotent so that a developer's app doesn't drastically change without their knowledge. But does that mean we should give them a mechanism to updating the private version of their space?

What if we keep the duplication logic in a class method that gives users more control of what version of the upstream space/hardware is used?

```python
client = Client.duplicate_from("abidlabs/en2fr", hf_token=..., private=...) # always fetch latest
client = Client.duplicate_from("abidlabs/en2fr", commit=..., hardware=....) # pin to a commit
```

**Comment by abidlabs** [comment]
Makes sense to me! I'll put together a PR

**Comment by Wauplin** [comment]
> What if we keep the duplication logic in a class method that gives users more control of what version of the upstream space/hardware is used?

I also like the idea. Just a nit but I would align some parameter if that's fine with you:

```py
# hf_token => token ?
# commit => revision (=> can be a branch name, a tag,...)

client = Client.duplicate_from("abidlabs/en2fr", token=..., private=..., revision=..., hardware=..., secrets=...)
```

It would also be useful to be able to set secrets for the space. For now it's not possible to retrieve which secrets are required when you duplicate a space via the API so it would be at user's discretion to know that. 

---

Since adding hardware to a Space can be very costly, I wonder what would be the best way to ensure users don't feel cheated if a Space is not in use anymore. A possibility could be to use the auto-sleep feature but I'm not sure how well it was working + it's not accessible via script. Another possibility is to request a free cpu once the python exit (using `atexit` for example?). But even like this it's possible that it's not called if the script is shut down abrutely.

Any thoughts on how we can handle this?

**Comment by abidlabs** [comment]
> I also like the idea. Just a nit but I would align some parameter if that's fine with you:

Totally

> commit => revision

Will make the change. Is it possible to use the revision with `duplicate_space`? I don't see it as a parameter here: https://huggingface.co/docs/huggingface_hub/v0.13.4/en/package_reference/hf_api#huggingface_hub.HfApi.duplicate_space

> # hf_token => token

For this, I'd prefer to keep `hf_token`. I know that's not consistent with usage in other HF libraries, but it's consistent with usage in other parts of the gradio library, such as `gradio.themes.push_to_hub`

> It would also be useful to be able to set secrets for the space

Makes sense. Will add using `add_space_secret`:  https://huggingface.co/docs/huggingface_hub/v0.13.4/en/package_reference/hf_api#huggingface_hub.HfApi.add_space_secret

**Comment by abidlabs** [comment]
> Since adding hardware to a Space can be very costly, I wonder what would be the best way to ensure users don't feel cheated if a Space is not in use anymore. A possibility could be to use the auto-sleep feature but I'm not sure how well it was working + it's not accessible via script. Another possibility is to request a free cpu once the python exit (using atexit for example?). But even like this it's possible that it's not called if the script is shut down abrutely.

For this, I was thinking we can set a sleep timeout of 1 hour. So worst case scenario, people are charged for one hour of CPU usage. Is it possible to do this with the `huggingface_hub` library?

**Comment by Wauplin** [comment]
>  Is it possible to use the revision with duplicate_space? 

Actually no, it's not possible. Maybe not worth investing time to add it since it's maybe more a corner case.

> For this, I'd prefer to keep hf_token. 

Yep, fine :+1: 

> Will add using `add_space_secret`

Definitely the way to go yes!

> I was thinking we can set a sleep timeout of 1 hour.
> Is it possible to do this with the huggingface_hub library?

Unfortunately not at the moment no. But the endpoint already exists server-side (see [API route](https://github.com/huggingface/moon-landing/blob/a461ec4007cf96db2f2764d767c308e984c5ff56/server/server.ts#L675) and [implementation](https://github.com/huggingface/moon-landing/blob/main/server/app/spacesHandlers.ts#L445) -private link).
I can work on adding this to `huggingface_hub`. Next release `0.14` should come _soon_ (most probably next week?).

**Comment by abidlabs** [comment]
> Unfortunately not at the moment no. But the endpoint already exists server-side (see [API route](https://github.com/huggingface/moon-landing/blob/a461ec4007cf96db2f2764d767c308e984c5ff56/server/server.ts#L675) and [implementation](https://github.com/huggingface/moon-landing/blob/main/server/app/spacesHandlers.ts#L445) -private link). I can work on adding this to huggingface_hub. Next release 0.14 should come soon (probably next week?).

Sweet, that'd be awesome. If you're open to doing an alpha release, maybe we can incorporate it even earlier.

**Comment by Wauplin** [comment]
I'll let you know :)

**Comment by abidlabs** [comment]
Added a more visible warning @osanseviero:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/1778297/231539219-c0d33258-c640-453d-bc2b-05fe4c3a8b3a.png">

**Comment by osanseviero** [comment]
What happens if the user has no billing info?

**Comment by Wauplin** [comment]
Good question @osanseviero :+1: 

I just tested it with a dumb account (no billing info) and the server returns a HTTP 403 Forbidden with an explicit message:
```
Traceback (most recent call last):
  File "/home/wauplin/projects/huggingface_hub/cccc.py", line 5, in <module>
    request_space_hardware(repo_id, hardware="cpu-upgrade")
  File "/home/wauplin/projects/huggingface_hub/src/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/wauplin/projects/huggingface_hub/src/huggingface_hub/hf_api.py", line 4006, in request_space_hardware
    hf_raise_for_status(r)
  File "/home/wauplin/projects/huggingface_hub/src/huggingface_hub/utils/_errors.py", line 301, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/spaces/huggingface-hub-ci/tmptest/hardware (Request ID: Root=1-6437da80-55d843e1547ce2af646ead33)

You must add a payment method to your account to upgrade your space's hardware. Visit your billing settings to add one: https://huggingface.co/settings/billing
```

**Comment by abidlabs** [comment]
Yup that's right thanks @Wauplin!

**Comment by osanseviero** [comment]
Thanks a lot!
