### ISSUE TITLE
Vertical orientation for `gr.Slider`

### ISSUE THREAD

**Issue by Xynonners** [gradio-app/gradio#3834]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

I have some UI design that vertical sliders would fit better than horizontal ones, and was hoping it could be a thing in gradio.

**Comment by abidlabs** [comment]
Closing for lack of followup

**Comment by drscotthawley** [comment]
@abidlabs  I just asked the same question on HF Discord: [1104129830750011464](https://discord.com/channels/879548962464493619/1104129830750011464)

We mean sliders with a vertical orientation rather than a horizontal one, so that the user slides the marker up and down instead of left to right.

**Comment by abidlabs** [comment]
Got it @drscotthawley! Not possible right now, but we can open it up as a feature request

**Comment by drscotthawley** [comment]
@abidlabs Cool!  Looks like it might be a super-simple, almost automatic change!: 

https://stackoverflow.com/questions/15935837/how-to-display-a-range-input-slider-vertically

> First, set height greater than width. In theory, this is all you should need. The [HTML5 Spec suggests as much](http://www.w3.org/TR/html5/forms.html#range-state-(type=range)):
> 
> ... the UA determined the orientation of the control from the ratio of the style-sheet-specified height and width properties.

**Comment by drscotthawley** [comment]
Hey @abidlabs  one little hack I found: it *is* currently possible in existing Gradio via CSS if the user is willing to rotate the *entire* element, text included.  But this is probably not what most people will want LOL: 

Sample Colab: https://colab.research.google.com/drive/1zHOv8xguHo4mlw0gt0iZVORfaZdGz6vE?usp=sharing 

<img width="1163" alt="Screen Shot 2023-05-05 at 4 07 47 PM" src="https://user-images.githubusercontent.com/13925685/236569129-f8208b3b-a76b-4819-983c-3d211aa1002d.png">

**Comment by abidlabs** [comment]
Hey! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help. Hopefully this will help address this issue.

**Comment by abidlabs** [comment]
I'll go ahead and close this issue since we are not planning to include this in the core Gradio library. But happy to help if you are interested in making this a custom Gradio component (feel free to ask questions in this issue).
