### ISSUE TITLE
Audio files inflate in size after loading in Gradio

### ISSUE THREAD

**Issue by sanchit-gandhi** [gradio-app/gradio#3842]
### Describe the bug

Given an audio file `audio.mp3`, when we check the size of the file on the system, we get a file size of 2.9MB. Loading the same audio file through Gradio and checking the file size, we get a file size of 84.7MB (29x increase).

This Space demonstrates with a test file `audio.mp3` (see cached examples): https://huggingface.co/spaces/sanchit-gandhi/gradio-audio-file-test

In both cases, we're computing the file size in the same way: https://huggingface.co/spaces/sanchit-gandhi/gradio-audio-file-test/blob/870f302c249f1d685648341d79f3561a1e53a71a/app.py#L7

Should there be a 29x inflation in file size after loading? This seems extreme no?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Refer to https://huggingface.co/spaces/sanchit-gandhi/gradio-audio-file-test

### Screenshot

![Screenshot 2023-04-13 at 15 37 39](https://user-images.githubusercontent.com/93869735/231794469-8362d4a6-c01f-4e67-aaf8-9bfecb826e13.png)

### Logs

```shell
N/A
```

### System Info

```shell
See https://huggingface.co/spaces/sanchit-gandhi/gradio-audio-file-test/blob/main/README.md
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
I think the problem is that gradio will convert all audio files to wav, which will increase the size as wav are lossless:

Very simple repro of the issue:

![image](https://github.com/gradio-app/gradio/assets/41651716/889440f2-207c-43b2-a472-c1309a36d23e)

One thing we can do is add a `file_format` parameter to the Audio class to control the format that the base64 data gets converted to.

In the case of the audio file in this example, that will still increase the file size but by 2x as opposed to 30x

![image](https://github.com/gradio-app/gradio/assets/41651716/7f434dee-2870-4cc3-b2ac-acaf5e636b0e)

However, when I tried the same approach with other mp3 files, the new files would be the same size or smaller

Case 1:
![image](https://github.com/gradio-app/gradio/assets/41651716/dbc06ed9-7406-48ed-b2b2-ad08b9d21e42)

Case 2:
![image](https://github.com/gradio-app/gradio/assets/41651716/6f2e004b-8514-46fd-bc53-1d4c5f7d4608)

@sanchit-gandhi Do you have other large mp3 files on hand we can test with?

**Comment by abidlabs** [comment]
> One thing we can do is add a file_format parameter to the Audio class to control the format that the base64 data gets converted to.

SGTM. We have a similar `format` parameter in the `Video` component. Maybe let's use `format` here too for consistency?
