### ISSUE TITLE
setting css not effective

### ISSUE THREAD

**Issue by 17818587795** [gradio-app/gradio#3851]
### Describe the bug

Unable to add background color to Button

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks(css="#warning {background-color: red}  .feedback {font-size: 24px}") as demo:
    box1 = gr.Textbox(value="Good Job", elem_classes="feedback")
    box2 = gr.Button(value="Failure", elem_id="warning", elem_classes="feedback")

if __name__ == "__main__":
    demo.launch(debug=True)
```

### Logs

```shell
no logs
```

### System Info

```shell
3.23.0
```

### Severity

annoying

**Comment by gtm-nayan** [comment]
There are two problems here,
1. There is a background-image property, that's drawn over the background-color. So, even if your style for background is actually applying to the element, it's going to covered by the gradient that's set as the background-image.

2. Your font-size from feedback won't apply to the element, because `.lg.svelte-xyz` will have more specificity than just `.feedback`.

The workarounds specific to this example would be to set background-image to none in your css and repeat the feedback class to be `.feedback.feedback`, but I doubt the workarounds will be of much use in general.

**Comment by abidlabs** [comment]
Hi @17818587795 for the custom css, you have to look at the inspector console to figure out how to target your elements correctly. And, if you use custom classes, you may have to use "!important" for specificity as @gtm-nayan points out. If you do go down this route, you can achieve what you want like this:

```py
import gradio as gr

css = """
#warning {background: red;} 

.feedback {font-size: 24px !important;}
.feedback textarea {font-size: 24px !important;}
"""

with gr.Blocks(css=css) as demo:
    box1 = gr.Textbox(value="Good Job", elem_classes="feedback")
    box2 = gr.Button(value="Failure", elem_id="warning", elem_classes="feedback")
    
demo.launch()
```

which produces this:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/1778297/232513804-5cadd217-91ae-4bce-bf0a-7f1f02363f3b.png">

However, custom css isn't a recommended approach in Gradio and it may not work consistently across Gradio versions. What we recommend instead is to use themes: https://gradio.app/theming-guide/
