### ISSUE TITLE
Process video intput frame by frame

### ISSUE THREAD

**Issue by harryliou** [gradio-app/gradio#4002]
Image with cam source can set streaming flag, process by frames and output as Image
Is it possible to do like that with video input?

**Comment by abidlabs** [comment]
Hi @harryliou it's not clear to me what this issue is asking. For general questions like this (that are not feature requests or bug reports), we would prefer if you could please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB) with more detail than what is provided here. (I'll close this issue)

**Comment by futureflsl** [comment]
> Image with cam source can set streaming flag, process by frames and output as Image Is it possible to do like that with video input?

I have the same question,But I think gradio may not do this now.
