### ISSUE TITLE
When localhost is not accessible

### ISSUE THREAD

**Issue by WALL-E** [gradio-app/gradio#4046]
Checking if localhost can be accessed is just to verify the program running on Colab. But this error is also triggered when http_proxy or https_proxy is set, but no_proxy="localhost, 127.0.0.1, ::1" is not set.

https://github.com/gradio-app/gradio/blob/531f11d642391164ed17fe74ea20824424ea2382/gradio/blocks.py#L1759-L1764

https://github.com/gradio-app/gradio/blob/531f11d642391164ed17fe74ea20824424ea2382/gradio/networking.py#L181-L189

**Comment by abidlabs** [comment]
Hi @WALL-E, I'm not sure I understand the issue: what do you mean by: 

> But this error is also triggered when http_proxy or https_proxy is set, but no_proxy="localhost, 127.0.0.1, ::1" is not set.

**Comment by WALL-E** [comment]
localhost is not accessible When three conditions are satisfied simultaneously:

1. set http_proxy or https_proxy
2. no set no_porxy
3. server_name is default value localhost or 0.0.0.0

At this point, I am not using Colab, a shareable link is not the best way to access.  Therefore, users should not be guided to set share=true. More reasonable error message:

"When localhost is not accessible, a shareable link must be created. Please set share=True or set the environment variable no_proxy"

**Comment by Accurio** [comment]
There are three ways to configure the proxy servers and the proxy exceptions on Windows:

1. Registry: configured through Settings or Internet Options.
2. Environment Variables: `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`, etc.
3. kwarg `proxies` in Requests and HTTPX.

HTTPX currently does not support the proxy exceptions in Registry (See [encode/httpx#1513](https://github.com/encode/httpx/discussions/1513)). This is because `urllib.request.getproxies()` returns both the proxy servers and the proxy exceptions if environment variables are set, but only the proxy servers in Registry without the proxy exceptions if environment variables are not set.

When a Windows user configures the proxy servers and the proxy exceptions only through Settings, HTTPX will get only the proxy servers and not the proxy exceptions, and the request to localhost will be sent to the proxy server. If the proxy server is not on the proxy client, the Gradio website on localhost cannot be reached and the error will be thrown.

For Windows users, they can configure environment variables manually using following code:

```Python
import os
from urllib.request import getproxies

proxies = getproxies()
os.environ["HTTP_PROXY"]  = os.environ["http_proxy"]  = proxies["http"]
os.environ["HTTPS_PROXY"] = os.environ["https_proxy"] = proxies["https"]
os.environ["NO_PROXY"]    = os.environ["no_proxy"]    = "localhost, 127.0.0.1/8, ::1"
```

I think the error message needs to prompt Windows users to configure the proxy servers and the proxy exceptions in environment variables if they use proxy.

**Comment by CharlesAttend** [comment]
Thank you for your issue, I was exactly in this case ! `no_proxy` was not set by on my server.
