### ISSUE TITLE
gr.Examples Enable for each example to have a label and a value

### ISSUE THREAD

**Issue by t-marinos** [gradio-app/gradio#4268]
- [yes ] I have searched to see if a similar issue already exists.

For example I would like the gr.Examples to display the example as "Person 1" and when it is clicked, to populate the linked component with "John Doe".

**Comment by abidlabs** [comment]
The way I'm thinking to implement this is to add a `labels` parameter to `gr.Examples()` (and an `examples_labels` parameter to `gr.Interface()`) which is a list of the same length as `examples`. If provided, these text labels appear instead of the original examples, but clicking on the labels populates the inputs in the same way as before.

**Comment by tlabarta** [comment]
@abidlabs Is there any update on this? I could need exactly this enhancement for a use case where we have long text examples that we could just abbreviate by a short label.
