### ISSUE TITLE
Unable to connect from notebook

### ISSUE THREAD

**Issue by Jeffwan** [gradio-app/gradio#4272]
### Describe the bug

I am using gradio in a remote jupyter notebook and I notice this is not working. 

It actually listen to `http://127.0.0.1:7860/` but actually the client side is expecting my localhost has 7860 listening.

It's hard for us to use `share=True` because of security concerns, Is there a way to run gradio like an embedded UI in the jupyter notebook?  The major ask is something it's hard for us to request a port. However, jupyter is a managed service and if we can leverage it to serve the gradio UI, that would be perfect

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just run the code

```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")

demo.launch()   
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/4739316/a98146be-96be-4f31-8ea2-e295859f19f7)

### Logs

```shell
no logs available
```

### System Info

```shell
python3 -V
Python 3.10.10

pip list | grep gradio
gradio                   3.31.0
gradio_client            0.2.5
```
```


### Severity

serious, but I can work around it

**Comment by kenghzou95** [comment]
facing same issue with python 3.10

**Comment by abidlabs** [comment]
Hi @Jeffwan @kenghzou95 in order to run Gradio on a remote jupyter notebook, you will need to use SSH forwarding to forward the port that Gradio is running to a port on to your local machine (by default, Gradio starts running on 7860, then 7861, etc.) and then open that local port in your browser, and Gradio should show up. 

You can see more in this discussion here: https://github.com/gradio-app/gradio/issues/700#issuecomment-1445216680

**Comment by kenghzou95** [comment]
okay thanks
