### ISSUE TITLE
Allow attaching arbitrary JS-readable data to components

### ISSUE THREAD

**Issue by akx** [gradio-app/gradio#4300]
- [ ] I have searched to see if a similar issue already exists.

# Is your feature request related to a problem? Please describe.

As something of an alternate approach to #4278, it would be useful to be able to specify arbitrary (string) data that could be accessed in JavaScript code, so custom frontend JavaScript could then do whatever it needs to, e.g. render tooltips.

# Describe the solution you'd like

The obvious HTML API for this is [`data-*`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*), which yields [`dataset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) in the JS DOM.
With this in mind, the Python API could also be `dataset`:

```python
gr.Number(..., dataset={"spam": "eggs"})
```
and the resulting `component` DIV would then be
```html
<div id="component-1" class="..." ... dataset-spam="eggs">...
```

For the particular case of #4278, this'd mean

```python
gr.Number(..., dataset={"tooltip": "Too high spam counts may make the UI unresponsive."})
```
and something like
```javascript
document.querySelectorAll("*[data-tooltip]").forEach(e => e.title = e.dataset.tooltip);
```
to configure tooltips.

# Additional context

h/t to @automatic1111 for the idea.

**Comment by AUTOMATIC1111** [comment]
We figured out that we can put things into config ourselves and access them from javascript directly.

**Comment by akx** [comment]
Yeah, it wouldn't have to be in the markup, but the gradio initialization code could also just set the attributes from `gradio_config` into each element's dataset.

**Comment by pngwn** [comment]
We don't currently version the config, so that approach isn't always guaranteed to work. Although I'd quite like us to version the config in the future. We could consider an official API for adding arbitrary metadata to the config of each component

But In a future version the component config maybe me more dynamic than it is now. But if this metadata was only acted upon when each component mounted, that wouldn't be an issue. We may also consider APIs for this usecase as well (running js when a component mounts rather than using the current JS hooks, which have some limitations). 

All that said, we'll be adding the ability to create custom components in a future version, which may offer the cleanest path for this kind of thing.

**Comment by AUTOMATIC1111** [comment]
> custom components

Very cool.

**Comment by abidlabs** [comment]
Closing as we now support [custom components](https://www.gradio.app/guides/five-minute-guide), which offer a much more flexible approach for tooltips or including custom attribute.
