### ISSUE TITLE
Please add these alerts messages: gr.Success(), gr.Warning(), gr.Info()

### ISSUE THREAD

**Issue by medram** [gradio-app/gradio#4319]
Please add these alerts messages: gr.Success(), gr.Warning(), gr.Info()

- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Sometimes we need to guide/inform the user about something.

**Describe the solution you'd like**  
please add gr.Success(), gr.Warning(), gr.Info()

Thanks in advance.

**Comment by abidlabs** [comment]
Hi @medram I'd suggest that you use the custom `Progress` bar if you need to inform the user about something related to your prediction functions. By design, the modals are meant to be used very rarely (really only when an exception is raised and your function cannot proceed)

Docs about progress bar: https://gradio.app/key-features/#progress-bars
