### ISSUE TITLE
A component that shows the status of the queue before a prediction is submitted

### ISSUE THREAD

**Issue by devendergarg** [gradio-app/gradio#435]
It can avoid high queue. Some people leave the screen after looking at long queue after submit.

**Comment by abidlabs** [comment]
Hmm @aliabid94 what do you think? Can we show a live queue as soon as the interface loads?

**Comment by abidlabs** [comment]
Also heard on Twitter:
![image](https://user-images.githubusercontent.com/1778297/147794050-034dc458-3dc8-4ce5-a237-7436896867cf.png)

**Comment by FarukOzderim** [comment]
We could easily use the queue/status endpoint and show it at page load. The only point to think about is having multiple events with Blocks.

**Comment by fffiloni** [comment]
+ 1 

i was looking for a solution for this.
subscribed :)

**Comment by abidlabs** [comment]
Hi @fffiloni @FarukOzderim @devendergarg and others who've requested this feature. Can you please elaborate a little more on why this would be important to users to see? If a user makes a request and there is a long queue, they can always close the tab (and in which case they'd be removed from the queue)

**Comment by fffiloni** [comment]
It useful when the queue is short and full, so the user get a « queue is full, try later »
Showing the queue status can be an indicator to know when to re-engage ;)

**Comment by abidlabs** [comment]
Interesting, so you're thinking a live indicator that is more or less binary: is the queue ready to accept users or not

That sounds potentially useful to me

**Comment by fffiloni** [comment]
Exactly yes

**Comment by freddyaboulton** [comment]
Where should this indicator be displayed?

**Comment by fffiloni** [comment]
Why not at the top-right corner of the output component div ?

**Comment by abidlabs** [comment]
Hmm I do see the value of this feature. But in order for this queue status indicator to be useful, we would need to submit requests continually to the backend to check the queue status, and these requests would start as soon as the page loads. It might cause a lot of network traffic on apps that are already getting a high level of traffic. I'm not sure if the upside is worth it.

**Comment by abidlabs** [comment]
I wonder if this should be a separate (custom?) component that users can add to their Gradio demos if they would like? 

E.g. check out this Space: https://huggingface.co/spaces/Intel/Stable-Diffusion which somehow implemented this: 

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/1778297/219292640-4e3df50b-505a-4d20-b3b1-add4ae7c6708.png">

**Comment by fffiloni** [comment]
sounds good to me

**Comment by abidlabs** [comment]
Hi! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help if you'd like to put together a custom component for this issue
