### ISSUE TITLE
Style changed when upgrade gradio==3.16.2 to gradio==3.21 in stable diffusion ui 

### ISSUE THREAD

**Issue by peijianbo** [gradio-app/gradio#4372]
because i want use .submit().then() with gradio, but .then method only worked on gradio version>3.21. so i upgrade gradio==3.21. however the style has a big change when upgraded:

gradio==3.16.2 style:
![image](https://github.com/gradio-app/gradio/assets/42259444/e65b02e3-0697-44a5-8409-b4a3cee7e980)

gradio==3.21 style:
![image](https://github.com/gradio-app/gradio/assets/42259444/cd258ce7-880b-44d5-b7d7-9c9ef3c8bece)

how can i solve it？

**Comment by abidlabs** [comment]
Hi @peijianbo the Stable Diffusion WebUI includes significant amounts of custom CSS and JS. Unfortunately, we cannot guarantee this be consistent across different gradio versions since DOM elements may themselves change across different versions. My suggestion would be to look at the JS console and terminal to see if you have any warnings that may indicate which CSS/styling rules are not being correctly applied in your case.
