### ISSUE TITLE
May ChatBot support edit query in chat history?

### ISSUE THREAD

**Issue by tianzhipengfei** [gradio-app/gradio#4444]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I want to use gradio to implement my chatbot quickly. I use char.Chatbot as the component for chatting feature. However, I found I cannot modify the query in chat history. Though I used css to make the element editable, the beckend cannot track the change in browser.

**Describe the solution you'd like**  
It is great to make Chatbot module supports editable, just like ChatGPT.

**Comment by abidlabs** [comment]
Hi @tianzhipengfei the approach I'd suggest is along the lines of the Falcon demo here: https://huggingface.co/spaces/HuggingFaceH4/falcon-chat-demo-for-blog

Where instead of a Delete Last Turn button,  you could actually have an Edit Last Turn button. That button would delete the last conversation and bring the user input back to the textbox, allowing you to edit it and resend it to the chatbot. Since this is doable with Gradio already and not a feature request, I'll close this issue. You can ask follow up questions on the HF Forums (https://discuss.huggingface.co/c/gradio/26) or on Discord (https://t.co/JKepTfXraQ) instead.
