### ISSUE TITLE
Changing minimum/maximum on an unconnected slider disables it

### ISSUE THREAD

**Issue by 2-5** [gradio-app/gradio#4471]
### Describe the bug

If you create two sliders, one with defaults, and the other with changed minimum/maximum, the last one will be disabled.

The sliders are not connected to anything, which is a bit pointless, so I'm not 100% sure this is a bug or by design.

I discovered this bug in the context of the `blocks_kitchen_sink` demo, where controls are unconnected.

Seems related: https://github.com/gradio-app/gradio/pull/2459

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

DISABLED:

```python
import gradio as gr

with gr.Blocks() as demo:
    gr.Slider()        # ENABLED
    gr.Slider(10, 20)  # DISABLED

demo.launch()
```

### Screenshot

![2023-06-10_003557](https://github.com/gradio-app/gradio/assets/3753822/3c4c8f83-ce2d-4ca2-90e9-b42a630060a1)

### Logs

```shell
-
```

### System Info

```shell
Gradio 3.34.0, Windows 10, Chrome
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @2-5 ! Yea this is by design. In general, if a component is not used as input for an event, it's not interactive. We make a couple of exceptions though, namely that if the initial value is 0 or "" or [], then we make the component interactive. This explains the difference between the two sliders. When you set min=10/max=20, the intial value gets picked to be in the ranged which makes it non-zero.

If the built-in heuristics don't work for your particular use case, you can set `interactive` in the component constructor to force something to be interactive.
