### ISSUE TITLE
An event listener for mouse movements

### ISSUE THREAD

**Issue by sanbuphy** [gradio-app/gradio#4507]
- [√ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
None

**Describe the solution you'd like**  
I would like to implement a demonstration similar to that of the SAM website, where there is a mouse movement event bound, and the area is continuously calculated while moving the mouse. This can be used to display different things when I move the mouse to certain areas of the image. However, it seems that there is only a click event available at the moment?

**Additional context**  
None

Thank you very much.

**Comment by abidlabs** [comment]
Hi @sanbuphy that's correct. I'll leave this is a feature request that we explore at some point in the future

**Comment by 1049451037** [comment]
I think just adding "right click" event is also a good workaround to support more functions. Looking forward to it.

**Comment by abidlabs** [comment]
Folks, I think this would be a great case for a custom component!

we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
