### ISSUE TITLE
Adding 'gr.examples' could freeze corresponding Textbox, if the Textbox is not an input to a submit button.

### ISSUE THREAD

**Issue by Neph0s** [gradio-app/gradio#4541]
### Describe the bug

When I write this code:
with demo:

	with gr.Tab('Inspiration'):
		with gr.Row().style(equal_height=False):
			with gr.Column():
				input_1 = gr.Textbox(label="Inspiration", placeholder="Inspiration")
				sys_prompt_1 = gr.Textbox(label="Task Prompt", placeholder=prompts.inspiration_prompt)
				with gr.Row():
					clear_1 = gr.Button('Clear')
					submit_1 = gr.Button('Submit', variant='primary')
			with gr.Column():
				output_1 = gr.Textbox(lines=2, label="GPT4 result")

		gr.Examples([examples.inspiration_example_1], input_1) 

	clear_1.click(None, [],  [input_1, output_1], _js=f"""() => {json.dumps([getattr(component, "cleared value", None) for component in [input_1, output_1]])}""") 

I found that, after adding gr.Examples([examples.inspiration_example_1], input_1), the input_1 Textbox becomes frozen, which means that I am unable to edit it.

After adding submit_1.click(funcs.do_copy, inputs=[input_1, sys_prompt_1], outputs=[output_1]) to the end of this code, the problem disappears.

This may not be a serious bug for a matured code. However, it takes me two hour to fix this problem during development. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Provided above

### Logs

```shell
None
```

### System Info

```shell
None
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @Neph0s agree that this is a bit confusing and thanks for creating this issue for visibility for others. However, this is actually the expected behavior. If a component is *only* used as the output of an event listener, then it is rendered not interactive. As soon as it is used as the input to an event listener, it is rendered interactive. Gradio automatically handles this, as described here: https://gradio.app/blocks-and-event-listeners/#event-listeners-and-interactivity

However, if you would like to override this behavior, you can pass in `interactive=True` to `gr.Textbox()`.
