### ISSUE TITLE
When using generator the processing timer stops after first result

### ISSUE THREAD

**Issue by dashesy** [gradio-app/gradio#4776]
### Describe the bug

While a query is being processed gradio shows a timer like this
![image](https://github.com/gradio-app/gradio/assets/873905/37ae99b6-926e-414e-89be-7beceebd6cfc)

This timer should stop after the generator is exhausted, but it stops after the first result that comes from yield

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
    def bot(history)->Iterator[List]:
        if not history:
            yield history
            return
        query = " some query "
        for result in ai.run(query):
            history += [(None, result)]
            yield history
...

        generate.click(add_text, [chatbot, txt], [chatbot, txt], queue=False).then(
            bot, chatbot, chatbot
        )
```

### System Info

```shell
gradio: 3.35.2
OS: Linux 18
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @dashesy this is intentional -- we don't know exactly how long a job will take. If there are many jobs ahead of the current one, we estimate the ETA it will take for the current job by keeping track of the average runtime of previous jobs and multiplying by the number of jobs in the queue. However, in practice, jobs can take different amounts of time to complete (if the runtime depends on the input sequence length, etc.) and so we wouldn't want to provide an estimate the time of completion to the current job. 

Instead, we have other options you can use to indicate the progress of the current job, such as the `gr.Progress` progress bar, which you can read about here: https://gradio.app/docs/#progress-header

**Comment by dashesy** [comment]
Thanks @abidlabs. I do not know how many steps are going to be needed. And in the meanwhile, I can still click on the submit button! 
There is no indication that further steps are in progress at all. Only for the few first step or two I see chatbot showing a ... to indicate there is a progress.

Is there a way to disable the buttons while waiting for the results of yield to finish?

**Comment by abidlabs** [comment]
Perhaps something like this will work? https://twitter.com/abidlabs/status/1668590865248403459
