### ISSUE TITLE
Adding gradio to Code Library Search Chatgpt plugin

### ISSUE THREAD

**Issue by mswoff** [gradio-app/gradio#4837]
I wanted to let you know that users of our Code Library Search Chatgpt plugin has requested we support the gradio Python library. Unless we hear otherwise from you, we’ll add support for gradio (free for open source and no action required from gradio contributors).

The plugin let's users get library specific coding help by analyzing gradio's codebase.

If you want to get in touch about any concerns or offering AI based support directly on gradio.app or adding additional documentation/examples that aren't in the release, please email me at mason@salv.ai.

**Comment by abidlabs** [comment]
Thanks @mswoff, as there are no action items here I'll close this issue.

One suggestion I have for you (if possible) is to discourage the use of `gradio.inputs.X` and `gradio.outputs.X`. Both of these have been deprecated in favor of using `gr.X` directly. 

For example, you should not write `gr.inputs.Textbox` but instead do `gr.Textbox`. I mention this because the previous syntax will be fully deprecated in Gradio 4.0 soon.
