### ISSUE TITLE
Gradio starting with 3.36 is extremely slow

### ISSUE THREAD

**Issue by vladmandic** [gradio-app/gradio#4841]
### Describe the bug

I just upgraded my app from Gradio 3.32.0 to 3.36.1 (I cannot use versions in-between due to breaking change that was fixed post 3.35.2) and browser page load time grew from 5sec to 15sec.

Yes, its a highly complex app with too many controls, but 300% performance degradation is not what I would expect.

Once page load completes, actual functionality is on-par and I don't see any errors.
Note that assets download is not an issue, they all complete fast (seen in browser inspector network tab), its actual building of the UI, for example JS code  inside `http://127.0.0.1:7860/assets/Blocks-7b1f1558.js` takes 5sec to execute alone.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Install [SD.Next](https://github.com/vladmandic/automatic) and start it using `webui.sh/webui.bat`  
  (first start will install a lot of dependencies so it may take long)
2. Change `requirements.txt` to use new Gradio and start again

### Logs

```shell
No error messages in console or browser console
```

### System Info

```shell
Server Gradio 3.36.1 on Ubuntu 22.04
Client Chrome 114 on Windows 11
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
Nothing major has changed recently so this is somewhat surprising, although I do have a slight suspicion about what this might be. I'll investigate and report back!

**Comment by pngwn** [comment]
I know what this is now and I'll fix it as part of #3261. 

The issue is two-fold.

1. Complex apps with large numbers of components are all processed at app startup, regardless of how many are on view at any time.
2. We programatically attach events. For 'normal' events we know which ones the user has applied (`btn.click()` etc) so the impact in minimal (though not zero) but we also use events to handle errors dispatched from components, we almost always need to know about these events so we need to attach the listeners. Attaching listeners to hundreds or thousands of components is very expensive.

1\. is a multi-faceted issue and involves substantial changes to fix entirely. 
  - The first step is to ensure we only render things if they are visible (inactive tabs, `visible=false` should not be rendered). This _used_ to be the behaviour but we changed it because we only store the props (i.e. state as gradio-python understands it) in memory, we do not store the state necessary to rehydrate all components exactly as they are currently. This mean switching tabs resets state, for example, and we don't have sufficient data to recreate it exactly as it was. This will be taken care of at some point soon and can be done independently of gradio python and requires no breaking changes (although it isn't trivial). 
  - The ideal scenario is that the config is fully dynamic and can be updated at any time, rerendering the UI. This is a more substantial change because it will introduce a number of new challenges, none of which are insurmountable. This will probably involved breaking changes, or a significant enough internal refactor that it makes sense to release it as part of 4.0, if we decide to do it.
  
2\. This can be resolved fair simply by changing how we listen for events. I have a few ideas that I think will work but will need some testing. I will also look at refactoring other similar code to improve performance across the board. This _should_ result in a significant improvement to startup time for _all_ apps but especially complex ones with many components. It will also simplify some of our  initialisation code, although there are tradeoffs.

I'll take care of this as I'm working on the refactors over the next few weeks.

**Comment by vladmandic** [comment]
any update on this issue? its open without any updates for over a month.
gradio 3.40 was just released and page load is so slow that brower reports "page is not responding" and asks to kill it.
in the meantime i'm stuck on gradio 3.32 since other blocking issue i had was only resolved in >=3.36.

also note its confirmed it has same impact on multiple apps, so this is turning into a big thing - i don't think this can be burried any longer under "technical debt" - its a massive regression.

cc @pngwn @abidlabs

**Comment by MoonRide303** [comment]
> any update on this issue? its open without any updates for over a month. gradio 3.40 was just released and page load is so slow that brower reports "page is not responding" and asks to kill it. in the meantime i'm stuck on gradio 3.32 since other blocking issue i had was only resolved in >=3.36.
> 
> also note its confirmed it has same impact on multiple apps, so this is turning into a big thing - i don't think this can be burried any longer under "technical debt" - its a massive regression.
> 
> cc @pngwn @abidlabs
> 
> ![image](https://user-images.githubusercontent.com/57876960/259954734-90c55cb6-e693-4663-8055-ca56eb2695c0.png)

Same problems can be observed in SD web UI (when you add multiple extensions, and UI size grows). It's kinda ridiculous for UI framework to initialize still relatively small number of components in time like minute - it's longer than whole OS boot time...

**Comment by pngwn** [comment]
Sorry for the delay! This is literally the the first thing I'll be taking care of tomorrow.

**Comment by anapnoe** [comment]
> Sorry for the delay! This is literally the the first thing I'll be taking care of tomorrow.
> 
> Content visibility would not help in this case.

https://svelte.dev/repl/2a0f3556497a43f1aaf88f9219dfc6a2?version=4.2.0
maybe event delegation can help reduce the amount of the event listeners
