### ISSUE TITLE
Possible to change Textbox submit key from Shift-Enter to Enter with multilines input 

### ISSUE THREAD

**Issue by liaoweiguo** [gradio-app/gradio#4919]
- [ ] I have searched to see if a similar issue already exists.

user want to submit more efficient

**Comment by abidlabs** [comment]
I'm confused as to how would this work -- enter would go to the next line, it shouldn't also submit

**Comment by liaoweiguo** [comment]
In China, we use Enter for submit, shift+enter for nextline. A choice will be fine

**Comment by abidlabs** [comment]
Interesting, good to know thanks @liaoweiguo

**Comment by abidlabs** [comment]
Hey! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help. Hopefully this will help address this issue.

**Comment by abidlabs** [comment]
I'll go ahead and close this issue since we are not planning to include this in the core Gradio library. But happy to help if you are interested in making this a custom Gradio component (feel free to ask questions in this issue).
