### ISSUE TITLE
A sharing interface is still running few days, can help to termiate it?

### ISSUE THREAD

**Issue by sunnyxcao79** [gradio-app/gradio#4935]
### Describe the bug

I ran a sharing gradio interface via binder from 13 July 2023.  Now the binder notebook already shutdown from 13 July 204, but the share interface is still running till today.  can help to terminate it?

the share link is https://f21b9e948a967ab90a.gradio.live/

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

The link is https://f21b9e948a967ab90a.gradio.live/

### System Info

```shell
https://f21b9e948a967ab90a.gradio.live/
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @sunnyxcao79 if the binder notebook shuts down, then the share link would go down automatically. However, the fact that the share link is still active and the Gradio app runnable suggests that the binder link is still active.

Can you try restarting or forcibly closing the binder notebook? We don't shut down share links on our end since we have no way of knowing share link ownership.
