### ISSUE TITLE
API request need session States for chat history

### ISSUE THREAD

**Issue by YerongLi** [gradio-app/gradio#4951]
- [x] I have searched to see if a similar issue already exists.

We need session history state for chat robot Blocks()
https://www.gradio.app/docs/chatbot

**Is your feature request related to a problem? Please describe.**  
For web interface, different user have different session history States, while for API call there is no session States.

**Describe the solution you'd like**  
We need session states that with a same {"user" : "id" }, keep the user session State for a timeout.

**Additional context**

**Comment by freddyaboulton** [comment]
Hi @YerongLi!

We just released `ChatInterface` which makes it really easy to build chatbot UIs: https://www.gradio.app/guides/creating-a-chatbot-fast . This will handle the history for you.

Refer to this guide (https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks) if you need more control over the application layout or functionality.

Since this isn't a bug or feature request, I'm going to close this issue.
