### ISSUE TITLE
File cannot be fetched...

### ISSUE THREAD

**Issue by LLKoder** [gradio-app/gradio#5107]
### Describe the bug

I did not use Automation 1111 for ~2-3 months, It was all ok before. Today I have runned it and see UI was broken (some buttons are very big). I try install different version of Gradio - nothign help me.

I try Python 3.10.6 and 3.10.11.

I see some files of Gradio not load in browser, may be it help you to understand my problem.

I have no ideas what happened.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12302

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Just run Automatic 1111

### Screenshot

![258337452-fc0206be-d792-46e1-af3e-60acb3aeb6fd](https://github.com/gradio-app/gradio/assets/50442676/8160466c-7df8-4f59-84a5-724ac46b99ab)
![258337509-bc116c56-18ed-43a3-ba33-7570709246b8](https://github.com/gradio-app/gradio/assets/50442676/5fa8d51d-d5c9-46fe-b5c6-af11a58b0ff5)
![258337498-b4266b06-fcf7-4307-9c74-f20ce425afa9](https://github.com/gradio-app/gradio/assets/50442676/a109f7f3-06e2-40c1-be0f-96f8921d72c9)
![258337483-5ddda1e0-a92d-4fd7-8950-4a2b2665fe58](https://github.com/gradio-app/gradio/assets/50442676/b82a26e9-aedf-4355-8355-826eb7652b60)

### System Info

```shell
gradio environment

Launching in *reload mode* on: http://127.0.0.1:7861 (Press CTRL+C to quit)

Watching: '...\.venv\lib\site-packages\gradio', '...\.venv\Scripts'

ERROR:    Error loading ASGI app. Could not import module "environment".
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @LLKoder for letting us know that its been solved. I'll close this issue.

**Comment by yyhhenry** [comment]
I encountered the same error again on Windows(, and not related to symbolic links), because I put it in a folder whose name starts with a dot (.), such as C:/.bin/stable-diffusion-webui. However, it worked fine when I reverted to version v1.5.2 of SD WebUI (with older version of gradio like 3.32). So I guess it might be related to some update of gradio. 

I guess gradio automatically adds the dot-starting directories to the block paths, even if the dot actually overlaps with the root path. I hope this judgment is based on relative directories, so that it won’t cause similar problems.

**Comment by abidlabs** [comment]
Hi @yyhhenry this is an intentional security feature, please see: https://www.gradio.app/guides/sharing-your-app#security-and-file-access

<img width="981" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/b5ff3c12-8dea-465b-9e0d-8f932c573088">

**Comment by yyhhenry** [comment]
@abidlabs Thank you very much for your explaining. It seems that this is a new feature, which makes the behavior of gradio 3.41.x different from the one I used before, 3.32.x. It took me 4 hours to find the reason, but now I get it. Thanks again.
