### ISSUE TITLE
time.monotonic() or time.perf_counter() should be used instead of time.time() to measure elapsed time

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#5170]
For example in
https://github.com/gradio-app/gradio/blob/abec340a54cddd096972bb93906656e0f6e1de3b/gradio/queueing.py#L390

 https://www.webucator.com/article/python-clocks-explained/ says
> `time.time()` should NOT be used for comparing relative times. It’s not reliable because it’s adjustable.

**Comment by abidlabs** [comment]
I don't think this is a big deal -- if a developer adjust their own click, yes it might effect the queuing etas but this is case of a developer doing something intentional to mess things up. It seems very unlikely and something that a developer should be aware may have side effects on any other Python processes running on their machine. I'm going to close this issue, but feel free to reopen @whitphx if you believe differently
