### ISSUE TITLE
Feature request: Can gradio Accordion have event click like Button

### ISSUE THREAD

**Issue by githubheyguy** [gradio-app/gradio#5197]
docs: https://www.gradio.app/guides/controlling-layout
`
gr.Accordion("Open for More!") 

`

if it has a method to know if that Accordion is clicked or toggle on it is good and more flexible

**Comment by abidlabs** [comment]
I think adding `.open()` and `.close()` events to the `gr.Accordion` class is a great idea @githubheyguy! We'd be happy to review any contributed PRs fro this.

**Comment by p1utoze** [comment]
Hey! I would like to work on this issue? @abidlabs could you please elaborate more about it? `.open()` function might cause an issue with python built-in.

**Comment by abidlabs** [comment]
Hi @p1utoze feel free to take it! As inspiration, you can see how other layouts such as `gr.Tab` have the `.select()` method defined.

>  .open() function might cause an issue with python built-in.

This shouldn't be a problem since such an instance method named .open() in the class won't directly clash with the built-in open function used for opening files, as they exist in different namespaces.

**Comment by vlasvlasvlas** [comment]
hi! this would be great, its already working? would to to close accordion when clicked on button for ex

**Comment by JackismyShephard** [comment]
Is there any updates on this? I could really use it for my project as well.

**Comment by starmoon-1134** [comment]
+1

**Comment by martinscooper** [comment]
+1
