### ISSUE TITLE
Trimming audio via the UI does not trim video in UI and causes processing error

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5246]
### Describe the bug

Noted by @fffiloni

Two issues with trimming audio:
1. Trimming area from the audio does not update the player to begin at the chosen starting point —> this one is a bug present since the 3.36.0
2. Processing the chosen audio area after selecting in_point and out_point (with the handles) give me a bug when using an audio coming from a Youtube downloaded sound

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/fffiloni/audio-trimming-bug

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/41651716/0ae9d21e-e497-4b4a-b93b-2676ff138522)

![image](https://github.com/gradio-app/gradio/assets/41651716/1fc368fd-c67c-4098-a781-1143911f23a2)

### System Info

```shell
-
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi folks, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!
