### ISSUE TITLE
Is it possible to have a flow attached to the bot . Like Track --> Phonenumber --> Result of API Call.

### ISSUE THREAD

**Issue by SathishNaqel** [gradio-app/gradio#5372]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Is it possible to have a flow atatched to the bot 

**Describe the solution you'd like**  
Is it possible to have a flow atatched to the bot 

**Additional context**  
Is it possible to have a flow atatched to the bot

**Comment by abidlabs** [comment]
Hi @SathishNaqel, for general questions like this (that are not feature requests or bug reports), please ask in our [Forums](https://discuss.huggingface.co/c/gradio/26) or [our Discord](http://discord.gg/feTf9x3ZSB). When you do ask, please provide more details including a code snippet of what you've tried -- otherwise we won't be able to answer your questions. (I'll close this issue)
