### ISSUE TITLE
Let `allowed_paths` allow access to dotfiles 

### ISSUE THREAD

**Issue by Yasand123** [gradio-app/gradio#5407]
### Describe the bug

Using Automatic's Stable Diffusion WebUI, Gradio looks broken and does not function properly. After a helpful comment -- https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13027#issuecomment-1704377186 -- in an issue I opened yesterday, it looks like having a dot in the file path was causing this.

So for example: if Gradio is located in `/home/john/.local/` (notice the dot) Gradio will not function properly. Moving the project to `/home/john/` made the issue go away. I am just assuming this is a Gradio related issue and not something else.

I did manually upgrade to version 3.42.0. Same issue.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

- Have a dot in the file path
- Gradio does not function properly

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/14009700/b4e93ef7-315b-4b70-85e3-bdb7f8df5a43)

### System Info

```shell
https://github.com/AUTOMATIC1111/stable-diffusion-webui/files/12505964/sysinfo-2023-09-03.txt
```

### Severity

I can work around it

**Comment by pngwn** [comment]
I believe this is intentional, I think we made a change a little while ago to ignore dot files.

cc @abidlabs

**Comment by abidlabs** [comment]
Hi @Yasand123 this is intentional -- by default, Gradio does not serve dotfiles or any files inside dot-folders. This is to prevent accidental leaking of secrets which are often in these locations. See

See: https://www.gradio.app/guides/sharing-your-app

However, considering your original issue, I think we should provide a workaround in cases where the Gradio app must be launched from a dot-folder. We already have a `allowed_paths` parameter -- currently it does not override the the dotfiles / dot-folders restriction, but we can have allow serving such files if they are located in any of the `allowed_paths`

**Comment by abidlabs** [comment]
Relabeled the issue to reflect this feature request, thanks @Yasand123

**Comment by abidlabs** [comment]
From @wfjsw:

> I wonder if it is better to exclude the app base path (working directory) when looking for dots here. This would provide a compromise when the app itself is placed in a dot folder while still making this hardening relevant.

**Comment by abidlabs** [comment]
Fixed in `v4` branch!

**Comment by bendavis78** [comment]
> Fixed in `v4` branch!

@abidlabs, what specifically is the fix? How do we allow dotfile paths? If my app is installed in ~/.local/share I get 403 for most assets.
