### ISSUE TITLE
how to use radio in chatbot

### ISSUE THREAD

**Issue by lsqingfeng** [gradio-app/gradio#5438]
I hava a new requirement:

when I asked a question in chatbot, 
the bot give me some choise , not an answer.
then I can choose , the bot will answer me use what I choosed. 

how to get It? please help me

now I use html in chabot, chatbot can render it. but I cannot get the value which i choose,  so that , the bot cannot answer next.

**Comment by dawoodkhan82** [comment]
Hi @lsqingfeng , this is more of a question rather than an issue. Next time you can use our discord and ask any questions there [(Gradio Discord)](https://discord.com/invite/feTf9x3ZSB). But to answer your questions we don't currently support adding a radio button into the chatbot. What you can do instead is have the bot return two messages and allow the user to select the message they want using the `select` event handler (https://www.gradio.app/docs/eventdata)
