### ISSUE TITLE
Output files can't be downloaded in Colab

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#5511]
### Describe the bug

When playing in Colab, I'm having issues downloading output files. I've had this issue in the dreambooth colab for example.

* If I try to right click + download generated output, I actually get to download a HTML file 
* If I try to download with download icon at top right, it tries o download a correct file but then it fails to download

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Minimal Colab - https://colab.research.google.com/drive/1x4YuWP8DVWLtqpE8RnP0ELKZqe_LOQBp?usp=sharing 

### Screenshot

![screenshot_from_2023-09-10_16-45-45_720](https://github.com/gradio-app/gradio/assets/7246357/05098563-a4cd-48d6-99ff-0d83506bd783)

### System Info

```shell
Colab
```

### Severity

Blocking usage of gradio

**Comment by ragman-google** [comment]
Richard from Colab here. We think we've diagnosed this problem.

Trying to repro it now, I actually don't get as far as rendering the Submit button and the waveform, I just get a 403 immediately.

We think the underlying problem is the same though.

The requests that gradio is making in the Colab output are going to `pw9...-colab.googleusercontent.com` origin, but they should be going to the `https://localhost:7860` origin.

Colab will then intercept that request and route it to the correct `googleusercontent.com` origin with the correct permissions.

Maybe something changed in the Gradio code recently? 

We have some docs on how to serve resources in a Colab output here: https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb#scrollTo=R8ZvCXC5A0wT

We'd love to get this working again, so please let us know if there's anything we can do on our end to help.

**Comment by abidlabs** [comment]
Hi folks! Gradio apps in Colab now automatically create a share link, which solves this issue.
