### ISSUE TITLE
Overflow of `gr.Dataframe` table columns

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#5523]
### Describe the bug

Somehow, some of the links in the table in [this Space](https://huggingface.co/spaces/hysts/list-of-demos) are overflowing. ([internal slack](https://huggingface.slack.com/archives/C02QZLG8GMN/p1694596884767699))

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/hysts/list-of-demos

### Screenshot

![00](https://github.com/gradio-app/gradio/assets/25161192/fb13e67b-f65f-4af2-9da0-358322a69d12)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.44.0
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.1
ffmpy: 0.3.1
gradio-client==0.5.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.3
numpy: 1.25.2
orjson: 3.9.7
packaging: 23.1
pandas: 2.0.3
pillow: 10.0.0
pydantic: 1.10.12
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.25.0
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by rabroldan** [comment]
hey there is this issue still up for grabs?

**Comment by abidlabs** [comment]
Yes it is!

**Comment by abidlabs** [comment]
Ok so this issue is actually more complicated than I originally thought. The problem is that the column widths are set based on the length of the content of the visible rows. That means if there's a particularly wide column later on, its content will get cut off. There's no real way of knowing the maximum column width without losing all of the benefits of using a virtual table.

So given that we have to keep the column widths as is, I think we should do these two things:

(1) set the `overflow-x` behavior to `hidden`, which means that the overflow content will be clipped, like this:

<img width="508" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/fa4d4f12-99b3-40d2-8250-d11239fb45bc">

(2) make the column widths adjustable, so that the user can drag the headers to increase the width

WDYT @hysts @pngwn?

**Comment by abidlabs** [comment]
Actually I meant that the solution would be to implement both (1) and (2) :) 

Let me look into wrapping / column widths and see what we can do there

**Comment by abidlabs** [comment]
Ok I think #5894 may offer a solution by setting the column widths manually and then setting `wrap=True`. wdyt @hysts?

**Comment by rabroldan** [comment]
@abidlabs when i was doing this i tried implemeting a dynamically a allocating maxwidth of each row taking in the longest string as the basis of the table. unfortunately it was harder to implement than i initally thought

**Comment by hysts** [comment]
> Actually I meant that the solution would be to implement both (1) and (2) :)

Ah, OK, sorry, I misunderstood.

> Ok I think https://github.com/gradio-app/gradio/pull/5894 may offer a solution by setting the column widths manually and potentially setting wrap=True. wdyt @hysts?

I just realized that somehow I missed this comment and the PR. Sorry! Anyway, the solution looks great! Thanks a lot!
