### ISSUE TITLE
Supporting HTTPS when running locally

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#563]
Hi Adi,
Thanks for the quick response.
So explain in detail, I have made a gradio app and it by default ran on  a http connection when I provided my vm ip address in the server_name parameter for the launch function.http://12.13.65.70:3031 (my VM ip address).

But due to company requirements, I have to run this on https. Like https://12.13.65.70:3031.
We have a cert and key available but I am not sure how can I pass them to launch function.

I tried wrapping the gradio interface in  a flask app and tried to run it by additionally providing ssl_context. But unfortunately I did not work.
Can you suggest any idea here?

_Originally posted by @vijay2405 in https://github.com/gradio-app/gradio/discussions/370#discussioncomment-2135364_

**Comment by abidlabs** [comment]
Hi @vijay2405, this is now supported in the latest version of `gradio` on `master` which takes two arguments directly: `ssl_keyfile` and `ssl_certfile` in the `launch()` method. You can test this by generating a certificate for localhost (e.g. following this guide: https://dev.to/rajshirolkar/fastapi-over-https-for-development-on-windows-2p7d) and confirm this works for you.

We will release a new version to PyPi by the end of this week . If you need this fix before then, please take a look at the [contributing guidelines](https://github.com/gradio-app/gradio/blob/master/CONTRIBUTING.md) about how to install from the `master` branch.

**Comment by Escovilla** [comment]
I encountered an issue with using a self-signed certificate and encountered an SSL error with the message "certificate verify failed: unable to get local issuer certificate". To resolve the issue, I followed a solution provided by @abidlabs https://github.com/gradio-app/gradio/issues/563#issuecomment-1033365497 , but it still returned error `certificate verify failed: unable to get local issuer 
certificate .` However, after checking another resource, I  made a change in the blocks.py file of Gradio by setting verify=False in the requests.get function, and that solved the issue.
` requests.get(f"{self.local_url}startup-events", verify=False)`

**Comment by abidlabs** [comment]
Or actually would like to open a PR with the fix? Would be much appreciated!

**Comment by abidlabs** [comment]
Or actually @Escovilla would you like to open a PR with the fix? Would be much appreciated!

**Comment by Escovilla** [comment]
> I encountered an issue with using a self-signed certificate and encountered an SSL error with the message `certificate verify failed: unable to get local issuer certificate .` However, after seeing https://stefvanlooveren.me/errors/how-fix-sslerrore-requestrequest-requestsexceptionssslerror-httpsconnectionpool. I made a change in the blocks.py file of Gradio by setting verify=False in the requests.get function ` requests.get(f"{self.local_url}startup-events", verify=False)` , and that solved the issue.

Upon further investigation, I've come to the realization that the use of verify="false" is not advisable for production environments, and although I'm currently utilizing it for my local development, it poses a significant risk for live systems.
I removed the `verify=False` , I generated a certificate using the mkcert utility and added it to my Certificate Authority. In order to allow other users on my local network to use the app, I updated the mkcert command to include the IP address of my computer on the network, changing it from mkcert localhost 127.0.0.1 ::1 to mkcert 192.168.1.3 192.168.1.3 ::1.

**Comment by abidlabs** [comment]
@Escovilla I got a notification (although I can't see the comment now) with a message from you saying that `verify=False` is not advisable. Would you like to reshare your solution and then I think we can close this issue?

**Comment by Escovilla** [comment]
@abidlabs I initially commented that  

> removing the `verify=false` in requests is not advisable for production environments, and although I'm currently utilizing it for my local development, it poses a significant risk for live systems if implemented. Regardless I still used `verify=false` for my local server for local computers to access (web application using a camera)

We could consider adding an option for both self-signed and trusted certificates that would toggle verify=true for trusted certificates and verify=false for self-signed certificates. To avoid compromising live production while having an optionality for developers to use self signed certificates ( to whatever reason ) use https

**Comment by abidlabs** [comment]
Thanks for clarifying @Escovilla. Perhaps a flag called `ssl_verify` in the `launch()` method could control this. I'll look into this, thank you!

**Comment by Escovilla** [comment]
Right @abidlabs should I PR this implementation ?

**Comment by abidlabs** [comment]
That would be much appreciated @Escovilla, I'm happy to review

**Comment by abidlabs** [comment]
Hi @Escovilla did you get a chance to look into this?

**Comment by Escovilla** [comment]
Hi @abidlabs I apologize for being away. I will review the matter promptly

**Comment by gitgithan** [comment]
Is there any guide to setting up https for cloud deployment (so not localhost)?
It seems setting `ssl_keyfile="key.pem", ssl_certfile="cert.pem"` in gradio is only one part of the puzzle and there are infrastructure level setups required too?

Why is editting blocks.py of gradio required? This issue and https://github.com/gradio-app/gradio/issues/2551 both editted `blocks.py` but in different ways.

I tried aws ACM + ELB (couldnt point Domain registrar ionos to ELB which wasn't an ip address but readable words), certbot (couldn't setup apache properly following https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-ubuntu-20-04 maybe due to lack of ufw knowledge), free wildcard SSL that comes with IONOS domain (not sure if should use SSL Certificate, Intermediate Certificate, or PFX file in gradio launch parameter, tried all all failed).

I'm frequently getting errors from ssl.SSLContext saying can't find cert and key pem (looks like must be absolute path?), or permission denied (when using certbot generated cert+key) or `verify failed: unable to get local issuer certificate .` for a few cases i forgot.

**Comment by VikParuchuri** [comment]
@gitgithan The easiest way to do this is:

- Setup a Cloudflare account with HTTPS for your domain
- Select "flexible" as your cloudflare SSL mode, which means that your server will run in HTTP, but your client can connect in HTTPS (Cloudflare will handle the certificate)
- Run gradio normally with port 80, and no SSL certificate, etc.
- Add a cloudflare a record dns entry pointing to the IP of your cloud instance

**Comment by VikParuchuri** [comment]
@Escovilla @abidlabs Just setting `verify=False` for `requests.get` isn't enough to run with a self-signed certificate with the queue enabled, since websockets do their own SSL check.  I'm not sure how to disable that one (and you probably wouldn't want to!).

**Comment by gitgithan** [comment]
@VikParuchuri 
Nice to see you here.
`Run gradio normally with port 80, and no SSL certificate`
Whats the importance of starting with server_port=80? Is it to save the effort setting up reverse proxy (which helps user avoid appending :7860 to url)?  I'm getting `OSError: Port 80 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().`

When i try to enter https://...:7860 in url i get `WARNING:  Invalid HTTP request received.` .
I changed nameservers to the two from cloudflare, set flexible SSL,  turned on universal SSL of cloudflare, is there any missing step? I see a page of configuration rules, tried adding a rule and still both http and https don't work when im running gradio on default 7860 without specifying `server_port:80` or the 2 ssl parameters

**Comment by VikParuchuri** [comment]
@gitgithan Port 80 is the typical HTTP port.  Yes, if you're running a reverse proxy like nginx, you can specify another port, as long as nginx is configured to map port 80 to that port.  I mentioned port 80 because you want to run gradio in http mode, without any ssl cert, versus https, which would be port 443.

I think you have a few separate issues.  The reason cloudflare isn't working is because your web server isn't running properly.  I would resolve each one separately, instead of together.

- First, run your gradio server on port 80 (or whatever port your reverse proxy is configured to forward to).  Set share=True in launch, and make sure you can access the server from the huggingface url that is generated.
- Then, make sure your EC2 firewall settings, etc, enable you to access gradio on port 80.  Try to access gradio using the instance ip.
- Then, setup cloudflare ssl.  You just need to add a DNS entry to your EC2 instance up, as well as the SSL stuff.

**Comment by abidlabs** [comment]
Just circling back, it sounds like a setting to disable ssl verify would help with the local deployment. Is that something you are still interested in implementing @Escovilla?

**Comment by Taited** [comment]
> https://dev.to/rajshirolkar/fastapi-over-https-for-development-on-windows-2p7d

This is also what I am interested in.

**Comment by papuSpartan** [comment]
@abidlabs Would it not be possible to pass an ssl context to the websocket creation at the ` /queue/join` route in routes.py? This may be doable using the tls arguments already implemented for the uvicorn setup. Passing self-signed certificates using `REQUESTS_CA_BUNDLE` was enough before for getting https up and running locally. Now, the wss connection failing halts the entire flow of the gradio runtime.

**Comment by bharadwaj509** [comment]
So the https issue is resolved? Could some one let me know?

**Comment by garrettsutula** [comment]
> Thanks for clarifying @Escovilla. Perhaps a flag called `ssl_verify` in the `launch()` method could control this. I'll look into this, thank you!

I added what I think needs to be done here in [PR 3873](https://github.com/gradio-app/gradio/pull/3873)

@papuSpartan I think all that really needs to be done w/ that is to trust the self-signed cert in the host OS of the client device.

**Comment by papuSpartan** [comment]
@garrettsutula It would be, intuitively, except that the created wss websocket does not respect system-level trust store certificates. This is also why I had to use `REQUESTS_CA_BUNDLE` to get HTTPS connections to form properly when passing a certificate with the tls command line args (requests doesn't respect them either). It will pass your cert but doesn't do anything extra in the case that it is a self-signed certificate. Exposing an option to disable verification with `ssl_verify` is helpful but it doesn't have the same level of confidentiality as providing the extra context of that one cert to the wss websocket.

**Comment by garrettsutula** [comment]
> @garrettsutula It would be, intuitively, except that the created wss websocket does not respect system-level trust store certificates. This is also why I had to use `REQUESTS_CA_BUNDLE` to get HTTPS connections to form properly when passing a certificate with the tls command line args (requests doesn't respect them either). It will pass your cert but doesn't do anything extra in the case that it is a self-signed certificate. Exposing an option to disable verification with `ssl_verify` is helpful but it doesn't have the same level of confidentiality as providing the extra context of that one cert to the wss websocket.

Looks like this is a workaround it: https://github.com/gradio-app/gradio/commit/417004f9465aa5182b74093d0f245b4f76159864

The problem is that the http client used in `queueing.py` isn't being initialized with any ssl context. 

I am not sure how best to pass down from `blocks.py` - I could kludge it and add the ssl params but there's probably something different/better that could  be done instead.

**Comment by ucas010** [comment]
have the same bug and problem

**Comment by qiyuangong** [comment]
> > @garrettsutula It would be, intuitively, except that the created wss websocket does not respect system-level trust store certificates. This is also why I had to use `REQUESTS_CA_BUNDLE` to get HTTPS connections to form properly when passing a certificate with the tls command line args (requests doesn't respect them either). It will pass your cert but doesn't do anything extra in the case that it is a self-signed certificate. Exposing an option to disable verification with `ssl_verify` is helpful but it doesn't have the same level of confidentiality as providing the extra context of that one cert to the wss websocket.
> 
> Looks like this is a workaround: [417004f](https://github.com/gradio-app/gradio/commit/417004f9465aa5182b74093d0f245b4f76159864)
> 
> The problem is that the http client used in `queueing.py` isn't being initialized with any ssl context.
> 
> I am not sure how best to pass down from `blocks.py` - I could kludge it and add the ssl params to the Queue constructor but there's probably something different/better that could be done instead.

https://github.com/gradio-app/gradio/pull/3873 save one day for me. :)

Unfortunately, we still need to set `blocks.ssl_verify = False` to avoid blocks raise `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)` Error.

Instead of changing any code in Gradio, you can set `blocks.ssl_verify = False` before creating app.

```python
# This line turn off ssl_verify for blocks
blocks.ssl_verify = False

gradio_app = App.create_app(blocks)
```

**Comment by miguelwon** [comment]
I'm having  a related issue. I also need https, and I'm able to run my app with:

```
HOST = "0.0.0.0"
PORT = 8010
demo.queue()
demo.launch(
    favicon_path=favicon_path, 
    server_name=HOST, 
    server_port=PORT,
    share=False,
    ssl_keyfile="key.pem", ssl_certfile="cert.pem",
    ssl_verify=False)
```

But although the app is running in a remote VM and I can't reach it. I'm getting no response. But the moment I remove ssl:

```
HOST = "0.0.0.0"
PORT = 8010
demo.queue()
demo.launch(
    favicon_path=favicon_path, 
    server_name=HOST, 
    server_port=PORT,
    share=False,
```

I get a response and it works nicely. 
Appreciate any help.
