### ISSUE TITLE
Nonlinear slider?

### ISSUE THREAD

**Issue by jimmysue** [gradio-app/gradio#5673]
I want to create a slider value range from 0 to 100, but UI shows 2000 ~ 50000 to represent color temperature, which is nonliearly transform from slider value. Can you please support that? Or if there is a work around ?

- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Hi @jimmysue I think this is a bit niche to include into the core `gr.Slider` component, but we're working on making it possible for Gradio users to create their own custom components -- meaning that you'll be able to take an existing Gradio component and clone it, modify the backend or the frontend, and use it in your Gradio apps. This should hopefully help solve this use case!

**Comment by henryruhs** [comment]
@abidlabs The `steps` parameter should just take a `List[int]` next to the existing `int`. This way everyone could create their custom steps, for me this is not niche, it's a common thing todo.

**Comment by abidlabs** [comment]
Nice suggestion! Would you be interested in PR-ing this @henryruhs?

**Comment by henryruhs** [comment]
I cannot promise it, but will send a couple of PRs next months as I pause freelancing for a while and dedicate some time to OS.

**Comment by abidlabs** [comment]
I think this would be a great case for a custom component @jimmysue!

We've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
