### ISSUE TITLE
SEO tracking issue

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#579]
General goal is to improve SERP rankings.

- [x] #580
- [x] #581
- [x] #582
- [ ] #583
- [x] #584
- [x] #585
- [x] #586
- [x] #587
- [x] #575

**Comment by altryne** [comment]
Found this, so will comment instead of opening a new one

Gradio docs have very bad DX for the way I work (open tab, google something, get result, close tab) 

I can't ever search for anything specific on google, the only result is showing the main docs site. 

The main docs site is VERY poor performance wise, so one has to wait until it loads, then until it's interactive (11 seconds), then try to again search for what they already searched in google (as direct results are not showing up on google) 

![CleanShot 2022-10-07 at 11 45 51@2x](https://user-images.githubusercontent.com/463317/194618587-ccebf8c2-20dc-4f66-9d3c-65c39f51b2e9.jpg)


![CleanShot 2022-10-07 at 11 42 52@2x](https://user-images.githubusercontent.com/463317/194618121-e616dae9-794f-46cc-99c6-6da0527af4c9.jpg)

Compare with something like tailwind, searching for a feature in tailwind, shows you it's direct result in google

![CleanShot 2022-10-07 at 11 47 20@2x](https://user-images.githubusercontent.com/463317/194618819-4788c9d7-8204-49c4-a952-69961b1ff98f.jpg)

and loads immediately

![CleanShot 2022-10-07 at 11 48 43@2x](https://user-images.githubusercontent.com/463317/194619058-759ee4ac-bd61-4973-ae0c-706e2c1d6630.jpg)

**Comment by aliabd** [comment]
This is extremely useful feedback @altryne so thanks for sharing! Especially helpful that you outlined your exact workflow. You're right that our performance on docs is really bad. 

I opened these two issues to track this: https://github.com/gradio-app/gradio/issues/2416 and https://github.com/gradio-app/gradio/issues/2415 Feel free to add more feedback there, but I'll be going through this soon.
