### ISSUE TITLE
Upload / Droparea for images and videos

### ISSUE THREAD

**Issue by henryruhs** [gradio-app/gradio#5809]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**

In FaceFusion and some other roop forks, we have a **target_path** droparea that allows images and videos for later processing.

[screencast](https://github.com/gradio-app/gradio/assets/1835397/217b85a8-4aea-47c9-9456-614c4051368b)

At the moment this has been solved this way:

1. Use `gradio.File` as an entry point
1. Once a file has been uploaded `gradio.File` becomes invisible
1. The upload path will be forwarded to `gradio.Image` or `gradio.Video`   

Source: https://github.com/facefusion/facefusion/blob/master/facefusion/uis/components/target.py#L16-L44

**Describe the solution you'd like**  

The problem with the current approach: we cannot unload the temporary files for `gradio.File` - therefore the disc space and RAM is allocated twice for no good reason.

**Potential solutions**

1. Gradio could recognize temp file paths and reuse them instead of creating a fresh one
1. Forward the upload / blob to the Image or Video component
1. Unload of components (not just hiding) and related temp files
1. A `gradio.Media` component

**Additional context**  

FaceFusion stores the processed images and videos to an given path. Once done, we display this in the UI. From my observation this is causing a similar issue. A copy from the **output_path** is is stored within another temporary Gradio file.

![grafik](https://github.com/gradio-app/gradio/assets/1835397/22fec46b-8fb0-4bf6-8e26-86e6a7ee1eaf)

**Comment by abidlabs** [comment]
Hey! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. **In particular, its very fast if you want to build off an existing component**. We've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help. Hopefully this will help address this issue.
