### ISSUE TITLE
The login interface of the Chinese version is still in English. I hope it can be updated in the next version.

### ISSUE THREAD

**Issue by xxWeiDG** [gradio-app/gradio#5841]
- [x] I have searched to see if a similar issue already exists.
![image](https://github.com/gradio-app/gradio/assets/140797957/1523fb51-c704-497e-ba3c-2d76144aa908)
![image](https://github.com/gradio-app/gradio/assets/140797957/f1e011dd-2ae0-4d08-9fcf-4daef53f9d89)

The prompt part is still in English

**Comment by abidlabs** [comment]
Hi @xxWeiDG in order for us to support Chinese translation for the login page, we would need someone to contribute the Chinese language tokens for the phrases under "login" in the screenshot you provided.

It would mean editing this file: https://github.com/gradio-app/gradio/blob/46334780dbbb7e83f31971d45a7047ee156a0578/js/app/src/lang/zh-CN.json#L4, and opening a pull request so that we can merge it into Gradio.

Would you like to do that? We'd be happy to review your PR, thanks!

We don't need a specific issue for this, as we are generally open to contributions regarding language support, so I'll go ahead and close this.

**Comment by xxWeiDG** [comment]
Hi, this is my first time using github to pull a request, I already
requested it yesterday，please check it

**Comment by abidlabs** [comment]
Thanks @xxWeiDG I don't see it here: https://github.com/gradio-app/gradio/pulls -- maybe you haven't opened it yet?

**Comment by xxWeiDG** [comment]
ok I will see it later


Abubakar Abid ***@***.***>于2023年10月10日 周二11:36写道：
