### ISSUE TITLE
Lite: Queue-related features show errors

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#6001]
Samples:
```python
import gradio as gr
import numpy as np
import time

# define core fn, which returns a generator {steps} times before returning the image
def fake_diffusion(steps):
    for _ in range(steps):
        time.sleep(1)
        image = np.random.random((600, 600, 3))
        yield image
    image = np.ones((1000,1000,3), np.uint8)
    image[:] = [255, 124, 0]
    yield image


demo = gr.Interface(fake_diffusion, inputs=gr.Slider(1, 10, 3), outputs="image")

# define queue - required for generators
demo.queue()

demo.launch()
```

```python
import time
import gradio as gr

def slow_echo(message, history):
    for i in range(len(message)):
        time.sleep(0.05)
        yield "You typed: " + message[: i+1]

demo = gr.ChatInterface(slow_echo).queue()

if __name__ == "__main__":
    demo.launch()
```

**Comment by stefanengelmann** [comment]
Hi @whitphx, I just tried to run the above samples in the Gradio Playground, and they do not seem to behave as intended, i.e. there are no iterative outputs. The apps load until the loops have ended and then display the last yielded output. Is this a bug or just because the procedure for using iterative outputs in Gradio Lite has changed after Gradio 4.0?

**Comment by whitphx** [comment]
@stefanengelmann it's not a bug: `time.sleep()` is mocked as no-op on Pyodide/Gradio-Lite as https://github.com/pyodide/pyodide/issues/97.
I pasted the code above to reproduce the queue error and didn't care about the `time.sleep` problem.
