### ISSUE TITLE
Copying cell values from dataframe output

### ISSUE THREAD

**Issue by lukasugar** [gradio-app/gradio#6086]
- [x ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
It's difficult to copy cell value from output Dataframe. It's very frustrating to have to go "inspect element" to just simply copy text.

**Describe the solution you'd like**  
I'd like to either:
- have "copy" button in the corner of a cell when I hover it
- be able to copy text from cell using triple click

**Additional context**  

https://github.com/gradio-app/gradio/assets/22435018/aae0d627-2152-4660-8fde-262102c73064

**Comment by lukasugar** [comment]
Workaround: instead of using Dataframe, I'm using Markdown, and filling it with tabulated data. Works, but would be cool to support this in Dataframe :)

**Comment by abidlabs** [comment]
Hi @lukasugar which browser are you using?

**Comment by hysts** [comment]
@abidlabs I'm using Chrome and have the same issue with `gradio==3.50.2` and `gradio==4.0.2`. It was possible to copy when using `gradio==3.44.4`, for example.

**Comment by lukasugar** [comment]
I'm also using Chrome, on Mac.

**Comment by shimizust** [comment]
I'm also seeing this issue. I was able to double click a DataFrame cell to copy it in `gradio==3.44.3`, but after upgrading to `gradio==3.50.2` double-clicking does not select the cell contents. This is on Chrome on Mac/Linux.

**Comment by 1713172499** [comment]
You can try using css, and I did it:
`.cell-wrap span{
user-select:text !important;
-moz-user-select:text !important;
-webkit-user-select:text !important;
-o-user-select:text !important;
-ms-user-select:text !important;
}
`
then:
with gr.Blocks(css=css) as demo:

**Comment by one-lithe-rune** [comment]
> You can try using css, and I did it: `.cell-wrap span{ user-select:text !important; -moz-user-select:text !important; -webkit-user-select:text !important; -o-user-select:text !important; -ms-user-select:text !important; } ` then: with gr.Blocks(css=css) as demo:

This works about 50% for me. It doesn't amount to a real workaround.

If you manage to create the text selection you want without triggering gradio dataframe cell selection behavior, then you're fine. However gradio seems to use mouseup to decide when you're  selecting a cell as a whole, and doesn't seem to check whether that cell is already selected, so it always re-renders it, and because mouseup is also what you use to mark the end of a text selection, you text selection is immediately wiped out as the gradio cell selection is re-applied

If you try double or triple click, you'll see the selection of a word or the whole text in the cell quickly appear and disappear.

You have to end you text selection somewhere outside the cell you started in, to have the text selection stick, which isn't very convenient if you just want something from one cell.

This is on Firefox, on Windows 10, gradio 4.8.0

**Comment by shubhamofbce** [comment]
@abidlabs I am on it, Can you please assign this to me.
<img width="989" alt="image" src="https://github.com/gradio-app/gradio/assets/45156638/a7752186-7e21-47f9-947f-56f7ee199d3a">

**Comment by ojasvi266** [comment]
i am using version 5.39.0 and still facing this issue , can anyone please help
