### ISSUE TITLE
Please add a "keyboard_shortcut" feature to Buttons

### ISSUE THREAD

**Issue by ediweber** [gradio-app/gradio#6101]
We really need keyboard_shortcut for Buttons. Pleeeeaase implement that.

I just converted one of my projects from tkinter to gradio, but the problem is that it's impossible (?) to assign a keyboard shortcut to the Button component. (At least if I want to stick to python). IMO there should be an easy way to implement shortcuts to gradio apps.

When I decided to change to gradio I did so, because it offered the sight of being able to focus less on UI stuff and more on ML stuff.

Now I am stuck, cause my project heavily relies on keyboard shortcuts. I really wonder why such a basic thing is not yet implemented?

Gradio is great and promising, but without support for keyboard shotcuts it limits its capabilites to a great extend.

**Comment by abidlabs** [comment]
Hey! We've now made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that [allows you to write bold/italics/colored text](https://huggingface.co/spaces/abidlabs/gradio_rich_textbox)
* A "Folium Map Viewer" component that [allows you to use interactive maps](https://huggingface.co/spaces/freddyaboulton/gradio_folium)

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. If you'd like to get started, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help. Hopefully this will help address this issue.

**Comment by thiswillbeyourgithub** [comment]
For anyone wondering how to add shortcuts to components, here's a quick guide that worked for me:

```
shortcut_js = """
<script>
function shortcuts(e) {

    if (e.key == "s") {
        document.getElementById("my_btn").click();
    }
    else {
        alert(e.code);
        }
}
document.addEventListener('keyup', shortcuts, false);
</script>
"""

```

and when you declare the button:
```
with gr.Blocks(head=shortcut_js):
    sync_btn = gr.Button(value="Sync", elem_id="my_btn")
```


pinging #2670 #3279 #5223   @wiseyoungbuck

**Comment by abidlabs** [comment]
Thanks @thiswillbeyourgithub for sharing this method! I don't think we'll be adding keyboard shortcuts as an officially supported feature in `gr.Button`. While I understand the appeal, we don't want to take over user keyboard controls since Gradio apps might be embedded or shared in other environments where users do not want to lose their regular keyboard shortcuts. So I'll refer users who want to do this to this approach, and will close this issue.

Pinging @pngwn @hannahblair @aliabid94 @dawoodkhan82 -- feel free to respond / reopen if you disagree.

**Comment by thiswillbeyourgithub** [comment]
Thank you. I completely understand why you wouldn't integrate it for anyone but personnaly I think a code snippet to help the interested users would be nice in [your documentation page 'Custom CSS and JS'](https://www.gradio.app/guides/custom-CSS-and-JS).

Something as simple and basic as what I showed, just for folks unfamiliar with JS and CSS like me.

**Comment by abidlabs** [comment]
Sure, feel free to open a PR to add it there!

**Comment by thiswillbeyourgithub** [comment]
Done, the PR is at @6952

I think it deserves a mention in the CHANGELOG.md but I wasn't sure if i was supposed to do it myself or let the maintainers do it when releasing a version.

Here's the missing line just in case:
```
- [#6952](https://github.com/gradio-app/gradio/pull/6952) [`63c74e6`](https://github.com/gradio-app/gradio/pull/6952/commits/63c74e6f88b863fc5f630b5896e1d2ec11484633) - Show how to use JS to add keyboard shortcuts to any component. Thanks [@thiswillbeyourgithub](https://github.com/thiswillbeyourgithub/)!
```
