### ISSUE TITLE
Add an "add row" and "add column" event to `gr.DataFrame`

### ISSUE THREAD

**Issue by Kilig947** [gradio-app/gradio#6144]
- [ 1] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

> Is it possible to register only the new row or new column listener?
> I want to automatically give a role type to the first column when I add a new row, but the dataset only has the change method, and he triggers the change when I'm done changing the contents of the row, which is a performance concern!

**Describe the solution you'd like**  

**Additional context**  

> I would like to add an add method that is only triggered by adding a new row or a new column

```
        self.masks_dataset.change(fn=func_signals.mask_setting_role,
                                  inputs=[self.masks_dataset],
                                  outputs=[self.masks_dataset])
```
![image](https://github.com/gradio-app/gradio/assets/46100050/95c9f890-609d-44aa-91c0-3762e32bacfb)

**Comment by abidlabs** [comment]
Hi @Kilig947 thanks, yes I think we could add an event for this. If you are interested in contributing, feel free to open a PR and we can take a look!

**Comment by abidlabs** [comment]
Hi @Kilig947, after thinking about this some more, I don't think we'll add a specific event for this. We are planning on adding many more options to the Dataframe context menu, e.g. deleting rows/columns or freezing rows/columns, and it would be overkill to add events for all of these interactions. I'd suggest one of these two options:

(1) Use the `.change()` event and look at the difference between the old dataframe the and new dataframe to figure out if a new row/column has been added

(2) If you cannot do (1) due to performance reasons, I think this would be a great case for a custom component. As you may know, we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. It would be pretty easy to fork the Dataframe component and and create your own with these events, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
