### ISSUE TITLE
LaunchGradiofromSpaces Gradio HF links

### ISSUE THREAD

**Issue by AK391** [gradio-app/gradio#618]
Gradio and Huggingface Spaces links should open in a new tab when using `launchGradioFromSpaces`

example

<img width="838" alt="Screen Shot 2022-02-15 at 10 45 39 AM" src="https://user-images.githubusercontent.com/81195143/154098241-3a445e77-7f07-422e-bb5a-578563342c20.png">

Huggingface Spaces link currently does not work

**Comment by FarukOzderim** [comment]
Looking into this issue I could not understand the problem clearly, @AK391 maybe you could describe it with more detail?

**Comment by abidlabs** [comment]
What @AK391 is referring to here is that if you embed a Gradio demo using the `launchgradio()` method ([for example in this report](https://wandb.ai/akhaliq/jojogan/reports/JoJoGAN-One-Shot-Face-Stylization-with-W-B-and-Gradio---VmlldzoxNDMzNzgx)), there is a nice footer that we add underneath the embedding:

![image](https://user-images.githubusercontent.com/1778297/155318095-d41d6bf1-6929-4c79-860a-d4772e485ab4.png)

There are 3 links in that footer, and none work properly:
* The 2 hugging face Spaces link throw an error
* The Gradio link opens in the embedded frame instead of in a new tab

All of them should open up in a new tab (and the links should work!)

**Comment by AK391** [comment]
thanks @abidlabs for clarification, I also added a video here to show the issue @FarukOzderim 

https://user-images.githubusercontent.com/81195143/155344808-14dfc86b-2b5b-4787-92ec-305429783827.mov


this is using `launchgradiofromspaces`

https://github.com/gradio-app/gradio/blob/37c8ee397449a184a5528a0a1061545ee8d17566/ui/packages/app/src/main.ts#L105-L112
