### ISSUE TITLE
Scrollable gr.Image

### ISSUE THREAD

**Issue by BachHD** [gradio-app/gradio#6257]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I have a really wide image that i want to scroll through at the original size (.i.e 20000x100). However gr.Image seem to resize the image to fit the frame, which make it unviewable 

**Describe the solution you'd like**  
Maybe a parameters in the initialization

**Additional context**

**Comment by abidlabs** [comment]
Hi @BachHD would a fullscreen toggle, as described here https://github.com/gradio-app/gradio/issues/4908, work for you? I think that would be a better design than scrollable images

**Comment by BachHD** [comment]
Hi @abidlabs, the image is used as a reference to look at while the main work is done somewhere else in the GUI, also the Image is really really wide, which would not fit into any screen. So a fullscreen button sadly does not work for me. 
Here is a sample image: 
![event](https://github.com/gradio-app/gradio/assets/14168647/e4e3e3d4-22f9-4155-91b3-deedc9a63123)

I tried css=".my_long_img {overflow: scroll; object-fit: none;}". But the image just got cut off and no scroll bar appear
![image](https://github.com/gradio-app/gradio/assets/14168647/c64658ff-7878-4862-8ab1-0aeb65e5b023)

**Comment by abidlabs** [comment]
Ok, we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

	* A "Rich Textbox" that allows you to write bold/italics/colored text: https://huggingface.co/spaces/abidlabs/gradio_rich_textbox
	* A "Folium Map Viewer" component that allows you to use interactive maps: https://huggingface.co/spaces/freddyaboulton/gradio_folium

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. 

I think this could be a good use case for a custom component. If you'd like to get started, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.

**Comment by BachHD** [comment]
That seems promising. Thank you
