### ISSUE TITLE
Dependency object has no attribute launch

### ISSUE THREAD

**Issue by sanjiv-upgiant** [gradio-app/gradio#6449]
### Describe the bug

I am trying to run hugging face model and also trying the same code in local environment. However, I am getting this weird issue. 

How do I run this small app?

```
import gradio as gr

gr.Interface.load("models/ehartford/dolphin-2.2.1-mistral-7b").launch()
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Follow my steps. 

### System Info

```shell
Python => 3.9.6
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @sanjiv-upgiant, the typical approach would be to do:

```py
import gradio as gr

gr.load("models/ehartford/dolphin-2.2.1-mistral-7b").launch()
```

Note `gr.load()` instead of `gr.Interface.load()`. However, this won't work for this specific model because `gr.load` is only compatible with models that work with HF's Inference API. if you go to the model page, you'll see it says: Model is too large to load onto the free Inference API. To try the model, launch it on [Inference Endpoints] so(https://ui.endpoints.huggingface.co/new?repository=ehartford%2Fdolphin-2.2.1-mistral-7b) insteadns
