### ISSUE TITLE
Delay interface re-run with "live=True"

### ISSUE THREAD

**Issue by yesdeepakmittal** [gradio-app/gradio#645]
Please add an option to delay the re-run of an application when we use `live=True`. 

What do I want? I want to implement `live=True` into **[Using State](https://gradio.app/getting_started/#using-state)** example mentioned into documentation. Currently, if I use `live=True`, my application is re-run after entering every character. I want to give users some time so that they can successfully enter the input and then **Using State** will work.

**Comment by abidlabs** [comment]
Can you give a little more context into what kind of machine learning application you are building?

How often would you prefer it to be rerun? Every X characters?

**Comment by abidlabs** [comment]
Yup. On the Python side, `live` could take an alternative `float` value which would the amount of time after which to call the function again.

**Comment by pngwn** [comment]
I think this would probably be a good default, at least for text inputs, with a sensible value that we can figure out with a little testing. We can also make it configurable via a param as you suggested.

**Comment by abidlabs** [comment]
Hi @yesdeepakmittal, we experimented with adding a debounce, but it caused other issues with live interfaces. I don't think we'll add debounce to the components since we've found that trying to get this to work well varies significantly depending on the model and the rest of the GUI.

@pngwn feel free to reopen if you reached a different conclusion.
