### ISSUE TITLE
[ImageEditor]- allow users to drag an image to upload (maybe also click)

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#6503]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by abidlabs** [comment]
Btw I think this issue is even more important now because the upload button is tucked within a row of other buttons and its not super obvious what to click to start uploading an image:

<img width="779" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/a9ee0b5e-7b8f-49ac-9ff6-35e128e02c30">

**Comment by lllyasviel** [comment]
hi this needs higher priority and is blocking sd-webui's adopting of gradio 4
i tried a bit js hacking - but - is there any js way to hack this? it seems the image editors' internal  js vars are very complicated and not easy to hack

**Comment by pngwn** [comment]
I doubt this is possible to hack without breaking the image editor, if it is possible at all. 

I'll probably take this on next week.

**Comment by lllyasviel** [comment]
beep beep

**Comment by lllyasviel** [comment]
@pngwn beep beep

**Comment by pngwn** [comment]
@lllyasviel peeb peeb

**Comment by pngwn** [comment]
Also, PR here: https://github.com/gradio-app/gradio/pull/8803
