### ISSUE TITLE
Document that loading spaces with Blocks does not load css

### ISSUE THREAD

**Issue by vitaliy-sharandin** [gradio-app/gradio#6626]
### Describe the bug

While using `gradio.load()` to load another space, everything is loaded correctly, yet css is not loaded together with the rest of the code. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Spaces to be loaded
```python
with gr.Blocks(theme=gr.themes.Soft(), css=".column-frame {border: 2px solid #AAA;border-radius: 10px;padding: 10px;margin: 10px;}") as demo:
```

### Screenshot

**Original space**
![image](https://github.com/gradio-app/gradio/assets/14151437/7fb8cd5b-9bc1-43ac-b25e-a2fc48bd5f2e)

**Loaded space**
![image](https://github.com/gradio-app/gradio/assets/14151437/ae24fb27-b408-4916-b35c-013dcbe15250)

### System Info

```shell
- gradio 4.7.1
- HF Spaces
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @vitaliy-sharandin, this is actually the intentional behavior. The high-level `Blocks()` parameters are not loaded when you use `gr.load` -- only the internal components. 

If you'd like to add custom css, you can do something like this:

```py
with gr.Blocks(css=css) as demo:
    gr.load(...)

demo.launch()
```

This isn't documented very well, so I'll relabel this issue.
