### ISSUE TITLE
Need absolute path pickup component

### ISSUE THREAD

**Issue by LittleApple-fp16** [gradio-app/gradio#6661]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Nothing can do this in gradio, now

**Describe the solution you'd like**  
Drag a folder to the new component i want, it will output the abs path

**Additional context**  
You can see this post: https://stackoverflow.com/questions/75842180/how-can-i-convert-this-gradio-file-upload-code-into-folder-path-taking-one

**Comment by abidlabs** [comment]
Hi @LittleApple-fp16 this is actually not possible since browsers run in a sandboxed environment where they cannot access a user's local file system except for files that are explicitly uploaded. 

You could take a look at the `gr.FileExplorer` component, which allows a developer to surface the filesystem where a Gradio app is _running_ (and you can select directories and get the absolute path), but it is not possible to get absolute paths from Gradio users's machines.
