### ISSUE TITLE
Using gr.HTML() How to locate tag attributes in HTML when creating a navigation bar?

### ISSUE THREAD

**Issue by naonao-beibei** [gradio-app/gradio#6802]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

**Comment by naonao-beibei** [comment]
I use HTML to create a navigation bar that includes a dropdown menu. When clicking on a submenu in the dropdown menu, an event needs to be triggered to redirect to the page. Now, I use gr.HTML () can load navigation bars. How can I complete the following operations?

**Comment by abidlabs** [comment]
Hi @naonao-beibei this is not possible using the `gr.HTML()` component, which is just designed to display HTML as output. Its not meant for these kinds of interactive use cases. 

One thing you could try -- we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

	* A "Rich Textbox" that allows you to write bold/italics/colored text: https://huggingface.co/spaces/abidlabs/gradio_rich_textbox
	* A "Folium Map Viewer" component that allows you to use interactive maps: https://huggingface.co/spaces/freddyaboulton/gradio_folium

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. If you'd like to build a "Navbar" custom component, you could start with this Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.

**Comment by naonao-beibei** [comment]
> Hi @naonao-beibei this is not possible using the `gr.HTML()` component, which is just designed to display HTML as output. Its not meant for these kinds of interactive use cases.
> 
> One thing you could try -- we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:
> 
> * A "Rich Textbox" that allows you to write bold/italics/colored text: https://huggingface.co/spaces/abidlabs/gradio_rich_textbox
> * A "Folium Map Viewer" component that allows you to use interactive maps: https://huggingface.co/spaces/freddyaboulton/gradio_folium
> 
> You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. If you'd like to build a "Navbar" custom component, you could start with this Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.


Thank you very much for your reply！
