### ISSUE TITLE
`text-align: center:` doesn't work for `gr.Markdown` when using `gradio==4.11.0`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#6849]
### Describe the bug

It was working fine when using `gradio==4.10.0`, but now it's not working.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/hysts-debug/gradio-markdown-css-text-align-center

```python
import gradio as gr

css = """
h1 {
    text-align: center;
}
"""

with gr.Blocks(css=css) as demo:
    gr.Markdown("# title")

if __name__ == "__main__":
    demo.queue().launch()

```

### System Info

```shell
gradio==4.11.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @hysts you can fix this by adding `display: block` to the css, e.g:

```py
import gradio as gr

css = """
h1 {
    text-align: center;
    display:block;
}
"""

with gr.Blocks(css=css) as demo:
    gr.Markdown("# title")

if __name__ == "__main__":
    demo.queue().launch()

```

It looks like we might have changed the Markdown container from `<p>` to a `<span>` which affected this change. Since we don't guarantee consistency of the HTML elements across versions, I don't think this is an actual regression actually (despite my application of the label), and I think we can close this.

**Comment by hysts** [comment]
Oh, I see. I understand. Thanks for the answer! I'll close this.
