### ISSUE TITLE
Show additional message in gr.Chatbot 

### ISSUE THREAD

**Issue by Rogerspy** [gradio-app/gradio#6860]
like which in red box:
<img width="578" alt="image" src="https://github.com/gradio-app/gradio/assets/26625102/59e6f17e-aad2-4288-97ab-dba6136799df">

**Comment by abidlabs** [comment]
Hi @Rogerspy I'm not sure what the purpose of those messages is. Are they clickable responses or something else? Please provide more details on this feature request, thank you!

**Comment by Rogerspy** [comment]
> Hi @Rogerspy I'm not sure what the purpose of those messages is. Are they clickable responses or something else? Please provide more details on this feature request, thank you!
@abidlabs Thank you for the reply. They are not clickable, just for display like user or bot message. I call those system message. Specifically, I want `gr.Chatbot` to render `history: [user_message, bot_message, system_message]` , which the css style of `system_message` like those in red box.

**Comment by abidlabs** [comment]
Hmm I don't think this is possible and it would be too niche for us to include in the `gr.Chatbot` component. Instead, I'd suggest perhaps using `gr.Markdown` above or below the chatbot to display this image. And then you could use custom css to style this message including adding a red border: https://www.gradio.app/guides/custom-CSS-and-JS

**Comment by Rogerspy** [comment]
> Hmm I don't think this is possible and it would be too niche for us to include in the `gr.Chatbot` component. Instead, I'd suggest perhaps using `gr.Markdown` above or below the chatbot to display this image. And then you could use custom css to style this message including adding a red border: https://www.gradio.app/guides/custom-CSS-and-JS

@abidlabs   Maybe I wasn't clear. Let me show you the code:
```python
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.ClearButton([msg, chatbot])

    def respond(message, chat_history):
        system_message = random.choice(['This is system_message1', 'This is system_message2'])  # generate system message
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        chat_history.append((message, system_message, bot_message))  # append system_message to chat_history
        time.sleep(2)
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])

if __name__ == "__main__":
    demo.launch()
```
The `chat_history` contains three items instead of two, where `system_message` is also a string (also `None` or empty string `''`) instead of a image. And the css style of `system_message` is, for example:
```css
.system_message{
        font-size: 10px;
        color: #a2b0a2;
        font-family: Arial;
        padding: 0px 0px 0px 60px;
    }
```

The red border was drawn by me, just to attract your attention, and does not require css rendering. 

<img width="741" alt="image" src="https://github.com/gradio-app/gradio/assets/26625102/91320836-b17e-4c7b-a84e-5ab08605372a">

**Comment by abidlabs** [comment]
Yes, makes sense. I don't think we'd include this in the core `Chatbot` component, but we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. Here are some examples of custom Gradio components:

* A "Rich Textbox" that allows you to write bold/italics/colored text: https://huggingface.co/spaces/abidlabs/gradio_rich_textbox
* A "Folium Map Viewer" component that allows you to use interactive maps: https://huggingface.co/spaces/freddyaboulton/gradio_folium

You can see the source code for those components by clicking the "Files" icon and then clicking "src". The complete source code for the backend and frontend is visible. You can also clone existing components, e.g. if you want to make a variant of the `Chatbot` component. If you'd like to get started, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
