### ISSUE TITLE
Disable this mobile warning

### ISSUE THREAD

**Issue by IvanaXu** [gradio-app/gradio#6928]
Very nice @aliabid94! Can confirm that I see this warning modal when I initiate the job:

![image](https://github.com/gradio-app/gradio/assets/1778297/1b55b591-f436-4e9e-a224-329b19c4acb3)

(though only with queuing enabled, which I think is fine)

And I see this when I switch tabs. (Btw on my iPhone, I only see this if I set it to low power mode, otherwise the connection doesn't break):

![image](https://github.com/gradio-app/gradio/assets/1778297/8cd78a71-8a52-4956-b526-033233c48ff8)

_Originally posted by @abidlabs in https://github.com/gradio-app/gradio/issues/4742#issuecomment-1624349691_

**Comment by Siddharth1605** [comment]
@abidlabs can you assign this issue to me

**Comment by abidlabs** [comment]
We don't assign issues to contributors formally, but feel free to open a PR!

**Comment by abidlabs** [comment]
@hannahblair I think the context for this issue is that there was a request for a  way to disable this warning and error that appear on mobile. After thinking about this some more, I think this is a relatively niche use case and removing these warnings may degrade the user experience for mobile users, so I don't think we should include it in the official python api. 

That being said, I would confirm that this only appears the first time a user runs a prediction, as it would be annoying to see this message appear again and again every time you interact with the gradio app

**Comment by freddyaboulton** [comment]
Will close as this is very niche and the warning only shows up once. Just verified
