### ISSUE TITLE
Exe packaging issue

### ISSUE THREAD

**Issue by 80381220** [gradio-app/gradio#6954]
### Describe the bug

The program code runs normally, but after being packaged as exe, it crashes

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

We used the official column code provided by the authorities

### System Info

```shell
It's the latest
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @80381220 there aren't enough details here. What's the gradio app? How did you package it as an exe?

**Comment by 80381220** [comment]
I am using Python 3.9, and the code is the official example of Studio. The code is as follows:

import gradio as gr

def greet(name, intensity):
    return "Hello " * intensity + name + "!"

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch()

The code runs normally, but with pyinstaller \Main. py is packaged as an exe program, and running the packaged exe program crashes.
Thank you for answering my question. What other records do I need to provide? thanks

**Comment by abidlabs** [comment]
Thanks for responding @80381220. It sounds then that this is an issue with pyinstaller, since the Gradio app is working fine as a standalone python program. We don't have official support for packaging into exe files, but it looks like pyinstaller should be able to convert arbitrary python programs into exe files, and its failing for this program. I would suggest opening an issue on the pyinstaller repo: https://github.com/pyinstaller/pyinstaller/issues

**Comment by abidlabs** [comment]
Please feel free to follow https://github.com/gradio-app/gradio/issues/2257 for an officially supported way to build desktop apps with Gradio
