### ISSUE TITLE
Error Showing :  Unexpected token '<', " <!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by SameerSector6** [gradio-app/gradio#7027]
### Describe the bug

Whenever I go to advanced options there is an error message showing after 10-12 seconds.

And the error message is :

Unexpected token '<', " <!DOCTYPE "... is not valid JSON

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

Unexpected token '<', " <!DOCTYPE "... is not valid JSON

### System Info

```shell
Yes, I am using latest version of Gradio.
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @SameerSector6 !

I don't know what you mean by this:

> Whenever I go to advanced options there is an error message showing after 10-12 seconds.

Can you share a minimal reproducible example? Thanks

**Comment by mayank64ce** [comment]
I am also facing this bug .. 
![image](https://github.com/gradio-app/gradio/assets/43180708/ed8c499c-97b4-41d8-8164-ac405a5683ef)

**Comment by abidlabs** [comment]
@mayank64ce sounds like you are facing this with a specific Gradio demo, perhaps on Hugging Face Spaces, is that the case? If so, I'd suggest raising an issue/discussion on that specific Space. Otherwise, please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

Closing for now
