### ISSUE TITLE
Have a icon= param for gr.Accordion

### ISSUE THREAD

**Issue by dwipper** [gradio-app/gradio#7173]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
The UI presentation of the gr.Accordion component is limited since it doesn't have a icon= override like gr.Button.

**Describe the solution you'd like**  
Instead of the standard "label text + arrow" UI, similar to gr.Button, have a icon= param for gr.Accordion so that something like a "Hamburger" icon could be used for a more modern UI. 
![image](https://github.com/gradio-app/gradio/assets/140648761/d5e33f62-13db-47de-bb08-0477ffa38024)

**Additional context**

**Comment by abidlabs** [comment]
I think this would be a great case for a custom component!

we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image. But you can also create custom components from Layouts (in this case you could use the original `gr.Accordion` as a template)

If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.

**Comment by dwipper** [comment]
@abidlabs Thanks. I've read about the custom components.....it's just that I don't have the depth of programming skills at this point to do that. Hopefully someone will pick it up🤞

**Comment by abidlabs** [comment]
Sounds good, I'll go ahead and close this for now
