### ISSUE TITLE
Image/Video controls does not work with camera (green screen)

### ISSUE THREAD

**Issue by sqbiak** [gradio-app/gradio#7300]
### Describe the bug

This does not: https://www.gradio.app/docs/video 

This works 100%: https://huggingface.co/spaces/multimodalart/stable-video-diffusion 

it does not produce any errors. It also does not work with virtual camera from OBS. 

I am sure it is my OS/hardware but WHAT? 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Screenshot

My local PC:![image](https://github.com/gradio-app/gradio/assets/84133037/92276fc5-1b7e-47c7-9ab4-f932f61b29cb)
the text says "unity has not started sending image data"

### System Info

```shell
Windows 11 - chrome, edge, firefox...

gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.25.1
huggingface-hub: 0.20.3
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
