### ISSUE TITLE
[Blocks] String shortcuts for components

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#731]
Can we support string shortcuts for components like in `Interface`? 

shortcuts like "sketchpad" save from having to define 4 parameters (`gr.inputs.Image(image_mode='L', source="canvas", shape=(28, 28), invert_colors=True)`)

Not currently supported in blocks.

**Comment by FarukOzderim** [comment]
I think using strings for components names are not legit and hacky.
We can have these pre-prepared components in a class and import from there.

```python
from gradio.components.Templates import Sketchpad
inputs = [Sketchpad]
```
or
```python
from gradio import Templates
inputs = [Templates.Sketchpad]
```

**Comment by abidlabs** [comment]
String identifiers are  pretty common practice in parameters the way we have them in `inputs` and `outputs`. For example, see https://keras.io/api/optimizers/ (`"adam"` and `Adam()` both work). I actually think they are part of the convenience of high level APIs like Keras and Gradio.

That being said, they are not very convenient in the Blocks context, since you can't just have a string by itself the way you could have a Class being instantiated. I think the approach you are suggesting @FarukOzderim make sense to me. I would prefer the last one, if possible, so that all of the components live in the same namespace. I think there is a small typo and it should read:

```python
from gradio.component import Sketchpad
inputs = Sketchpad()
```

The only I don't love is having to import from a separate module

**Comment by FarukOzderim** [comment]
About this issue let's give the final decision

- for blocks we want to have Template components that are implemented by us. 
- What about Interface? Would you want to drop support shortcuts within Interface and move to Templates usage as well? Or still support shortcuts within Interface?

**Comment by abidlabs** [comment]
> for blocks we want to have Template components that are implemented by us.

To clarify, how would this work? Would it be that we pass in `Template("sketchpad")` and it renders the `Image` component with the "sketchpad" parameters? If so, that seems reasonable to me.

> What about Interface? Would you want to drop support shortcuts within Interface and move to Templates usage as well? Or still support shortcuts within Interface?

We should still support shortcuts within Interface: (a) because they make Interface easy to use for common use cases (b) backwards compatibility

**Comment by FarukOzderim** [comment]
Ok then;

- We will still support shortcuts within interface.
- We will create custom components with necessary parameters and etc for the shortcuts and they will work like this:
```
from gradio import Sketchpad
inputs = Sketchpad()
```

**Comment by abidlabs** [comment]
Ah okay, got it! So `Sketchpad` will subclass `Image`, right? Sounds good to me.

cc @aliabid94

**Comment by aliabid94** [comment]
Yep I like @FarukOzderim suggestion

**Comment by abidlabs** [comment]
>To distinguish real components and Custom or Template components I want to create a hierarchy and import mechanism like this, WDYT? The size of custom components can increase a lot in the future, we can even accept custom components from community.

Sounds good to me. I prefer `Templates` as it is shorter than `CustomComponents` and a single word

**Comment by FarukOzderim** [comment]
@abidlabs @aliabd 
Would we want to have templates for these shortcuts?

```
  Dataframe
{
            "dataframe": {"type": "pandas"},
            "numpy": {"type": "numpy"},
            "matrix": {"type": "array"},
            "list": {"type": "array", "col_count": 1},
        }
```

**Comment by abidlabs** [comment]
I think we should. Not sure how commonly they are used, but there should be no harm in including them.
