### ISSUE TITLE
Order of files selected while uploading cannot be maintained with gr.File(interactive=True)

### ISSUE THREAD

**Issue by schoudhary101** [gradio-app/gradio#7314]
- [x] I have searched to see if a similar issue already exists.

When doing multiple files upload at once, the order of the files are in ascending order of name while it cannot be in the order the user selects.
Hope this can be implemented.
 
If not possible, then in the UI, the user should be able to rearrange the order of files.

**Comment by abidlabs** [comment]
Hi @schoudhary101 I think this would be a great case for a custom component!

we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image. 

You could do something similar here and create a custom `OrderedFile` gradio custom component templating off of the `File` component

If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.

**Comment by abidlabs** [comment]
I'll go ahead and close this issue for now
