### ISSUE TITLE
Add analytics for custom components workflow

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#7330]
It'd be great to have some analytics for how many people are running each step of the custom component workflow along with some basic metadata:
* `create`
* `dev`
* `build`
* `publish`

**Comment by pngwn** [comment]
I'm not a huge fan of this personally but i'll let others chime in.

**Comment by freddyaboulton** [comment]
I think this will help us keep track of growth in the custom components workflow so I'm for it. I don't think we need separate analytics for dev because that usage is already tracked in our current analytics since we're launching a regular gradio blocks - maybe we just need a flag in the analytics metadata.
