### ISSUE TITLE
gradio_client update broken so many Gradio apps

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#7339]
gradio_client version 0.0.9 broken kohya and automatic1111 gradio apps

i dont know which other apps are also broken

the error is 

![image](https://github.com/gradio-app/gradio/assets/19240467/5d993dc9-6d5d-4dd7-8ce4-90d09ab8ad52)

0.8.1 working just fine

for maintained repositories this should get fixed but for not maintained repositories this will cause some errors

**Comment by daszzzpg** [comment]
Same, stucked here
Who did this?
Completely unable to achieve a correct install.

**Comment by freddyaboulton** [comment]
Hi @FurkanGozukara ! We pin the version of the gradio client in gradio's requirements.txt so that only one version of the client is compatible with a given version of gradio. If you update the client without updating errors, you will probably get an error. The problem is that pip will install a conflicting version an only give you an error.

The only version of gradio that is compatible with version 0.9.0 of the client is 4.17.0. So if you're using version 0.9.0 of the client, you have to use 4.17.0 of gradio!

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara ! We pin the version of the gradio client in gradio's requirements.txt so that only one version of the client is compatible with a given version of gradio. If you update the client without updating errors, you will probably get an error. The problem is that pip will install a conflicting version an only give you an error.
> 
> The only version of gradio that is compatible with version 0.9.0 of the client is 4.17.0. So if you're using version 0.9.0 of the client, you have to use 4.17.0 of gradio!

the issue is people uses certain gradio but they did left gradio_client as default thus installs latest version. can't this be resolved automatically? i mean if gradio version is certain cant you make pip to install only compatible version of gradio_client ?

**Comment by freddyaboulton** [comment]
I think this issue only happens if you already have a version of gradio installed and you manually update the client. You get an error like this but the version you ask for will still get installed.

<img width="604" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/907024da-d43c-4873-beb0-5cc963fea75b">

Unfortunately it's a limitation of pip and there's nothing we can do about it beyond pinning the version of the client like we do now.

**Comment by Arkadiusz-87** [comment]
Hey, I had a similar issue when trying to run "kohya_ss" in "StabilityMatrix". The installation went smoothly, but when I tried to launch it, I got the error message you can see in the screenshot below. I managed to fix it by simply copying and replacing the entire "gradio_client" folder from "Stable Diffusion WebUI"

![scren](https://github.com/gradio-app/gradio/assets/102323849/c8f0782a-c8f0-42e3-8619-f151a8915626)
