### ISSUE TITLE
Share Breaks In Spaces

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#734]
### Describe the bug

share=True usage in launch gives error in spaces

### Reproduction

https://huggingface.co/spaces/ruhwang2001/wonder-app/blob/main/app.py

`interface.launch(debug=True, share=True)`

### Logs

```shell
Running on local URL:  http://localhost:7860/
█
*** Failed to connect to ec2.gradio.app:22: [Errno 110] Connection timed out
```

### System Info

```shell
Spaces
```

### Severity

critical

**Comment by abidlabs** [comment]
That makes sense. We can coordinate with the Spaces team to set up that environmental variable. 

My suggestion would be that if this environmental variable is set *and share=True*, then we print a helpful warning to the user saying that for Spaces, `share` should be set to `False`. 

(Instead of overriding `share` as I don't think we should override an explicit parameter with an implicit environmental variable)

**Comment by FarukOzderim** [comment]
Gonna make us of these env variables for this issue:

https://github.com/huggingface/spaces-app-manager/blob/main/dockerfiles/cpu/Dockerfile#L45

**Comment by FarukOzderim** [comment]
@aliabid94 @abidlabs I fixed this issue with #739 and testing it on 

https://huggingface.co/spaces/farukozderim/bug_test_1

However I am not getting an error and the error message, 🤔

**Comment by FarukOzderim** [comment]
Oh the error came now, it was working nice and cool at the start :D

**Comment by FarukOzderim** [comment]
Well we did not get a release, of course it will not be fixed 🤭 

Will test it with the next release.

**Comment by FarukOzderim** [comment]
tested and it works as expected 💪 

https://huggingface.co/spaces/farukozderim/bug_test_1
