### ISSUE TITLE
Document that `gr.EventData` can be used with any event

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [gradio-app/gradio#7380]
### Describe the bug

As described [in another issue](https://github.com/gradio-app/gradio/issues/6278#issuecomment-1937018835)

I have several buttons in my app. By default I want them to be invisible except for the first one. Clicking on the first one called "Load buttons" should update the properties of the other buttons to change their names and make them visible.
The event of all those buttons is the same function. In this function I have `evt: gr.EventData` as arg to know which button was clicked as that has an influence on what the function will do.

When doing this I noticed that although the buttons now were visible and with the right name, evt still returned their old names.

Here's another way I explained it:

> In my example I have a button B that called function f.
Before f is called, B has value "UNDEFINED".
As soon as f is called: it returns gr.update(value="name") direclty to B.
So far so good: for the user the text appearing on B is now "name" after clicking.
But when clicking again on B, f now checks evt.target.value to see the name of the button that called it. I expected the value to be "name" but it was instead "UNDEFINED".
I ended up working around it by setting elem_id of my buttons so that I can keep track of what button called no matter their name but still this is a bug.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def f(evt: gr.EventData, btn1, btn2):
    print(f"Name of the button clicked: {evt.target.value}")
    print(f"Actual name of the buttons: {btn1}, {btn2}")
    btn1 = gr.update(value="0")
    btn2 = gr.update(value="1")
    return [btn1, btn2]

with gr.Blocks() as demo:
    b1 = gr.Button(value="Undefined 1", elem_id="Undefined 1")
    b2 = gr.Button(value="Undefined 2", elem_id="Undefined 2")

    b1.click(fn=f, inputs=[b1, b2], outputs=[b1, b2])
    b2.click(fn=f, inputs=[b1, b2], outputs=[b1, b2])

demo.launch(inbrowser=True)
```

### System Info

```shell
gradio==4.18.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @thiswillbeyourgithub this issue is not really clear to me. The `gr.Button()` does not have any officially supported event that includes EventData. The `gr.Button` component's only supported event is `.click()` which carries the current value of the buttons. But it does not have any event like `.select()` which carries `EventData`. Passing in an argument of type `EventData` may do something but its not officially supported so the behavior is unpredictable. 

The right way to do this would be to pass in the buttons as inputs themselves, which should carry the latest value of the buttons as your code example shows. It looks like that works correctly -- is there something that you're not able to do?

**Comment by thiswillbeyourgithub** [comment]
Thanks for the quick response. I'll answer point by point.

First regarding EventData:
I expected **Event**Data to work with any **event**. It's not clear to me why `.select()` and not `.click()` would have this support. I mean I understand that the most obvious use of EventData is for select components but my case does not sound too far fetched to me.

Regarding my use case:
If I pass the value of the buttons as input to f then indeed in f I can see the up to date name of the buttons. **But in my case I need to also know which button was pressed to call f and the only way I found was to use EventData** so:
1. If there is a proper way I think the docs didn't make it clear.
2. EventData does not look aptly named if it's only about some events.
3. If the end goal is to support all events by EventData then raising a warning for those not yet implemented like `.click()` seems relevant.
4. If not then raising an exception when an unexpected event is used rather than doing something unpredictable seems sensical.
5. To reiterate : the current state where I was using with no errors nor warnings EventData on an event that is not supported to then return a gr.update that alters the appearance (UI) but not some "deeper" level of the component smells to me like many bugs could come from that area and some guardrails might be worth thinking about.

To clarify, I'm absolutely in love with gradio and don't wan't to sound like I don't!

**Comment by abidlabs** [comment]
Thanks @thiswillbeyourgithub that makes sense, let us think about this a bit more and come up with a good solution

**Comment by abidlabs** [comment]
Hi @thiswillbeyourgithub I've been thinking about this for a bit, but there's not really a good solution for this. Basically, the problem is that if you directly access the attributes of a component (e.g. .value or .lines), you will get the **initial** value of that attribute. This is what is defined in the backend and this does not change. We couldn't change it because these component objects are shared across *all* users of an app (since there's only one backend serving many different users). This is why we never suggest users accessing attributes of a component directly.

When you return a `gr.update()`, what happens is that we actually create a *copy* of a component and store it a dictionary that is keyed by your browser session ID. This component is used and updated as needed. I think creating an API to expose it would be adding an unnecessary level of complexity given the rare use case.

My recommendation would be to stick with the approach of assigning an `elem_id` to the buttons and using that to figure out which one has been clicked. You could also look at the `._id` attribute of the component.

**Comment by thiswillbeyourgithub** [comment]
Hi. Thank you very much for taking the time to explain.

I understand now that you have good reasons for that and I no longer think it would be a good idea to change this.

Just a few things left to adress if you don't mind:
- What about making sure that EventData supports all events? Or renaming it to avoid confusion?
- What about raising warnings/exception when EventData is called on events by components that souldn't implement it like `btn.click`?

PS: Also hats off to gradio because it means that the library did a few things *right* if I managed to implement my weird usecase using elem_id and stuff without all hell breaking loose :)

**Comment by abidlabs** [comment]
Thanks @thiswillbeyourgithub. From my quick experiments, it sounds like every event and every component supports `gr.EventData` -- is that not what you're seeing? E.g. `btn.click` implements it:

```py
import gradio as gr

def test(evt: gr.EventData):
    return str(evt.target)
    

with gr.Blocks() as demo:
    b = gr.Button()
    t = gr.Textbox()
    
    b.click(test, None, t)
    
demo.launch()
```

Or do you mean we should document it?

**Comment by thiswillbeyourgithub** [comment]
Indeed it worked but you told me this was unpredictable:

> The gr.Button() does not have any officially supported event that includes EventData. The gr.Button component's only supported event is .click() which carries the current value of the buttons. But it does not have any event like .select() which carries EventData. Passing in an argument of type EventData may do something but its not officially supported so the behavior is unpredictable.

**Comment by abidlabs** [comment]
Yes you're right, its unofficial / undocumented. So let me reopen this issue but reframe it around documenting `gr.EventData`

**Comment by ichabodcole** [comment]
+1 for better documentation regarding EventData. 

I got very confused by the current documentation and in my reading it seemed as if all events have their own event data type (e.g. gr.SliderEvent, etc), not just select and keyup. I then thought I needed to create a custom subclass of EventData, which went nowhere :D.  Finally, figured out I can just use gr.EventData with any event, though also hit the same, stuff doesn't update issue. 
Would be great to clear this up with some examples of other event types using this data in the docs and the limitations of the property updates. 
Admittedly, I am using this to deal with a dynamic list of components situation and using the elem_id to figure out what has been clicked, but figuring out I had access to EventData saved my bacon :D.
