### ISSUE TITLE
Gradio Iframe

### ISSUE THREAD

**Issue by camillevingere** [gradio-app/gradio#740]
### Describe the bug

When we flag from a gradio interface using Iframe, the api is not working (500 error)

### Reproduction

<link rel="stylesheet" href="https://gradio.s3-us-west-2.amazonaws.com/2.6.2/static/bundle.css">
<div id="manga-anime-demo"></div>
<script src="https://gradio.s3-us-west-2.amazonaws.com/2.6.2/static/bundle.js"></script>
<script>
launchGradioFromSpaces("temp-late/manga-anime", "#manga-anime-demo")
</script>

### Screenshot

![image](https://user-images.githubusercontent.com/49264781/155696900-b3ff938f-31a6-424b-8583-60673663e1af.png)

### Logs

```shell
Access to fetch at 'https://huggingface.co/gradioiframe/temp-late/manga-anime/+/api/flag/' from origin 'https://temp-late.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
bundle.js:2236          POST https://huggingface.co/gradioiframe/temp-late/manga-anime/+/api/flag/ net::ERR_FAILED 500
(anonyme) @ bundle.js:2236
c @ bundle.js:53
(anonyme) @ bundle.js:53
(anonyme) @ bundle.js:53
l @ bundle.js:2224
a @ bundle.js:2224
(anonyme) @ bundle.js:2224
(anonyme) @ bundle.js:2224
(anonyme) @ bundle.js:2236
(anonyme) @ bundle.js:2236
c @ bundle.js:53
(anonyme) @ bundle.js:53
(anonyme) @ bundle.js:53
l @ bundle.js:2224
a @ bundle.js:2224
(anonyme) @ bundle.js:2224
(anonyme) @ bundle.js:2224
(anonyme) @ bundle.js:2236
r.flag @ bundle.js:2236
Qe @ bundle.js:69
Ye @ bundle.js:69
(anonyme) @ bundle.js:69
_i @ bundle.js:69
ji @ bundle.js:69
(anonyme) @ bundle.js:69
Ie @ bundle.js:69
(anonyme) @ bundle.js:69
Si @ bundle.js:69
Zt @ bundle.js:69
Jt @ bundle.js:69
t.unstable_runWithPriority @ bundle.js:77
Rr @ bundle.js:69
Fe @ bundle.js:69
Gt @ bundle.js:69
Afficher 4 autres frames
bundle.js:2236                  Uncaught (in promise) TypeError: Failed to fetch
    at bundle.js:2236:220334
    at c (bundle.js:53:45184)
    at Generator._invoke (bundle.js:53:44937)
    at Generator.next (bundle.js:53:45543)
    at l (bundle.js:2224:85430)
    at a (bundle.js:2224:85633)
    at bundle.js:2224:85692
    at new Promise (<anonymous>)
    at bundle.js:2224:85573
    at bundle.js:2236:220543
```

### System Info

```shell
Latest gradio
```

### Severity

annoyance

**Comment by abidlabs** [comment]
@aliabid94 is this something you can look into?

**Comment by abidlabs** [comment]
Hi @camillevingere there were a couple of issues related to flagging with iframes. The first was a CORS permissions issue, which has been fixed in the latest version of Gradio. You can upgrade your Space to the latest version of Gradio by restarting the Space by going to the settings for your repo:

![image](https://user-images.githubusercontent.com/1778297/165196505-591b9fff-667f-4a3b-bf81-5581dc1ccdf5.png)

For example, you can confirm that this Space flags data: https://huggingface.co/spaces/abidlabs/flagging-tester 

However, you might still not see the behavior that you expect when you try flagging your data. And the reason for that is that the flagged data is saved locally on the Space machine, but is not pushed to the Space repo. I discussed the issue here and described the solution: #914 

Closing this issue, please follow that issue for updates, or feel free to ask any clarification questions.

Thank you!
