### ISSUE TITLE
Unnecessary progress / component flicker when component is not actually being updated

### ISSUE THREAD

**Issue by JohnDuncanScott** [gradio-app/gradio#7494]
### Describe the bug

Handlers can output using a dictionary containing only the outputs that should be updated. If an output is not updated, that output component should not show progress bars or render flicker since no value is being updated.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

The below is a cutdown working example. Type a bunch of characters into the textbox and note how the chatbot component shows progress indication even though the dictionary being returned does not contain any updates for it. The progress is super distracting. You could toggle this off in the event handler, but then you'd want it in other scenarios (i.e. the progress is important IF the component is being updated, otherwise it's just UI noise). The user shouldn't need to tweak this, this seems like a fairly straightforward optimisation task I think. There doesn't seem to an obvious workaround. Have tried returning empty dict, None, the original history, etc.. Everything always causes a progress update.

```python
import gradio as gr

with gr.Blocks() as model_test_harness:
    # region Components - rendered
    chatbot_component = gr.Chatbot(height=300, bubble_full_width=False)
    chat_input_textbox = gr.Textbox(container=False, scale=7)
    # endregion

    def handler_chat_input_textbox_input(input: str, history):
        return {}

    # endregion

    # region Event handler setup
    chat_input_textbox.input(
        handler_chat_input_textbox_input,
        inputs=[chat_input_textbox, chatbot_component],
        outputs=[
            chatbot_component,
        ],
    )
    # endregion

model_test_harness.launch()
```

### System Info

```shell
Windows 11
4.19.1
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @JohnDuncanScott this is actually not very straightforward as the user's function could be arbitrarily complex and different branches of the code could be executed, updating different components depending on the input values or other conditions. So generally speaking, its not possible to know ahead of time which output components are actually updated and which are not updated from a function. 

As a developer, if you do know ahead of time, you can set `show_progress="hidden"` on a particular event to hide the progress updates for that component. And if you want to do something more complex (i.e. show progress only if certain conditions are met), you could chain events and only call subsequent events if earlier events are successful (this is not a perfect workaround since it requires raising an error but at least it won't be visible to your end users). Here's an example based on yours:

```py
import gradio as gr

with gr.Blocks() as model_test_harness:
    # region Components - rendered
    chatbot_component = gr.Chatbot(height=300, bubble_full_width=False)
    chat_input_textbox = gr.Textbox(container=False, scale=7)
    # endregion

    def handler_chat_input_textbox_input(input: str, history):
        return {}
    
    def terminate_if_short(input: str):
        if len(input) < 5:
            raise ValueError("Too Short")

    # endregion

    # region Event handler setup
    chat_input_textbox.input(
        terminate_if_short,
        inputs=[chat_input_textbox],
        show_progress="hidden"
        ).success(    
        handler_chat_input_textbox_input,
        inputs=[chat_input_textbox, chatbot_component],
        outputs=[
            chatbot_component,
        ],
    )
    # endregion

model_test_harness.launch()
```

**Comment by JohnDuncanScott** [comment]
Ah that's very helpful, thanks. The event chaining seems good enough to work around, appreciate it.

**Comment by Onturenio** [comment]
Hi, @abidlabs I'm coming from [here](https://github.com/gradio-app/gradio/issues/7479#issuecomment-1955773209).

I'm trying to implement this workaround, but I'm concerned with the (sort of) unhandled exception. Actually, I don't fully understand what's happening when you raise the exception within the `gr.Blocks` environment. I have tried to catch the exception, but it still outputs the text with the Traceback. I don't want to have this in the output, as it seems to mess the log of the application.

Actually, when you raise the exception, the normal execution flow would be that the `success` function is not executed at all, but the execution should just jump to the `except` construct. But of course the whole point of the `success` method is that this is not expected to happen... I'm sorry but I find it extremely counterintuitive. I guess there are some nasty hacks under the hood here but I can't grasp them. 

Can you give some little insight on how is this working, and how the Traceback can be silenced, if at all possible?

Thanks.

**Comment by abidlabs** [comment]
Hi @Onturenio yes basically we try/catch it internally, display the traceback, and the skip the `.success()` function if an error has been handled. I don't think there's a way to _not_ print the traceback. 

What we need, in my opinion, are additional ways to chain that don't rely on exceptions being through. For example, a `.true()` method that runs the subsequent only if the previous event does not return a False-y value. Would that make sense for your workflow or do you have a different suggestion in mind?

**Comment by Onturenio** [comment]
Sure, I fully agree that it would be nice to have some more flexible way to chain events that allow to "cancel" it if certain conditions are not met. This would allow more complex applications and remove some of the flickering artifacts @JohnDuncanScott or myself are having when components are not actually being updated.

But I'm not sure how to handle the False-y value as the former action returns a set of `outputs` for gradio elements, not _a value_... I have been thinking and I believe a clean and general solution could be to have an additional parameter to the event listeners, something like `run`, which takes a function. Based on the inputs past to the event listener, the function past is evaluated, and if it is `True`, then the event is executed normally. Otherwise, the execution for this event listener is aborted and the elements are not updated at all.

I think this is more general and robust than the `success` approach, as you could achieve the behaviour with a `then` with this parameter, so avoiding the exception. Even better, in more simple scenarios, such as the example that opened this thread, you could avoid using nesting completely. You just would need to use the `run` parameter of the `input` event listener.

Does it make sense?
