### ISSUE TITLE
Add label to show_copy_button 

### ISSUE THREAD

**Issue by FurkanGozukara** [gradio-app/gradio#7521]
Can we add copy to clipboard label to this icon?

![image](https://github.com/gradio-app/gradio/assets/19240467/a2e2fa64-f3d1-4a16-ad85-c3d176b690b6)
 
Gradio latest version

`single_output = gr.Textbox(label="Single Image Captioning Results", interactive=True, show_copy_button=True )`

**Comment by abidlabs** [comment]
Hi @FurkanGozukara, do you mean adding the text "Copy to Clipboard" next to the copy icon? This change would by stylistically inconsistent with the other Gradio components and would be too crowded if the `gr.Textbox()` was taking up less horizontal space. For these reasons, we wouldn't provide an official gradio api for this. 

But if you'd like, you could make this tweak or any other tweaks if you create a custom component based off of the core Gradio Textbox component!

As you may know, we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.

**Comment by FurkanGozukara** [comment]
@abidlabs thank you so much. then i will pass :) i think perhaps you could add some styles like make it bigger more noticeable etc.
