### ISSUE TITLE
Real time applications (`input` trigger or `live=True`) fail on finishing sentences

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#7752]
### Describe the bug

For real time applications such as:
- https://huggingface.co/spaces/cyzgab/catch-me-if-you-can (`gr.Interface()` with `live=True`)
- https://huggingface.co/spaces/radames/Real-Time-Text-to-Image-SDXL-Lightning (`gr.Blocks()` with `input` trigger)

There seems to be an issue with bouncing/debouncing the real time text typed, in a way that the last thing one types is not processed properly. This issue happens when I'm typing fast, but not as much when I'm typing slower. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr 

def autocomplete(input):
    return input

iface = gr.Interface(
    fn=autocomplete,
    inputs=gr.Textbox(lines=2,
                      placeholder="Hello 👋",
                      label="Input Sentence"),
    outputs=gr.Markdown(),
    title="Live typing bug test",
    live=True,  # Set live to True for real-time feedback
    allow_flagging="never",  # Disable flagging
)
iface.launch()
```

https://huggingface.co/spaces/multimodalart/fast-typing-live-bug

### Screenshot

https://github.com/gradio-app/gradio/assets/788417/3244ebbf-b722-4552-98e7-173c933c33eb

### System Info

```shell
gradio==4.22.0
```

### Severity

I can work around it

**Comment by pngwn** [comment]
This is by design. When using blocks you should be able to set the `trigger_mode` of the event to either `“multiple”` or `”always_last”` to change the behaviour. Could you try this and see if it solves the problem?  I think this should be the default for change events so I’m not 100% sure if this will resolve the issue.

**Comment by apolinario** [comment]
But ignoring an input feels like a bug in any `trigger_mode`, no? I understand the difference between triggering for every word vs once someone "finishes" typing, but to me feels that something is broken if it doesn't react to some input. 

In the video I uploaded, even in the slow typing some letters get ignored

**Comment by apolinario** [comment]
`trigger_mode="always_last"` works well!

https://github.com/gradio-app/gradio/assets/788417/9c7567fb-acf1-41e2-84a0-e8eaf4019960

 What I'm failing to see is what's the advantage (or inner workings) of why it is not a bug the `multiple` behavior. All this live applications may suffer a bit from the user not seeing the output of the thing they wrapped with - unsure if I'm missing something

**Comment by pngwn** [comment]
Live life uses change events under the hood and they are supposed to have the `always_last` trigger mode, so that looks like a bug.

**Comment by pngwn** [comment]
The reason we have different modes is because that expensive compute triggered frequently for each user could hog the queue for a popular space. So depending on the type of inference, we want to give users some flexibility. For true 'realtime' demos obviously some of these modes don't really make sense.
