### ISSUE TITLE
How can two ChatInterface objects to access and modify the same variable

### ISSUE THREAD

**Issue by pcccccccccc** [gradio-app/gradio#7790]
### Describe the bug

I have defined two ChatInterface objects on a webpage, and I want these two ChatInterface objects to access and modify the same variable. I also want the access to this variable to be isolated for different users. How should I proceed?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
4.22
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
HI @pcccccccccc ! I think you'll have to use the `gr.Chatbot` component instead of `ChatInterface` and build your own logic for this case. The general idea is to use a `gr.State` component and pass it to both chatbots.

Going to close as this is not a gradio bug. Please continue the discussion on the huggingface discord in the gradio channels: https://discord.gg/hugging-face-879548962464493619
