### ISSUE TITLE
It is confusing to call render after gr.load

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#7996]
### Describe the bug

If you want to embed a loaded gradio app into a parent Blocks context you HAVE to do the following:

1. Call gr.load outside the parent blocks context
2. Then call `.render()` in the parent context, in the location you want to embedded app to appear

I'm wondering if we can make calling `gr.load(...)` once within the parent context work as expected?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Call `gr.load()` inside a parent block without render. The embedded app won't trigger its dependencies because render was not called.

### System Info

```shell
4.26.0
```

### Severity

I can work around it

**Comment by DeepeshKalura** [comment]
## Greetings
Hello @freddyaboulton , I am new open source in general and new to this repo, I would like to work on this issue.  
## Understanding
A way to when we call gr.load() inside a parent block it will trigger the dependencies without explicit tell to render.

Since, I never use gradio, I need some tips to get started and how can we can successfully resolve this bug. 
Currently just install code locally.
