### ISSUE TITLE
Gradio needs a way to change the 'temp' directory to a cloud storage bucket

### ISSUE THREAD

**Issue by peeter2** [gradio-app/gradio#8090]
I know it's possible to change just the directory using the env variable GRADIO_TEMP_DIR='temp' but I need this to be some file storage service (instead of the server where the app resides), otherwise the Gradio app is not stateless/scalable (as new container instances are added or removed) as it depends on the temp files on the server. 
I need to make every request independent of any data on the server. Is this possible?

**Comment by abidlabs** [comment]
Thanks @peeter2 — right now the recommended approach when working with containers is to set sticky headers so that requests from the same IP route to the same container, see https://www.gradio.app/guides/deploying-gradio-with-docker#important-considerations

I believe this should solve this issue but let us know if not

**Comment by abidlabs** [comment]
Will close for lack of follow up but let us know if this does not work for you.
