### ISSUE TITLE
Be able to pass the component loader to each svelte component

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#8257]
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
There are cases where a svelte component may need to load another component

- A Chatbot for displaying gradio components embedded into them
- A Dashboard custom component that loads several "@gradio/plot-components"

**Describe the solution you'd like**  
The `gradio` prop can have a `loader` attribute that can load any core or registered custom component.

**Additional context**

**Comment by pngwn** [comment]
We also need this to make the Examples dynamic I think.

**Comment by pngwn** [comment]
This is half implemented but it doesn't work for custom components.

The reason is that we request custom components via the component_class_id, this id is generated on the server and stored in the config, and is randomly generated at launch time. A user of an app has no way to access it.

The other issue is that the app doesn't know anything about a component until it is rendered.

We need to do one of two things:

- create some kind of 'register' API, that allows users to register a component by name: (`app.register('comp_name', CompClass))`
- Do something clever when 'returning' components from predict so we can somehow request the custom component inside of a component. I don't actually know how/ if this would work.

**Comment by pngwn** [comment]
I'll pad this out some more when @freddyaboulton has time to chat.

**Comment by freddyaboulton** [comment]
This is now possible via `gradio.load_component`! All you need to do is export a `gradio` prop in your component!
