### ISSUE TITLE
Connection errored out and new bug

### ISSUE THREAD

**Issue by pg56714** [gradio-app/gradio#8393]
### Describe the bug

After clicking on the examples, click again to directly display the results without needing to click 'submit'.

**I tried the same approach and found that others using Gradio on HuggingFace also have this issue where results are produced without needing to click submit. Three cases have been attached to the Google folder linked below.**

According to this question, Connection errored out will appear when pressing submit to execute.

This issue does not occur locally.

[huggingface discuss](https://discuss.huggingface.co/t/connection-errored-out-or-new-bug/88925)

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

[my huggingface space](https://huggingface.co/spaces/pg56714/Segment-Anything-Arena)

### Screenshot

[Three Cases](https://drive.google.com/drive/folders/1_APOIN3pkhuvcjlTtfyj24D4j0Gr6I0M?usp=sharing)

### System Info

```shell
The latest version(2024/05/28) 4.31.5
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @pg56714 - I think the problem is that clicking the examples updates the input image but you have a change event on the input image that clears the outputs.

https://huggingface.co/spaces/pg56714/Segment-Anything-Arena/blob/main/app.py#L202

I think you need to use `.clear` event, not a `change` event. 

Will close as this is behaving as expected.

**Comment by pg56714** [comment]
After further inspection, the issue was that gr.Examples was bound to fn, causing automatic execution when clicking on examples. It was resolved after removing that binding. Thank you.
