### ISSUE TITLE
Show Point Cloud in Model3D

### ISSUE THREAD

**Issue by buaacyw** [gradio-app/gradio#8459]
- [√ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
People sometimes need to visualize point cloud in 3D generation pipeline.

**Describe the solution you'd like**  
Adding Point Cloud visualization support in Model3D. The file Format might be ply. Support save format like Trimesh.PointCloud from [here](https://trimesh.org/trimesh.html#trimesh.PointCloud).

**Comment by jytime** [comment]
Hi @buaacyw @abidlabs 

I am making a demo which is related to this. May I ask if there is any update on this?

What I am doing now is using trimesh.Scene() to load a point cloud, save it as a .glb file and pass it to gradio.Model3D. The problem here is, the visualised points are too small and usually hard to distinguish. It can be checked at this hugging face demo https://huggingface.co/spaces/facebook/vggsfm.

I attempted to enhance visibility by defining a sphere for each 3D point:
```
        point_size = 0.05  

        for point, color in zip(points3D, points3D_rgb):
            sphere = trimesh.creation.icosphere(subdivisions=2, radius=point_size)
            sphere.apply_translation(point)
            sphere.visual.vertex_colors = [color] * len(sphere.vertices)
            glbscene.add_geometry(sphere)
```
However, this method is too slow, especially for point clouds with over 1M points.

It would be much appreciated if Gradio could support better visualization of point clouds, as it is a common use case in the 3D community. Thank you :)

**Comment by dawoodkhan82** [comment]
@buaacyw @jytime Releasing soon! https://github.com/gradio-app/gradio/pull/8687
