### ISSUE TITLE
Issues with Gradio ImageMask

### ISSUE THREAD

**Issue by Xelawk** [gradio-app/gradio#8490]
Description:

The behavior of ImageMask is different from Image. It is not possible to upload an image by clicking in the middle of the container; you need to click a small button to upload.
When the uploaded image is too large, it does not adapt to the container size like Image does. Instead, it exceeds the height limit of the container's bounding box.

**Comment by Xelawk** [comment]
the attribute height of ImageMask can't afftect the image to display

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue yet, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio
