### ISSUE TITLE
If you turn on https to download the file, it will show Please check your network connection

### ISSUE THREAD

**Issue by IdleIdiot** [gradio-app/gradio#8681]
### Describe the bug

trun on https，and code click button return gr.components.File，then wait about 5s， click download link，browser show the download error.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```shell
root@ai-ubuntu:~# touch /tmp/debug_file_in_server
root@ai-ubuntu:~# 

```

```python
import json

import gradio as gr


def debug():
    return "/tmp/debug_file_in_server"


def setup_resource_chart():
    with gr.Blocks() as app:

        show_button = gr.Button("history")

        file_exporter = gr.components.File(label="download")

        show_button.click(
            fn=debug,
            inputs=[],
            outputs=[
                file_exporter,
            ],
        )

    return app


if __name__ == "__main__":
    with open("settings.json") as f:
        settings = json.loads(f.read())
    app = setup_resource_chart()
    app.launch(
        share=True,
        inbrowser=False,
        server_name="0.0.0.0",
        server_port=9528,
        show_api=False,
        ssl_keyfile=settings["pages"]["ssl"]["key"],
        ssl_certfile=settings["pages"]["ssl"]["pem"],
        ssl_verify=False,
    )


```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/49224652/44cbd060-00b6-4bdf-a588-9ed529c202e5)

![image](https://github.com/gradio-app/gradio/assets/49224652/9692e14c-8ff1-4bfd-9cf1-8e11077251b4)

### System Info

```shell
(llm-experience) root@ai-ubuntu:/data/wanghui01/llm-experience/inference/frontend# gradio environment
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.29.0
gradio_client version: 0.16.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==0.16.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.0
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.9.15
packaging: 23.2
pandas: 1.5.3
pillow: 10.2.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.4
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.10.0
urllib3: 2.2.1
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.3.1
httpx: 0.27.0
huggingface-hub: 0.22.0
packaging: 23.2
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by IdleIdiot** [comment]
Network packet capture
<img width="925" alt="d04da784f779fd0e6be48ecab51f749" src="https://github.com/gradio-app/gradio/assets/49224652/d60ca11e-171f-4194-8ebe-d81658386dbc">

**Comment by pcasagranda** [comment]
Same problem. Using HTTPS with gradio we can download a file we generate for a few seconds. Then we have "Please check your network connection" in the browser.

**Comment by shaoqingyang** [comment]
How to deal with this bug.

**Comment by Isuxiz** [comment]
Occurred on me. How to solve / work around this problem, may @IdleIdiot share you idea plz?

**Comment by Isuxiz** [comment]
After half a day of wrestling with this problem, I found a (not perfect) solution: use a verified rather than self-signed ssl certificate. In fact this is a problem with browsers such as chrome. In the browser, an unverified SSL certificate (self-signed one) will prompt an insecure https link, explicitly telling the browser to go on will allow you to successfully reach Gradio app, but when downloading files, especially if it is the second time or after waiting for a while, the error will still occur.

In short, my actions are as follows:
1. Change gradio itself to http mode, assuming I let it run on port 999
2. Prepare an https domain name
3. Use a reverse proxy tool, nginx for me, to forward https on a certain port to the http service on port 999

So far, my app works great, whether it's downloading files or using the microphone or camera which requires https permissions.
If you work for a company, you can consult your Operations Engineers.
If you are an individual developer, you may need to find a CA to issue a widely recognized certificate for you, which may be free or paid.

**Comment by IdleIdiot** [comment]
Thanks to Isuxiz, I think this is a great approach.
