### ISSUE TITLE
Ability to select a chat bubble to copy/edit/delete?

### ISSUE THREAD

**Issue by piovis2023** [gradio-app/gradio#9096]
- [Y ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
A mistake in a conversation is currently perm when using gradio, unlike ChatGPT or Anthropic, where you can edit or delete a previous message and continue from that point. 
Its very hard to efficiently achieve goals if a mistake is made in conversation, either by the LLM or myself

**Describe the solution you'd like**  
I need to be able to select a chat bubble/message and edit or delete it.
The icons should be similar to the vote up/vote down/ like icons next to each message that you currently have.
When a bubble is selected, it should change colour to show it has been selected

**Additional context**  
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/206c4e4d-a4e3-4d1e-828d-805fc7ce420c">

**Comment by PiovisTeam** [comment]
@freddyaboulton @abidlabs could you please help with the above? I see it's been marked as an enhancement. We have reached out via email too for help on this. Thanks.

**Comment by abidlabs** [comment]
Hi @PiovisTeam @piovis2023 we are unlikely to add this to the Gradio Chatbot but I think this would be a great case for a custom component!

we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

If you'd like to create your own (templating off of the `gr.Chatbot` component), we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
