### ISSUE TITLE
Static file server to host HTML file rather than download as an attachment

### ISSUE THREAD

**Issue by jinsanity07git** [gradio-app/gradio#9146]
I developed an app with `gradio==4.19.1`  use the `/file` file path feature to embed a JS heavy HTML file in the iframe string in order to render the page in the HTML component.

However, when I upgrade to the `gradio==4.41.0`,  I found it broke my code, for now when I embed the file URL, it only prompt a file download action in the browser.

Here is the change I observed in  `gradio==4.41.0\route.py`:

```python
            return FileResponse(
                abs_path,
                headers={"Accept-Ranges": "bytes"},
                content_disposition_type="attachment",
                media_type="application/octet-stream",
            )
```

the reason I thought is related to the  `content_disposition_type="attachment"`.

My question is about is there any easy solution for me to use gradio as a static file server to render the HTML page in the newest version?

Any experience and advise is appreciated!

**Comment by abidlabs** [comment]
Hi @jinsanity07git I believe this is intended behavior. This change was made for security reasons (to prevent Gradio from being used for cross-site scripting purposes. We'll do official communication later, but wanted to provide context). But just to make sure I understand correctly, can you provide a repro to illustrate what kind of Gradio app no longer works for you?

**Comment by jinsanity07git** [comment]
[gradio_iframe_demo.zip](https://github.com/user-attachments/files/16663965/gradio_iframe_demo.zip)
Thank you @abidlabs for the quick response, here is a demo repo for this purpose

**Comment by luiarthur** [comment]
Hi,

I think this is related to serving static files in general, and not unique to HTML/JS. Here's a short demo:

`app.py`
```python
import gradio as gr

static_path = 'static'
# NOTE: The following doesn't help either.
# gr.set_static_paths(paths=[static_path])

with gr.Blocks() as demo:
    gr.HTML("<h1>Serving static files</h1>")
    gr.HTML(f"<a href='file={static_path}/foo.txt'>foo.txt</a>")
    gr.HTML(f"<a href='file={static_path}/foo.txt'>foo.txt</a>")
    gr.Markdown(f"[foo.txt](file={static_path}/foo.txt)")

# Run the interface
demo.launch(allowed_paths=[static_path])
```

`foo.txt`
```
Nothing to see here.
```

Tested with `python==3.12`, `gradio==4.41.0` and `gradio_client==1.3.0`.

Served with `python app.py` or `gradio app.py`.

As @jinsanity07git said, clicking on any of the links starts a download of `foo.txt`, instead of a view of the files in the browser.

**Comment by abidlabs** [comment]
@luiarthur we are fixing it for media files (including .txt files and most other extensions) in this PR: https://github.com/gradio-app/gradio/pull/9151

However, HTML files are a special case -- to prevent XSS, we are intentionally rendering them as an attachment so they are downloaded instead of immediately rendered in the browser

**Comment by luiarthur** [comment]
> @luiarthur we are fixing it for media files (including .txt files and most other extensions) in this PR: #9151
> 
> However, HTML files are a special case -- to prevent XSS, we are intentionally rendering them as an attachment so they are downloaded instead of immediately rendered in the browser

Awesome, thanks! Sorry for duplicating here.

**Comment by abidlabs** [comment]
Hi @jinsanity07git yes upon further thought, this is something we are not going to support by design, as it could pose a risk for cross-site scripting. I would encourage you to host/serve the HTML file elsewhere where you can set the headers yourself, as this isn't really an intended use for Gradio applications. Sorry about the inconvenience
