### ISSUE TITLE
[Slider] - Fixed range steps

### ISSUE THREAD

**Issue by elismasilva** [gradio-app/gradio#9283]
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
**Describe the solution you'd like**  
Is it possible to improve the slider component to allow specifying the interval jumps when moving the horizontal bar? For example I don't have fixed steps, I want to be able to go from 0 to 0.4 from 0.4 to 0.10 from 0.10 to 0.14 from 0.14 to 0.17. I think it would be something similar to the "choices" we have in the dropdown where we can pass the values ​​in order [0, 0.4, 0.10, 0.14, 0.17]

**Comment by abidlabs** [comment]
Thanks @elismasilva, I think this would be a great case for a custom component!

we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

If you'd like to create your own, you can template off of the `gr.Slider`, and we've put together a Guide to explain this: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
