### ISSUE TITLE
Replace gr.Image "switch camera" icon with another icon

### ISSUE THREAD

**Issue by Insulinocytus** [gradio-app/gradio#9290]
- [x] I have searched to see if a similar issue already exists.

## Is your feature request related to a problem? Please describe.

The `take photo` button and the `switch camera` button look like the same button.

## Describe the solution you'd like 

[gradio.Image](https://www.gradio.app/docs/gradio/image) provides an image upload window and supports taking photos using the web camera.
But I think there is a slight flaw in the UI design.

Please see the following example GIF (from [WinSCP](https://github.com/winscp/winscp))：
![1](https://github.com/user-attachments/assets/c87dc827-a6ea-44ac-98f4-17e28e00e51b)

The Properties button can open the property of the file. And this button has some other additional options, so there is an inverted triangle button next to it that can open a drop-down menu. But in order to tell the user that these are two buttons, there is a line between Properties and the inverted triangle. 

Just like the New button in the GIF, if there is no such line, it means this button is a button used to open a drop-down menu.

While most users won't consider this a problem, I have a "bad habit" of clicking the triangle first to see if there are any additional options I can use. This resulted in me spending about 10 minutes trying to find where the `take photo` button was. Finally I discovered that 📷 and 🔻 are actually two buttons.

My suggestion is to replace the 🔻 with another icon that is the same size as the 📷.

**Comment by abidlabs** [comment]
Thanks @Insulinocytus, let me cc @hannahblair for visibility. Personally, I don't think we'll change the UI here, but if you'd like this could be a great case for a custom component!

we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

If you'd like to create your own, you can template off of the `gr.Image` component and make the UI modification you suggested, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
