### ISSUE TITLE
DataFrame axis names ? To customize the "New Row" / "New Column" buttons

### ISSUE THREAD

**Issue by lhoestq** [gradio-app/gradio#9394]
e.g. in my dataset app there is an option to edit the columns and types of a dataset, I use a DataFrame for that but it feels confusing to have a button "New Row" while each row in the DataFrame corresponds to a dataset column name + type

In my case I would like the button to display "New dataset column" for example

![image](https://github.com/user-attachments/assets/c448038d-0d4b-447a-928f-95b4095ad9e9)

Otherwise let me know if you think of another way of fixing this confusion ?

**Comment by abidlabs** [comment]
Hi @lhoestq this isn't something we expose in our api, but its something we can consider in the future

**Comment by abidlabs** [comment]
We've redesigned the Dataframe component so that now there is a context menu instead. We are not likely to allow customization of every item in the menu because, among other things, we i18n these values. I would instead suggest creating a custom component, which should be pretty since its just modifying a few strings in the JS.
If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.

**Comment by lhoestq** [comment]
thanks @abidlabs !
