### ISSUE TITLE
Access filename of uploaded image file

### ISSUE THREAD

**Issue by shubham-goel-zefr** [gradio-app/gradio#943]
When an image file object is uploaded, you cannot retrieve it's original filename. You can only get the temporary filename associated with it. I'm using the flagging feature to log mistakes in my model, and then use the generated csv to further retrain my model. It'd be helpful if instead of Image/0.png, Image/1.png, and so on, I get the ability to use the original filename in the longs.

**Describe the solution you'd like**
1. Modify the flagging option to use the original filename instead of a iterator starting from 0. 
2. Have access to the original filename, when the type of input image is set to 'pil'.

**Comment by abidlabs** [comment]
Thanks @shubham-goel-zefr, this makes sense. Let us look into seeing if we can implement this.

**Comment by stunlocked1** [comment]
can this be added to gradio.components.Audio?

**Comment by joshwilson-dev** [comment]
Is this included in Gradio 4.0 yet? If so, how do I access the filename from the uploaded image object?

**Comment by marcelloexp386** [comment]
I have a similar question. Is it possible to keep the datetime of the original picture shot in the metainformation of the uploaded image? In the case I am working on, I am more interested in knowing the time when an uploaded image was shot than the original name. In any case, if the name of the uploaded image could be preserved would represent a great help because with (Samsung) Android the name of the jpeg file of the picture taken by your smartphone is the timestamp of the shot.
