### ISSUE TITLE
Support .amr file for audio component

### ISSUE THREAD

**Issue by jeremy-k3** [gradio-app/gradio#9434]
- [ X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When using an Audio component, Gradio does not support .amr file and returns an error.

**Describe the solution you'd like**  
Support for .amr file

**Additional context**  
People find all types of audio files and thiey had to convert it to mp3 first. That's an OK workaround but if it does not cost much to support it in Gradio, that would be top

**Comment by abidlabs** [comment]
Hi @jeremy-k3, the main issue issue is that the wavesurfer library that we use in the frontend [does not support amr files](https://github.com/katspaugh/wavesurfer.js/discussions/2703), so if you were to upload an amr file, you would not get the waveform display. However, it would get preprocessed and you could use it in your prediction function. 

You can test that with a simple example:

```py
import gradio as gr

gr.Interface(lambda x:x, "audio", "audio").launch()
```

On the output side, its easy to coerce it to be a .wav file or a different format, which Gradio can easily display in the wavesurfer frontend, like this:

```py
import gradio as gr

gr.Interface(lambda x:x, "audio", gr.Audio(format="wav")).launch()
```

I also think this would be a great case for a custom component where you can use the same `gr.Audio` component, but with your own frontend js library.

Context: we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

If you'd like to create your own based off of the `gr.Audio` component, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
