### ISSUE TITLE
[blocks] optional labels for certain inputs

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#946]
For most form elements, labels are required for accessibility reasons but for _outputs_ the case is less clear. They certainly need useful descriptions but since they are not interactive form elements, the accesibility considerations are more around readability.

We need  to figure out how/ where we can make certain labels optional without compromising end user usabilty or accessibility.

Continuation of #704.

**Comment by abidlabs** [comment]
Hi @pngwn I was looking into this and it looks like labels needed to be provided for accessibility reasons, but they don't necessarily need to be _visible_:

> A label for a form control helps everyone better understand its purpose. In some cases, the purpose may be clear enough from the context when the content is rendered visually. The label can be hidden visually, though it still needs to be provided within the code to support other forms of presentation and interaction, such as for screen reader and speech input users. The method used in this tutorial to hide an element visually but make it available for assistive technologies is explained in [Note on hiding element](https://www.w3.org/WAI/tutorials/forms/labels/#note-on-hiding-elements).

Source: https://www.w3.org/WAI/tutorials/forms/labels/

I think it would be nice if people can make the labels invisible because sometimes they clutter up the UI or look out of place. What do you think about adding a "hide_label" boolean parameter to each of the form elements? False by default, but can be set to True, which makes the label invisible.

**Comment by pngwn** [comment]
Works for me, tailwind has a class for that: https://tailwindcss.com/docs/screen-readers
