### ISSUE TITLE
[DOCS] Embedding components themselves in the documentation 

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#950]
It would be super cool for users to immediately see what a component looks like directly within docs, as well as be able to modify the parameters and see what changes.

**Comment by aliabd** [comment]
Example:  

Still need to allow users to modify parameters. 

https://user-images.githubusercontent.com/9021060/162327084-5e4c7518-3137-4e5d-b284-07611b19250b.mov

**Comment by abidlabs** [comment]
This is SO COOL!

**Comment by abidlabs** [comment]
I think we should definitely feature this prominently on the website. In addition to the technical reference, what do you think about having a separate gallery of all of the components for a better UX?

You can browse through all of the components, if you click on a component, you see: its docstring, its demos, its guides, you can play around with its parameters and you see a live preview -- basically all this stuff here but in a dedicated page for the component because the docs can be kind of overwhelming

**Comment by aliabd** [comment]
Started implementing parameter tweaking for components 

https://user-images.githubusercontent.com/9021060/163043977-f6f006de-72b7-4132-8db1-a28a8e8ca32b.mov

Love the components gallery idea. I think the docs page is getting super crowded so would be better to make space

**Comment by abidlabs** [comment]
Beautiful, great job @aliabd and @aliabid94!
