### ISSUE TITLE
Support older versions of python in gradio 5

### ISSUE THREAD

**Issue by not-lain** [gradio-app/gradio#9634]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Gradio 5 does not work on older versions of Python
context : https://github.com/gradio-app/gradio/issues/9463#issuecomment-2383768357

**Describe the solution you'd like**  

to support versions that are using 3.9 
```python
from __future__ import annotations
```
at the top of each file that uses any typing features.

Although some resources that I checked are conflicting if either this fixes support for only 3.9 or (3.9 backwards till 3.7), I am certain that it would fix any problems with 3.9 in all cases.

**Additional context**  
sources : 
* https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations
* https://stackoverflow.com/questions/61544854/from-future-import-annotations
* https://discuss.python.org/t/what-within-future-made-list-str-start-working-on-3-7/5428

**Comment by pngwn** [comment]
There is more to supporting 3.9 in gradio than just this, there are other places where supporting older versions added complexity or gave a worse experience. 

Dropping support for older versions of Python  was intentional in this release as it frees us up robust modern syntax in the future. Updating to 3.10 isn't an unreasonable ask in 2024.
