### ISSUE TITLE
Missing Multiple Outputs

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#974]
### Describe the bug

There should be 3 outputs with this example, however there is only one.

Reported by Nicholas Broad.

### Reproduction

One of the examples within our docs:

https://colab.research.google.com/drive/1MJ5Kz67ghYprPxJBjOal66VFU_CK2lqG

### Screenshot

![image](https://user-images.githubusercontent.com/44067394/162759003-23daa93e-9dac-4ef5-ac76-db57c9466be5.png)

### System Info

```shell
google colab
```

### Severity

critical

**Comment by abidlabs** [comment]
Very strange. Haven't looked into this deeply, but just want to add that the issue seems specific to this demo or this set of outputs. In general, multiple outputs are working fine as can be seen with this simple example:

![image](https://user-images.githubusercontent.com/1778297/162802174-519fbf44-df03-49c6-920b-15de8eebff89.png)

**Comment by nbroad1881** [comment]
If you change the middle output in the colab notebook to text it works fine. Formatting looks a bit off, but all three outputs are there.

**Comment by abidlabs** [comment]
The keyvalues component has been deprecated -- if you change it to `json`, then this demo now works with the latest version of Gradio (2.9.0b2). Thanks @FarukOzderim and @nbroad1881 for creating the issue.
![image](https://user-images.githubusercontent.com/1778297/164069881-0f625777-b0b2-43ed-bf93-27116b409c54.png)
