### ISSUE TITLE
Option to get 2d image from `Image3D` input

### ISSUE THREAD

**Issue by johnPertoft** [gradio-app/gradio#998]
Maybe a very niche usecase, but I would like to have the option of passing a 2d representation of the `Model3D` / `Image3D` input to the wrapped function, e.g. just grabbing the current state of the canvas as an image and using that as the input.

**Comment by abidlabs** [comment]
Hi @johnPertoft, I think this would be a great case for a custom component!

we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

If you'd like to create your own, we've put together a Guide: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
