### ISSUE TITLE
Custom Chatbot avatar image for each individual message

### ISSUE THREAD

**Issue by mc-marcocheng** [gradio-app/gradio#9993]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently Chatbot only supports user and bot avatar images.

**Describe the solution you'd like**  
Situations:
- Dynamic avatar image: Users may want to upload their own avatar image.
- Different avatar images for different agent tools response
- System message avatar image

**Additional context**  
I hope we can pass the avatar image url inside the "metadata" of each message.

**Comment by abidlabs** [comment]
Hi @mc-marcocheng thanks for opening this issue. I don't think we'll add this functionality to the core chatbot component, but  this would be a great case for a custom component!

The tldr is that we've made it possible for Gradio users to create their own custom components -- meaning that you can write some Python and JavaScript (Svelte), and publish it as a Gradio component. You can use it in your own Gradio apps, or share it so that anyone can use it in their Gradio apps. 

Here's an example of a Gradio custom component: https://github.com/PhyscalX/gradio-image-prompter -- it lets you upload images and process points or draw boxes on top of the image.

If you'd like to create your own, you can just "clone" or template off of the existing gr.Chatbot component, we've put together a Guide that explains this: https://www.gradio.app/guides/five-minute-guide, and we're happy to help.
